### ISSUE TITLE
Pod scraping requires annotations despite explicit target configuration

### ISSUE THREAD

**Issue by wardbekker** [grafana/k8s-monitoring-helm#1009]
### Current Behavior
When attempting to scrape profiles from a pod using explicit target configuration in Helm values, the scraping fails unless specific Grafana profile annotations are present on the target pod.

### Expected Behavior
Profile scraping should work based solely on the explicit target configuration in Helm values, without requiring additional pod annotations.

### Configuration
Currently using this Helm values configuration:
```yaml
profiling:
  enabled: true
  destinations: ["pyroscope"]
  scrape:
    enabled: true
    targets:
      - "__address__": "demo-bank.default.svc.cluster.local:8080"
        "service_name": "demo-bank"
```

The following annotations are currently required for scraping to work:
```yaml
profiles.grafana.com/cpu.scrape: "true"
profiles.grafana.com/cpu.port_name: "pprof"
profiles.grafana.com/godeltaprof_memory.scrape: "true"
profiles.grafana.com/godeltaprof_memory.port_name: "pprof"
profiles.grafana.com/godeltaprof_mutex.scrape: "true"
profiles.grafana.com/godeltaprof_mutex.port_name: "pprof"
profiles.grafana.com/godeltaprof_block.scrape: "true"
profiles.grafana.com/godeltaprof_block.port_name: "pprof"
profiles.grafana.com/goroutine.scrape: "true"
profiles.grafana.com/goroutine.port_name: "pprof"
profiles.grafana.com/memory.scrape: "true"
profiles.grafana.com/memory.port_name: "pprof"
profiles.grafana.com/mutex.scrape: "true"
profiles.grafana.com/mutex.port_name: "pprof"
profiles.grafana.com/block.scrape: "true"
profiles.grafana.com/block.port_name: "pprof"
```

### Impact
This creates unnecessary configuration overhead and makes the explicit target configuration in Helm values ineffective on its own.

### Additional Context
The explicit target configuration in Helm values should take precedence over or eliminate the need for pod annotations, as it provides all necessary information for scraping.
