### ISSUE TITLE
`applicationObservability.[type].filters.[type]` is broken in 2.0.0-rc.10

### ISSUE THREAD

**Issue by WesselAtWork** [grafana/k8s-monitoring-helm#1024]
# Problem

I might be missing something, but I can't get [filters](https://github.com/grafana/k8s-monitoring-helm/blob/v2.0.0-rc.10/charts/feature-application-observability/README.md#other-values) to work

From some searching around, it doesn't look like there is a different way to do **filters** but there is multiple ways to do **transformations** like:
* [applicationObservability](https://github.com/grafana/k8s-monitoring-helm/blob/v2.0.0-rc.10/charts/feature-application-observability/README.md#other-values)
* [destinations](https://github.com/grafana/k8s-monitoring-helm/blob/v2.0.0-rc.10/charts/k8s-monitoring/docs/destinations/otlp.md#transform-processor)

I feel like I am making a mistake somehow, but even after fiddling with the templates, I still couldn't get it render.

> The fact that `transformations` work is extra maddening

# Minimal `values.yaml`

```yaml
cluster:
  name: somecluster
destinations:
  - name: example
    type: otlp
    url: example.org:7134
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}

clusterMetrics:
  enabled: false
clusterEvents:
  enabled: false
podLogs:
  enabled: false
applicationObservability:
  enabled: true
  traces:
    transforms:
      span: ["thisworks"]
    filters:
      span: ["thisdoesnot"]
      spanevent: ["thisdoesnot"]
  metrics:
    filters:
      metric: ["thisdoesnot"]
      datapoint: ["thisdoesnot"]
  logs:
    filters:
      log_record: ["thisdoesnot"]
  receivers:
    otlp:
      http:
        enabled: true
      grpc:
        enabled: true

annotationAutodiscovery:
  enabled: false
prometheusOperatorObjects:
  enabled: false
profiling:
  enabled: false
integrations:
  enabled: false
selfReporting:
  enabled: false
autoInstrumentation:
  enabled: false

alloy-metrics:
  enabled: false

alloy-singleton:
  enabled: false

alloy-logs:
  enabled: false

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

```
---

```sh
cd k8s-monitoring
helm template . -f "values.yaml" -f "my-values.yaml"  --generate-name --debug --dry-run
```

<details>
<summary>Generated</summary>

```yaml
---
# Source: k8s-monitoring/charts/alloy-receiver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-alloy-receiver
  namespace: default
  labels:
    helm.sh/chart: alloy-receiver-0.10.1
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/instance: release-name
    
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
---
# Source: k8s-monitoring/charts/applicationObservability/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-applicationobservability
  namespace: default
data:
  module.alloy: |-    
    declare "application_observability" {
      argument "metrics_destinations" {
        comment = "Must be a list of metrics destinations where collected metrics should be forwarded to"
      }
    
      argument "logs_destinations" {
        comment = "Must be a list of log destinations where collected logs should be forwarded to"
      }
    
      argument "traces_destinations" {
        comment = "Must be a list of trace destinations where collected trace should be forwarded to"
      }
    
      // Receivers --> Resource Detection Processor  
      otelcol.receiver.otlp "receiver" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        http {
          endpoint = "0.0.0.0:4318"
        }
        debug_metrics {
          disable_high_cardinality_metrics = true
        }
        output {
          metrics = [otelcol.processor.resourcedetection.default.input]
          logs = [otelcol.processor.resourcedetection.default.input]
          traces = [otelcol.processor.resourcedetection.default.input]
        }
      }    
    
      // Resource Detection Processor --> K8s Attribute Processor  
      otelcol.processor.resourcedetection "default" {
        detectors = ["env", "system"]
        system {
          hostname_sources = ["os"]
        }
      
        output {
          metrics = [otelcol.processor.k8sattributes.default.input]
          logs = [otelcol.processor.k8sattributes.default.input]
          traces = [otelcol.processor.k8sattributes.default.input]
        }
      }
    
      // K8s Attribute Processor --> Transform Processor
      // Resource Detection Processor Traces --> Host Info Connector  
      otelcol.processor.k8sattributes "default" {
        extract {
          metadata = ["k8s.namespace.name","k8s.pod.name","k8s.deployment.name","k8s.statefulset.name","k8s.daemonset.name","k8s.cronjob.name","k8s.job.name","k8s.node.name","k8s.pod.uid","k8s.pod.start_time"]
        }
        pod_association {
          source {
            from = "connection"
          }
        }
      
        output {
          metrics = [otelcol.processor.transform.default.input]
          logs = [otelcol.processor.transform.default.input]
          traces = [otelcol.processor.transform.default.input, otelcol.connector.host_info.default.input]
        }
      }
      // Host Info Connector --> Batch Processor  
      otelcol.connector.host_info "default" {
        host_identifiers = [ "k8s.node.name" ]
      
        output {
          metrics = [otelcol.processor.batch.default.input]
        }
      }
    
    
      // Transform Processor --> Batch Processor  
      otelcol.processor.transform "default" {
        error_mode = "ignore"
        log_statements {
          context = "resource"
          statements = [
            "set(attributes[\"pod\"], attributes[\"k8s.pod.name\"])",
            "set(attributes[\"namespace\"], attributes[\"k8s.namespace.name\"])",
            "set(attributes[\"loki.resource.labels\"], \"cluster, namespace, job, pod\")",
          ]
        }
        trace_statements {
          context = "span"
          statements = [
            "thisworks",
          ]
        }
      
        output {
          metrics = [otelcol.processor.batch.default.input]
          logs = [otelcol.processor.batch.default.input]
          traces = [otelcol.processor.batch.default.input]
        }
      }
    
      // Batch Processor --> Destinations  
      otelcol.processor.batch "default" {
        output {
          metrics = argument.metrics_destinations.value
          logs = argument.logs_destinations.value
          traces = argument.traces_destinations.value
        }
      }
    }
---
# Source: k8s-monitoring/templates/alloy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-alloy-receiver
  namespace: default
data:
  config.alloy: |-
    // Destination: example (otlp)
    otelcol.receiver.prometheus "example" {
      output {
        metrics = [otelcol.processor.attributes.example.input]
      }
    }
    otelcol.receiver.loki "example" {
      output {
        logs = [otelcol.processor.attributes.example.input]
      }
    }
    
    otelcol.processor.attributes "example" {
      action {
        key = "cluster"
        action = "upsert"
        value = "somecluster"
      }
      action {
        key = "k8s.cluster.name"
        action = "upsert"
        value = "somecluster"
      }
      output {
        metrics = [otelcol.processor.transform.example.input]
        logs = [otelcol.processor.transform.example.input]
        traces = [otelcol.processor.transform.example.input]
      }
    }
    
    otelcol.processor.transform "example" {
      error_mode = "ignore"
    
      output {
        metrics = [otelcol.processor.batch.example.input]
        logs = [otelcol.processor.batch.example.input]
        traces = [otelcol.processor.batch.example.input]
      }
    }
    
    otelcol.processor.batch "example" {
      timeout = "2s"
      send_batch_size = 8192
      send_batch_max_size = 0
    
      output {
        metrics = [otelcol.exporter.otlp.example.input]
        logs = [otelcol.exporter.otlp.example.input]
        traces = [otelcol.exporter.otlp.example.input]
      }
    }
    otelcol.exporter.otlp "example" {
      client {
        endpoint = "example.org:7134"
        tls {
          insecure = false
          insecure_skip_verify = false
        }
      }
    }
    
    // Feature: Application Observability
    declare "application_observability" {
      argument "metrics_destinations" {
        comment = "Must be a list of metrics destinations where collected metrics should be forwarded to"
      }
    
      argument "logs_destinations" {
        comment = "Must be a list of log destinations where collected logs should be forwarded to"
      }
    
      argument "traces_destinations" {
        comment = "Must be a list of trace destinations where collected trace should be forwarded to"
      }
    
      // Receivers --> Resource Detection Processor  
      otelcol.receiver.otlp "receiver" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        http {
          endpoint = "0.0.0.0:4318"
        }
        debug_metrics {
          disable_high_cardinality_metrics = true
        }
        output {
          metrics = [otelcol.processor.resourcedetection.default.input]
          logs = [otelcol.processor.resourcedetection.default.input]
          traces = [otelcol.processor.resourcedetection.default.input]
        }
      }    
    
      // Resource Detection Processor --> K8s Attribute Processor  
      otelcol.processor.resourcedetection "default" {
        detectors = ["env", "system"]
        system {
          hostname_sources = ["os"]
        }
      
        output {
          metrics = [otelcol.processor.k8sattributes.default.input]
          logs = [otelcol.processor.k8sattributes.default.input]
          traces = [otelcol.processor.k8sattributes.default.input]
        }
      }
    
      // K8s Attribute Processor --> Transform Processor
      // Resource Detection Processor Traces --> Host Info Connector  
      otelcol.processor.k8sattributes "default" {
        extract {
          metadata = ["k8s.namespace.name","k8s.pod.name","k8s.deployment.name","k8s.statefulset.name","k8s.daemonset.name","k8s.cronjob.name","k8s.job.name","k8s.node.name","k8s.pod.uid","k8s.pod.start_time"]
        }
        pod_association {
          source {
            from = "connection"
          }
        }
      
        output {
          metrics = [otelcol.processor.transform.default.input]
          logs = [otelcol.processor.transform.default.input]
          traces = [otelcol.processor.transform.default.input, otelcol.connector.host_info.default.input]
        }
      }
      // Host Info Connector --> Batch Processor  
      otelcol.connector.host_info "default" {
        host_identifiers = [ "k8s.node.name" ]
      
        output {
          metrics = [otelcol.processor.batch.default.input]
        }
      }
    
    
      // Transform Processor --> Batch Processor  
      otelcol.processor.transform "default" {
        error_mode = "ignore"
        log_statements {
          context = "resource"
          statements = [
            "set(attributes[\"pod\"], attributes[\"k8s.pod.name\"])",
            "set(attributes[\"namespace\"], attributes[\"k8s.namespace.name\"])",
            "set(attributes[\"loki.resource.labels\"], \"cluster, namespace, job, pod\")",
          ]
        }
        trace_statements {
          context = "span"
          statements = [
            "thisworks",
          ]
        }
      
        output {
          metrics = [otelcol.processor.batch.default.input]
          logs = [otelcol.processor.batch.default.input]
          traces = [otelcol.processor.batch.default.input]
        }
      }
    
      // Batch Processor --> Destinations  
      otelcol.processor.batch "default" {
        output {
          metrics = argument.metrics_destinations.value
          logs = argument.logs_destinations.value
          traces = argument.traces_destinations.value
        }
      }
    }
    application_observability "feature" {
      metrics_destinations = [
        otelcol.processor.attributes.example.input,
      ]
      logs_destinations = [
        otelcol.processor.attributes.example.input,
      ]
      traces_destinations = [
        otelcol.processor.attributes.example.input,
      ]
    }
---
# Source: k8s-monitoring/charts/alloy-receiver/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-alloy-receiver
  labels:
    helm.sh/chart: alloy-receiver-0.10.1
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/instance: release-name
    
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
rules:
  # Rules which allow discovery.kubernetes to function.
  - apiGroups:
      - ""
      - "discovery.k8s.io"
      - "networking.k8s.io"
    resources:
      - endpoints
      - endpointslices
      - ingresses
      - nodes
      - nodes/proxy
      - nodes/metrics
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  # Rules which allow loki.source.kubernetes and loki.source.podlogs to work.
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "monitoring.grafana.com"
    resources:
      - podlogs
    verbs:
      - get
      - list
      - watch
  # Rules which allow mimir.rules.kubernetes to work.
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - prometheusrules
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  # Rules for prometheus.kubernetes.*
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - podmonitors
      - servicemonitors
      - probes
    verbs:
      - get
      - list
      - watch
  # Rules which allow eventhandler to work.
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  # needed for remote.kubernetes.*
  - apiGroups: [""]
    resources:
      - "configmaps"
      - "secrets"
    verbs:
      - get
      - list
      - watch
  # needed for otelcol.processor.k8sattributes
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
# Source: k8s-monitoring/charts/alloy-receiver/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-alloy-receiver
  labels:
    helm.sh/chart: alloy-receiver-0.10.1
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/instance: release-name
    
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-alloy-receiver
subjects:
  - kind: ServiceAccount
    name: release-name-alloy-receiver
    namespace: default
---
# Source: k8s-monitoring/charts/alloy-receiver/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-alloy-receiver
  labels:
    helm.sh/chart: alloy-receiver-0.10.1
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/instance: release-name
    
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: networking
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/instance: release-name
  internalTrafficPolicy: Cluster
  ports:
    - name: http-metrics
      port: 12345
      targetPort: 12345
      protocol: "TCP"
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
---
# Source: k8s-monitoring/charts/alloy-receiver/templates/controllers/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-alloy-receiver
  labels:
    helm.sh/chart: alloy-receiver-0.10.1
    app.kubernetes.io/name: alloy-receiver
    app.kubernetes.io/instance: release-name
    
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: alloy
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy-receiver
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: alloy
      labels:
        app.kubernetes.io/name: alloy-receiver
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-alloy-receiver
      containers:
        - name: alloy
          image: docker.io/grafana/alloy:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/tmp/alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --server.http.ui-path-prefix=/
            - --stability.level=generally-available
          env:
            - name: ALLOY_DEPLOY_MODE
              value: "helm"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 12345
              name: http-metrics
            - containerPort: 4317
              name: otlp-grpc
              protocol: TCP
            - containerPort: 4318
              name: otlp-http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
        - name: config-reloader
          image: ghcr.io/jimmidyson/configmap-reload:v0.12.0
          args:
            - --volume-dir=/etc/alloy
            - --webhook-url=http://localhost:12345/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
          resources:
            requests:
              cpu: 1m
              memory: 5Mi
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: config
          configMap:
            name: release-name-alloy-receiver
```

</details>

# Versions
## helm
```sh
helm version
version.BuildInfo{Version:"v3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"clean", GoVersion:"go1.22.7"}
```

## repo
```sh
git checkout v2.0.0-rc.10
HEAD is now at 6a381c38 Remove AKS platform test which is not ready yet
```
