### ISSUE TITLE
OTLP destination with OAUTH2 has wrong type for endpoint params

### ISSUE THREAD

**Issue by mentos1386** [grafana/k8s-monitoring-helm#1028]
Using `k8s-monitoring` version `2.0.0-rc.10`.

With config like:
```yaml
cluster:
  name: "hello-world"

clusterMetrics:
  enabled: true

clusterEvents:
  enabled: true

podLogs:
  enabled: true

nodeLogs:
  enabled: true

prometheusOperatorObjects:
  enabled: true

annotationAutodiscovery:
  enabled: true

alloy-logs:
  enabled: true
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true

destinations:
  - name: my-otel-endpoint
    type: otlp
    url: "grpc.my.otel.endpoint:443"
    auth:
      type: oauth2
      oauth2:
        tokenURL: "https://my.idp/application/o/token/"
        clientId: "<redacted>"
        clientSecretFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        endpointParams:
          grant_type: "client_credentials"
          client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
    logs:
      enabled: true
    metrics:
      enabled: true
    traces:
      enabled: false
```

I get failure:
```
Error: /etc/alloy/config.alloy:16:29: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer" should be array, got string

15 |   endpoint_params = {
16 |     client_assertion_type = "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",

   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17 |     grant_type = "client_credentials",
```

This is due to [this code](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl#L49) defining the value as string instead of array.

See [alloy docs mentioning that type should be array](https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.auth.oauth2/#arguments).

I assume this was a breaking change that happened in alloy at some point.

Fix would be to accept array as a helm value:
```yaml
endpointParams:
  grant_type:
    - "client_credentials"
  client_assertion_type:
    - "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
```

And correctly template as array on alloy config itself.
