### ISSUE TITLE
v2: annotation discovery - prom annotation not working

### ISSUE THREAD

**Issue by ceastman-r7** [grafana/k8s-monitoring-helm#1030]
I set the configuration per https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/features/annotation-autodiscovery/prom-annotations

```
annotationAutodiscovery:
  enabled: true

alloy-metrics:
  enabled: true
  annotations:
    scrape: prometheus.io/scrape
    metricsPath: prometheus.io/path
    metricsPortNumber: prometheus.io/port
```

but I am not seeing any prometheus metrics from cert-manager

```
ceastman@AUS-MBP-11488 alloy % kubectl get pods -n cert-manager cert-manager-f7f9b6644-f6n76 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    istio.io/rev: default
    kubectl.kubernetes.io/default-container: cert-manager-controller
    kubectl.kubernetes.io/default-logs-container: cert-manager-controller
    kubectl.kubernetes.io/restartedAt: "2024-04-01T19:08:20Z"
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/status: '{"initContainers":["istio-init","istio-proxy"],"containers":null,"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":null,"revision":"default"}'
```

**Comment by petewall** [comment]
this section:
```yaml
  annotations:
    scrape: prometheus.io/scrape
    metricsPath: prometheus.io/path
    metricsPortNumber: prometheus.io/port
```

should be inside the `annotationAutodiscovery` section, rather than the `alloy-metrics` section. Try that out and let me know.
