### ISSUE TITLE
Support configuring requests&limits within Helm Chart values

### ISSUE THREAD

**Issue by gabriel-yahav** [grafana/k8s-monitoring-helm#1044]
Hi,
Is it possible to add a support in the Helm Chart to set requests&limits to each and every workload that the
Helm chart provisions ?
The workloads provisioned by the chart are running on K8s created by AWS EKS Karpenter, and it's crucial
for us to be able set requests&limits for the pods.

Thanks.

**Comment by petewall** [comment]
Everything underneath of the `alloy-metrics`, `alloy-singleton`, `alloy-logs`, etc... can also utilize the settings from the [Alloy Helm chart](https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy). So, to set requests and limits, you can do that with:

```
alloy-logs:
  alloy:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

Here's a doc for guidelines on setting these values: https://grafana.com/docs/alloy/latest/introduction/estimate-resource-usage/
