### ISSUE TITLE
v2: Missing Option to set ExtraLabels for Profiles Services / Pyroscope

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm#1066]
In v1 you could set the following config;

```
pyroscope:
    host: "https://my-pyroscope-endpoint"
    basicAuth:
      username: user
      password: pass
    externalLabels:
      env: demo
      source: k8s-monitoring-helm
```

But in v2, there is no option to set this currently.

Could we please add an option to specify the extra labels to use for Pyroscope Profiles.
