### ISSUE TITLE
Prometheus rules, alerts, and Grafana dashboards

### ISSUE THREAD

**Issue by P4sca1** [grafana/k8s-monitoring-helm#1073]
https://github.com/kubernetes-monitoring/kubernetes-mixin provides a set of Grafana dashboards and Prometheus alerts for Kubernetes.
It works well in tandem with this helm chart. I successfully deployed dashboards and alerting rules and want to share with the community how it is done.

Maybe instructions can be added to the README or even better maybe this could be added to the helm chart via a feature flag.

### Prerequisites

Install [jsonnet](https://github.com/google/jsonnet) and [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler).

```sh
# On MacOS using brew
brew install jsonnet jsonnet-bundler
```

### Install dependencies
```sh
# This will produce a jsonnetfile.json file in the current working directory
jb init

# This will install the kubernetes-mixin to the ./vendor directory
jb install https://github.com/kubernetes-monitoring/kubernetes-mixin

# make sure to add the vendor directory to your .gitignore file
```

### Add the mixin.libsonnet file

The `mixin.libsonnet` file contains the jsonnet configuration. The selectors need to be updated to use the labels that are configured by this helm chart for Grafana Alloy. The below configuration is compatible with the default values used by this helm chart.

```jsonnet
local kubernetes = import "kubernetes-mixin/mixin.libsonnet";

kubernetes {
  _config+:: {
    cadvisorSelector: 'job="integrations/kubernetes/cadvisor"',
    kubeletSelector: 'job="integrations/kubernetes/kubelet"',
    kubeStateMetricsSelector: 'job="integrations/kubernetes/kube-state-metrics"',
    nodeExporterSelector: 'job="integrations/node_exporter"',
    kubeSchedulerSelector: 'job="kube-scheduler"',
    kubeControllerManagerSelector: 'job="kube-controller-manager"',
    kubeApiserverSelector: 'job="integrations/kubernetes/kube-apiserver"',
    kubeProxySelector: 'job="integrations/kubernetes/kube-proxy"',
    podLabel: 'pod',
    hostNetworkInterfaceSelector: 'device!~"veth.+"',
    hostMountpointSelector: 'mountpoint="/"',
    windowsExporterSelector: 'job="integrations/windows_exporter"',
    containerfsSelector: 'container!=""',

    grafanaK8s+:: {
      dashboardNamePrefix: '',
      dashboardTags: ['kubernetes', 'infrastucture'],
    },
  },
}
```

### Generate alerts, rules, and dashboards

Run the following commands to generate the files.

```sh
mkdir -p files/dashboards
jsonnet -J vendor -S -e 'std.manifestYamlDoc((import "mixin.libsonnet").prometheusAlerts)' > files/alerts.yml
jsonnet -J vendor -S -e 'std.manifestYamlDoc((import "mixin.libsonnet").prometheusRules)' > files/rules.yml
jsonnet -J vendor -m files/dashboards -e '(import "mixin.libsonnet").grafanaDashboards'
```

You then need to apply the generated files to prometheus / grafana. I am personally using the Prometheus and Grafana operator for that purpose.

### Add operator CRDs using helm 

```yaml
# Prometheus rules
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-mixin-rules
spec:
{{- .Files.Get "files/rules.yml" | fromYaml | toYaml | nindent 2 }}

# Prometheus alerts
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-mixin-alerts
spec:
{{- .Files.Get "files/alerts.yml" | fromYaml | toYaml | nindent 2 }}

# Grafana dashboards
{{- range $path, $_ :=  .Files.Glob  "files/dashboards/*.json" -}}
{{- $baseName := $path | base | trimSuffix (ext $path) }}
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: "kubernetes-mixin-{{ $baseName }}-dashboard"
spec:
  instanceSelector:
    matchLabels:
      grafana: main
  json: |-
    {{- $.Files.Get $path | nindent 4 }}
{{- end }}
```

**Comment by dgamo** [comment]
Great job! I have been using that mixin for many years, and it's great to have such an easy way to integrate it with Grafana Cloud

**Comment by wilfriedroset** [comment]
Thank you for that it saved me a headache. For those as lazy as me who don't want to deploy the grafana operator here is what I've done. Deploy your grafana on k8s with the dashboard sidecar, then load the dashboard with the following commands. The first one creates the configmaps the second one adds the labels used by the sidecar to identify which configmaps are dashboard.
```bash
for f in $(ls *json); do kubectl create configmap -n grafana $f --from-file $f; done
for f in $(ls *json); do kubectl patch configmap/$f -n grafana --type merge -p '{"metadata": {"labels": {"grafana_dashboard": "1"}}}'; done
```

For the alerts/rules, I'm not using prometheus I can't define them as `PrometheusRule`. Indeed I rely only on alloy which pushes the metrics to Mimir. Therefore I use [mimirtool](https://grafana.com/docs/mimir/latest/manage/tools/mimirtool) instead. Something similar to this one.
```bash
MIMIR_ADDRESS=http://localhost:8081 MIMIR_TENANT_ID=self-monitoring  mimirtool rules load files/rules.yml
MIMIR_ADDRESS=http://localhost:8081 MIMIR_TENANT_ID=self-monitoring  mimirtool rules load files/alerts.yml
MIMIR_ADDRESS=http://localhost:8081 MIMIR_TENANT_ID=self-monitoring  mimirtool rules list                                                                                       
Namespace | Rule Group
alerts    | kube-apiserver-slos
alerts    | kubernetes-apps
alerts    | kubernetes-resources
alerts    | kubernetes-storage
alerts    | kubernetes-system
alerts    | kubernetes-system-controller-manager
alerts    | kubernetes-system-apiserver
alerts    | kubernetes-system-kube-proxy
alerts    | kubernetes-system-kubelet
alerts    | kubernetes-system-scheduler
rules     | kube-apiserver-availability.rules
rules     | kube-apiserver-burnrate.rules
rules     | kube-apiserver-histogram.rules
rules     | kube-scheduler.rules
rules     | kubelet.rules
rules     | k8s.rules.container_cpu_limits
rules     | k8s.rules.container_cpu_requests
rules     | k8s.rules.container_cpu_usage_seconds_total
rules     | k8s.rules.container_memory_cache
rules     | k8s.rules.container_memory_limits
rules     | k8s.rules.container_memory_swap
rules     | k8s.rules.container_memory_requests
rules     | k8s.rules.container_memory_rss
rules     | k8s.rules.container_memory_working_set_bytes
rules     | k8s.rules.pod_owner
rules     | node.rules
rules     | windows.node.rules
rules     | windows.pod.rules

```

**Comment by cxk314** [comment]
To load PrometheusRule rules into Mimir we used [mimir.rules.kubernetes](https://grafana.com/docs/alloy/latest/reference/components/mimir/mimir.rules.kubernetes/#mimirruleskubernetes) Alloy component. You can use it like this in k8s-monitoring-helm:
```
alloy-singleton:
  enabled: true
  liveDebugging:
    enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
  alloy:
    enableReporting: false
  extraConfig: |-
    mimir.rules.kubernetes "default" {
      address = "http://mimir-ruler.observability.svc:8080"
      tenant_id = "anonymous"
    }
```
The only issue we have right now is configuring Mimir Alert Manager data source in Grafana. When choosing Mimir as alert manager type with url `http://mimir-nginx.observability.svc:80/alertmanager`, we get `It looks like you have chosen a Mimir or Cortex implementation, but detected a Prometheus endpoint. Please update implementation selection and try again.` When changed to Prometheus then connection works but in Alert Rules page we get only rules from mixin `rules.yml`, we don't get rules from `alerts.yml` even though both are loaded.

**Comment by jkleinlercher** [comment]
@P4sca1 great docs! Can you also share your values file for k8s-monitoring helm chart? I guess you needed to at some additional metrics (metricsTuning.includeMetrics) to make this work?

**Comment by Utwo** [comment]
On a similar note #1296

**Comment by unfrgivn** [comment]
@cxk314 This saved me after hours of banging my head on the wall. @Utwo I used your configuration from #1296 which loaded the dashboards into Grafana but I could not get the custom metrics and rules to be picked up from the prometheus CRDs like PrometheusRule. 

Adding this config to my alloy-singleton instance and all the mixin rules and alerts immediately got picked up by Mimir and are showing in Grafana. 

Thank you both!

**Comment by jkleinlercher** [comment]
@Utwo and @P4sca1 thanks again for your hint! I again checked my setting and I saw that all my `KubeAPIErrorBudgetBurn` alerts have "NoData". Are those alerts working in your environment?

I guess the reason is, that all recording rules which are used in `KubeAPIErrorBudgetBurn`  (like `apiserver_request:burnrate1h`, `apiserver_request:burnrate5m`, ..) rely on metrics like `apiserver_request_sli_duration_seconds_count` which are not gathered outofthebox in k8smonitoring. Also in https://github.com/grafana/k8s-monitoring-helm/issues/1296 I don't find them. Or did I miss something?

**Comment by P4sca1** [comment]
Hey @jkleinlercher, the `KubeAPIErrorBudgetBurn` alert works in my environment. The `apiserver_request_sli_duration_seconds_count` metric is available. Make sure you enable the `clusterMetrics` feature. My values (adjust to your needs):

```yaml
clusterMetrics:
  enabled: true
  kubelet:
    enabled: true
  kubeletResource:
    enabled: true
  cadvisor:
    enabled: true
  apiServer:
    enabled: true
  kubeDNS:
    enabled: true
  # kube-controller-manager and kube-scheduler only listen on localhost for security reasons.
  # Reading metrics does not work by default and would require a proxy.
  # https://github.com/prometheus-operator/kube-prometheus/issues/913#issuecomment-1065494045
  kubeControllerManager:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    # kube-proxy is not used. Cilium CNI provides an alternative implementation.
    enabled: false
  kube-state-metrics:
    enabled: true
    metricsTuning:
      includeMetrics:
        - kube_deployment_created
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 64Mi
  node-exporter:
    enabled: true
    deploy: true
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 32Mi
  windows-exporter:
    enabled: false
    deploy: false
  kepler:
    enabled: false
  opencost:
    enabled: false
```

Documentation is available here: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-cluster-metrics

**Comment by jkleinlercher** [comment]
@P4sca1 aaaah you are totally right, I always set an includeMetrics list in https://github.com/suxess-it/kubriX/blob/95a528bc7909d5d831c360e121af212ab788f275/platform-apps/charts/k8s-monitoring/values-demo-metalstack.yaml#L34-L45 

```
    apiServer:
      enabled: true
      metricsTuning:
        includeMetrics:
          - apiserver_requested_deprecated_apis
          - apiserver_request_total
          - apiserver_request_duration_seconds_sum
          - apiserver_request_duration_seconds_count
          - workqueue_depth
          - process_cpu_seconds_total
          - process_resident_memory_bytes
          - apiserver_requested_deprecated_apis
```

because I thought this list is in addition to a default allow list as with other features. Now I realized that for apiserver it is different. As soon as you set an includeMetrics list, only those metrics are retrieved ... as soon as I deleted the includeMetrics list also `apiserver_request_sli_duration_seconds_count` was available. thank you so much!

**Comment by Utwo** [comment]
> [@cxk314](https://github.com/cxk314) This saved me after hours of banging my head on the wall. [@Utwo](https://github.com/Utwo) I used your configuration from [#1296](https://github.com/grafana/k8s-monitoring-helm/issues/1296) which loaded the dashboards into Grafana but I could not get the custom metrics and rules to be picked up from the prometheus CRDs like PrometheusRule.
> 
> Adding this config to my alloy-singleton instance and all the mixin rules and alerts immediately got picked up by Mimir and are showing in Grafana.
> 
> Thank you both!

You will need to enable prometheusCRDs in the k8s-monitoring helm chart like this:
```
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
```
