### ISSUE TITLE
v2: Alloy Singleton is Unable to Start if Prometheus Metrics is used

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm#1075]
The `alloy-singleton` Container fails to start and CrashLoops if a Prometheus Metrics Destination is used for the `clusterEvents` feature, instead of an OTLP one (in addition to a Logs one).

Example Config;

```yaml

cluster:
  name: ${cluster}

# Values: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/destinations
## External Auth Examples: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/auth/external-secrets
destinations:
  - name: metricsService
    type: prometheus
    url: ${grafana_cloud_metrics_url}/api/prom/push
    extraLabels:
      env: ${env}
      source: ${source}
    auth:
      type: basic
      username: user
      password: pass
    sendNativeHistograms: true
  - name: logsService
    type: loki
    url: ${grafana_cloud_logs_url}/loki/api/v1/push
    extraLabels:
      env: ${env}
      source: ${source}
    auth:
      type: basic
      username: user
      password: pass
  - name: otlpService
    protocol: http
    type: otlp
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
    url: ${grafana_cloud_otlp_url}/otlp
    auth:
      type: basic
      usernameKey: otlp_username
      passwordKey: otlp_password
    secret:
      create: false
      name: ${secret_name}
      namespace: ${secret_namespace}

# Values: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-cluster-events/values.yaml
clusterEvents:
  enabled: true
  destinations: ["logsService", "metricsService"]
```

Can see the following in the Logs;

```
2025-01-08 17:33:29.956 GMT
Error: could not perform the initial load successfully
2025-01-08 17:33:30.677 GMT
Error: /etc/alloy/config.alloy:209:5: component "otelcol.receiver.prometheus.otlpservice.receiver" does not exist or is out of scope
2025-01-08 17:33:30.677 GMT
208 | forward_to = [
2025-01-08 17:33:30.677 GMT
209 | otelcol.receiver.prometheus.otlpservice.receiver,
2025-01-08 17:33:30.677 GMT
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-08 17:33:30.677 GMT
210 | ]
2025-01-08 17:33:30.677 GMT
{}
2025-01-08 17:33:30.677 GMT
Error: could not perform the initial load successfully
2025-01-08 17:33:53.050 GMT
Error: /etc/alloy/config.alloy:209:5: component "otelcol.receiver.prometheus.otlpservice.receiver" does not exist or is out of scope
```

Looking at the Rendered Config Map, the error is correct in that no receiver with that name exists;

```
/ Destination: metricsService (prometheus)
otelcol.exporter.prometheus "metricsservice" {
  add_metric_suffixes = true
  forward_to = [prometheus.remote_write.metricsservice.receiver]
}

prometheus.remote_write "metricsservice" {
  endpoint {
    url = "https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push"
    headers = {
    }
    basic_auth {
      username = nonsensitive(remote.kubernetes.secret.metricsservice.data["username"])
      password = remote.kubernetes.secret.metricsservice.data["password"]
    }
    tls_config {
      insecure_skip_verify = false
    }
    send_native_histograms = true

    queue_config {
      capacity = 10000
      min_shards = 1
      max_shards = 50
      max_samples_per_send = 2000
      batch_send_deadline = "5s"
      min_backoff = "30ms"
      max_backoff = "5s"
      retry_on_http_429 = true
      sample_age_limit = "0s"
    }

    write_relabel_config {
      source_labels = ["cluster"]
      regex = ""
      replacement = "seamus-tf-test-8cg7r-gcp"
      target_label = "cluster"
    }
    write_relabel_config {
      source_labels = ["k8s.cluster.name"]
      regex = ""
      replacement = "seamus-tf-test-8cg7r-gcp"
      target_label = "cluster"
    }
  }

  wal {
    truncate_frequency = "2h"
    min_keepalive_time = "5m"
    max_keepalive_time = "8h"
  }
  external_labels = {
    env = "testing",
    source = "grafana-k8s-monitoring-alloy",
  }
}

remote.kubernetes.secret "metricsservice" {
  name      = "metricsservice-grafana-k8s-monitoring"
  namespace = "grafana-k8s-monitoring"
}

// Destination: logsService (loki)
otelcol.exporter.loki "logsservice" {
  forward_to = [loki.write.logsservice.receiver]
}

loki.write "logsservice" {
  endpoint {
    url = "https://logs-prod-008.grafana.net/loki/api/v1/push"
    basic_auth {
      username = nonsensitive(remote.kubernetes.secret.logsservice.data["username"])
      password = remote.kubernetes.secret.logsservice.data["password"]
    }
    tls_config {
      insecure_skip_verify = false
    }
  }
  external_labels = {
    cluster = "seamus-tf-test-8cg7r-gcp",
    "k8s_cluster_name" = "seamus-tf-test-8cg7r-gcp",
    env = "testing",
    source = "grafana-k8s-monitoring-alloy",
  }
}

remote.kubernetes.secret "logsservice" {
  name      = "logsservice-grafana-k8s-monitoring"
  namespace = "grafana-k8s-monitoring"
}

// Feature: Cluster Events
declare "cluster_events" {
  argument "logs_destinations" {
    comment = "Must be a list of log destinations where collected logs should be forwarded to"
  }

  loki.source.kubernetes_events "cluster_events" {
    job_name   = "integrations/kubernetes/eventhandler"
    log_format = "logfmt"
    forward_to = [loki.process.cluster_events.receiver]
  }

  loki.process "cluster_events" {

    // add a static source label to the logs so they can be differentiated / restricted if necessary
    stage.static_labels {
      values = {
        "source" = "kubernetes-events",
      }
    }

    // extract some of the fields from the log line, these could be used as labels, structured metadata, etc.
    stage.logfmt {
      mapping = {
        "component" = "sourcecomponent", // map the sourcecomponent field to component
        "kind" = "",
        "level" = "type", // most events don't have a level but they do have a "type" i.e. Normal, Warning, Error, etc.
        "name" = "",
        "node" = "sourcehost", // map the sourcehost field to node
      }
    }
    // set these values as labels, they may or may not be used as index labels in Loki as they can be dropped
    // prior to being written to Loki, but this makes them available
    stage.labels {
      values = {
        "component" = "",
        "kind" = "",
        "level" = "",
        "name" = "",
        "node" = "",
      }
    }

    // if kind=Node, set the node label by copying the instance label
    stage.match {
      selector = "{kind=\"Node\"}"

      stage.labels {
        values = {
          "node" = "name",
        }
      }
    }

    // set the level extracted key value as a normalized log level
    stage.match {
      selector = "{level=\"Normal\"}"

      stage.static_labels {
        values = {
          level = "Info",
        }
      }
    }

    // Only keep the labels that are defined in the `keepLabels` list.
    stage.label_keep {
      values = ["job","level","namespace","node","source"]
    }
    forward_to = argument.logs_destinations.value
  }
}
cluster_events "feature" {
  logs_destinations = [
    loki.write.logsservice.receiver,
  ]
}

// Self Reporting
prometheus.exporter.unix "kubernetes_monitoring_telemetry" {
  set_collectors = ["textfile"]
  textfile {
    directory = "/etc/alloy"
  }
}

discovery.relabel "kubernetes_monitoring_telemetry" {
  targets = prometheus.exporter.unix.kubernetes_monitoring_telemetry.targets
  rule {
    target_label = "instance"
    action = "replace"
    replacement = "grafana-k8s-monitoring"
  }
  rule {
    target_label = "job"
    action = "replace"
    replacement = "integrations/kubernetes/kubernetes_monitoring_telemetry"
  }
}

prometheus.scrape "kubernetes_monitoring_telemetry" {
  job_name   = "integrations/kubernetes/kubernetes_monitoring_telemetry"
  targets    = discovery.relabel.kubernetes_monitoring_telemetry.output
  scrape_interval = "1h"
  clustering {
    enabled = true
  }
  forward_to = [prometheus.relabel.kubernetes_monitoring_telemetry.receiver]
}

prometheus.relabel "kubernetes_monitoring_telemetry" {
  rule {
    source_labels = ["__name__"]
    regex = "grafana_kubernetes_monitoring_.*"
    action = "keep"
  }
  forward_to = [
    otelcol.receiver.prometheus.otlpservice.receiver,
  ]
}
```

Switching to use an OTLP Destination works.

Side note, I did not even know it needed a Metrics Destination here, and initially my destinations restricted only to a Loki one.
