### ISSUE TITLE
v2: Integrations - Alloy - Go Metrics are being droped by default

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm#1084]
In v2, with the Alloy Integration Enabled, and the following Configuration;

```yaml
# Values: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-integrations/values.yaml
integrations:
  destinations: ["metricsService", "logsService"]
  alloy:
    instances:
      - name: "alloy"
        # Values: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-integrations/integrations/alloy-values.yaml
        labelSelectors:
          app.kubernetes.io/name: ["alloy-logs", "alloy-metrics", "alloy-profiles", "alloy-receiver", "alloy-singleton"]
        metrics:
          tuning:
            useDefaultAllowList: false
            includeMetrics: [".*"]
```

The `go_` Metrics are still being dropped, looking at the ConfigMap, I see the following block;

```
// alloy metric relabelings (post-scrape)
    prometheus.relabel "alloy" {
      forward_to = argument.forward_to.value
      max_cache_size = coalesce(argument.max_cache_size.value, 100000)

      // drop metrics that match the drop_metrics regex
      rule {
        source_labels = ["__name__"]
        regex = coalesce(argument.drop_metrics.value, "(^(go|process)_.+$)")
        action = "drop"
      }
```

This causes part of the Alloy Health Integration not to show Data;

![Image](https://github.com/user-attachments/assets/b8328340-4de1-48b8-ae71-e8ecd0ad5363)

In v1, this config, allowed the `go_` metrics to be sent still and so they showed in this Dashboard.
