### ISSUE TITLE
v2: Auto Instrumentation - Unable to provide custom Config to Beyla

### ISSUE THREAD

**Issue by SeamusGrafana** [grafana/k8s-monitoring-helm#1085]
This may well be something I a missing or not setting correctly as opposed to a bug, however in `v1` you could provide custom Config to Beyla, like so;

```yaml
beyla:
  config:
    data:
      attributes:
        kubernetes:
          enable: true
        select:
          beyla_network_flow_bytes:
            include:
              - direction
              - k8s.cluster.name
              - k8s.dst.name
              - k8s.dst.namespace
              - k8s.dst.owner.name
              - k8s.dst.owner.type
              - k8s.src.name
              - k8s.src.namespace
              - k8s.src.owner.name
              - k8s.src.owner.type
      discovery:
        exclude_otel_instrumented_services: false
        services:
          - k8s_pod_labels:
              instrument: beyla
      log_level: debug
      network:
        enable: true
      prometheus_export:
        port: 9090
        path: /metrics
        features:
          - application
          - application_process
          - application_service_graph
          - application_span
          - network
      internal_metrics:
        prometheus:
          port: 9090
          path: /internal/metrics
          routes:
      patterns:
        - /account
        - /api/products/{productId}
        - /cart
        - /fastcache
        - /health
        - /login
        - /payment
      ignored_patterns:
        - /debug/*
        - /metrics
      unmatched: heuristic
  enabled: true
  podAnnotations:
    k8s.grafana.com/job: default/beyla
    k8s.grafana.com/logs.job: default/beyla
  preset: application
```

However, trying to set that in `v2`, and the Config is not applied to Beyla,

```yaml
# Values: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-auto-instrumentation/values.yaml
autoInstrumentation:
  enabled: true
  destinations: ["otlpService"]
  beyla:
    config:
      data:
        attributes:
          kubernetes:
            enable: true
          select:
            beyla_network_flow_bytes:
              include:
                - direction
....
```

The ConfigMap for Beyla, shows what appears to be the default Configuration;

```
attributes:
  kubernetes:
    enable: true
    cluster_name: seamus-tf-test-8cg7r-gcp
  select:
    beyla_network_flow_bytes:
      include:
        - 'k8s.src.owner.type'
        - 'k8s.dst.owner.type'
        - 'direction'
filter:
  network:
    k8s_dst_owner_name:
      not_match: '{kube*,*jaeger-agent*,*prometheus*,*promtail*,*grafana-agent*}'
    k8s_src_owner_name:
      not_match: '{kube*,*jaeger-agent*,*prometheus*,*promtail*,*grafana-agent*}'
internal_metrics:
  prometheus:
    port: 9090
    path: /internal/metrics
prometheus_export:
  port: 9090
  path: /metrics
  features:
    - application
    - network
    - application_service_graph
    - application_span
otel_traces_export:
  endpoint: http://grafana-k8s-monitoring-alloy-receiver.grafana-k8s-monitoring.svc.cluster.local:4317
```
