### ISSUE TITLE
v2: node-exporter on multi node cluster always reporting the same node in instance label

### ISSUE THREAD

**Issue by sbidoul** [grafana/k8s-monitoring-helm#1099]
Hello,

I'm trying to use v2 to migrate from a grafana-agent-operator deployment. This sounds very easy and intuitive so far, thanks for this work!

I'm having a little issue with node exporter metrics which only have a single node in the `instance` label.
Apparently, it is always the node where the `grafana-k8s-monitoring-alloy-metrics-0` pod is running.

I'm using a basic values.yaml like this. Am I missing something obvious?

```
cluster:
  name: ...

destinations:
  ...

clusterMetrics:
  enabled: true
  node-exporter:
    metricsTuning:
      useDefaultAllowList: true
      includeMetrics:
        - node_load1
        - node_load5
        - node_load15
        - node_time_seconds
        - node_boot_time_seconds

prometheusOperatorObjects:
  enabled: true

clusterEvents:
  enabled: true

podLogs:
  enabled: true

alloy-logs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

kube-state-metrics:
  enabled: true
```
