### ISSUE TITLE
v2: Unable to patch destinations (set labels) via Helm values

### ISSUE THREAD

**Issue by benwh** [grafana/k8s-monitoring-helm#1116]
I've been trying to migrate our internal deployment to v2.0.1, and have run into a small issue:

## Context

In our existing configuration, when we generate our manifests, we have a base Helm `values.yaml` file, and then layer on top some additional config for each individual instance that we deploy.

We want to set some custom labels, for all of the metrics and logs which are produced by `k8s-monitoring`, separately for each instance.

That leads to us running (simplified, but demonstrates the concept):

```
helm template grafana/k8s-monitoring --version 1.6.18 --values values.yaml --set cluster.name="foo" --set externalServices.loki.externalLabels.project="bar"
```

However, if we try to follow the [migration advice](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/Migration.md#destinations), then we get a bit stuck...

## Issue

Because the chart defines `destinations` as an array rather than a dict, we aren't able to override specific fields. i.e. There's no way to supply a patch of `destinations[0].extraLabels.project="bar"`, or `destinations[type="prometheus"].extraLabels.project="bar"`, with Helm.

This is a reasonably well-documented shortcoming of Helm values: https://github.com/helm/helm/issues/3486. The general solution appears to be to always define chart values as dicts, rather than arrays, which this chart mostly does with the exception of this new `destinations` field.

## Workarounds?

I'd either have to create a separate values.yaml file for each instance, which re-defined the _entire_ destinations block, or use `--set-json` and construct quite a large argument, which again would need to redefine the entire block. That doesn't feel great.

I also looked at specify `kube-state-metrics.extraMetricProcessingRules`, to add labels post-scrape, but that would also require me to specify an entire string block for each instance, rather than just being able to stack values files and add a single label value.

**Comment by petewall** [comment]
What version of Helm are you using? In mine, I am able to set elements within the destinations array:

## Test 1 (all in values.yaml)
```yaml
cluster: {name: set-test}
clusterEvents: {enabled: true}
alloy-singleton: {enabled: true}

destinations:
  - name: loki
    type: loki 
    url: http://loki-host.example.com:3100/loki/api/v1/push
```
```bash
% helm template test grafana/k8s-monitoring -f values.yaml | grep loki-host
        url = "http://loki-host.example.com:3100/loki/api/v1/push"
%
```

## Test 2 (url missing)
```yaml
cluster: {name: set-test}
clusterEvents: {enabled: true}
alloy-singleton: {enabled: true}

destinations:
  - name: loki
    type: loki 
```
```bash
% helm template test grafana/k8s-monitoring -f values.yaml | grep loki-host
        url = "http://loki-host.example.com:3100/loki/api/v1/push"
%
```

Obviously, I expect this to be missing. Perhaps there needs to be validation for this...

## Test 3 (Using --set)
```yaml
cluster: {name: set-test}
clusterEvents: {enabled: true}
alloy-singleton: {enabled: true}

destinations:
  - name: loki
    type: loki 
```
```bash
% helm template test grafana/k8s-monitoring -f values.yaml --set "destinations[0].url=http://loki-host.example.com:3100/loki/api/v1/push" | grep loki-host
        url = "http://loki-host.example.com:3100/loki/api/v1/push"
%
```

So, using `--set "destinations[0].url=..."` allowed me to set a single element within the destination array when it wasn't set in the original values.yaml.
