### ISSUE TITLE
v2: Make it easy to set static labels

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1121]
I'd love to be able to do this:

```yaml
podLogs:
  staticLabels:
    region: central
```

without needing to do this:
```yaml
podLogs:
  extraLogProcessingStages: |
    stage.static_labels {
      values = {
        region = "central",
      }
    }
```
