### ISSUE TITLE
v2 docs: Make an example of setting kube-state-metrics's labels and annotations

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1128]
We need a v2 version of this:
https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring-v1/docs/examples/pod-labels

**Comment by petewall** [comment]
In v2, you should do:
```
clusterMetrics:
  kube-state-metrics:
    nodeSelector:
      node-role.kubernetes.io/tools: tools
```

Your option should work for v1.
