### ISSUE TITLE
v2, k3s: kubeControllerManager, kubeScheduler & kubeProxy metrics

### ISSUE THREAD

**Issue by pschiffe** [grafana/k8s-monitoring-helm#1145]
Hello, was anyone able to collect metrics of kubeControllerManager, kubeScheduler & kubeProxy on k3s? I don't think there are pods in the `kube-system` with `component=kube-controller-manager`, etc.

Based on this [thread](https://github.com/k3s-io/k3s/issues/3619), k3s exposes metrics for kubeControllerManager, kubeScheduler & kubeProxy only on the host, as far as I understand. When looking at the [rancher-monitoring](https://github.com/rancher/charts/blob/main/charts/rancher-monitoring/values.yaml#L93) chart, it seem like they are using [rancher-pushprox](https://github.com/rancher/charts/tree/dev-v2.10/charts/rancher-pushprox/103.0.1) for accessing metrics from the host.

Is this something this helm chart would support as well? Do you have some tips how to best implement this in the current version of v2?

Thanks.

**Comment by evilhamsterman** [comment]
It's possible to get the metrics exposed and use something like kube-prometheus-stack but it's a pain in the butt. I would be amazing if the LGTM stack could integrate nicely with k3s in this chart

**Comment by pschiffe** [comment]
I was able to make it work in an OK setup I think. If you want to collect also etcd metrics, enable them in k3s service with `--etcd-expose-metrics`. Then deploy `rancher-pushprox`. You need one for k3s and one for etcd. I have flux, so my config looks like one below.

It will deploy also `serviceMonitor`s and starts to work. Then you need to check for doubled metrics, some metrics is this helm chart able to collect as well. Basically you need to just disable `kubelet` metrics and don't enable metrics for scheduler, controller manager and proxy.

```yaml
clusterMetrics:
  enabled: true
  kubelet:
    enabled: false
```

```yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flux-rancher
spec:
  interval: 24h
  url: https://charts.rancher.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-rancher-pushprox-k3s
spec:
  interval: 12h
  timeout: 15m
  serviceAccountName: flux-k8s-monitoring
  chart:
    spec:
      chart: rancher-pushprox
      version: "103.x"
      sourceRef:
        kind: HelmRepository
        name: flux-rancher
  values:
    enabled: true
    metricsPort: 10250
    component: k3s-server
    global:
      rbac:
        create: true
        userRoles:
          create: true
          aggregateToDefaultRoles: true
    clients:
      port: 10013
      metrics:
        enabled: true
      useLocalhost: true
      https:
        enabled: true
        useServiceAccountCredentials: true
        insecureSkipVerify: true
      image:
        repository: rancher/pushprox-client
        tag: v0.1.4-rancher2-client
      command:
        - "pushprox-client"
        - "--log.level=warn"
        - "--log.format=json"
      copyCertsImage:
        repository: rancher/mirrored-library-busybox
        tag: "1.37.0"
      rbac:
        additionalRules:
          - nonResourceURLs: ["/metrics/cadvisor"]
            verbs: ["get"]
          - apiGroups: [""]
            resources: ["nodes/metrics"]
            verbs: ["get"]
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
    proxy:
      image:
        repository: rancher/pushprox-proxy
        tag: v0.1.4-rancher2-proxy
      command:
        - "pushprox-proxy"
        - "--log.level=warn"
        - "--log.format=json"
    serviceMonitor:
      endpoints:
        - port: metrics
          honorLabels: true
          relabelings:
            - targetLabel: source
              replacement: kubernetes

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-rancher-pushprox-etcd
spec:
  interval: 12h
  timeout: 15m
  serviceAccountName: flux-k8s-monitoring
  chart:
    spec:
      chart: rancher-pushprox
      version: "103.x"
      sourceRef:
        kind: HelmRepository
        name: flux-rancher
  values:
    enabled: true
    metricsPort: 2381
    component: kube-etcd
    clients:
      port: 10014
      metrics:
        enabled: true
      useLocalhost: true
      nodeSelector:
        node-role.kubernetes.io/etcd: "true"
      tolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      image:
        repository: rancher/pushprox-client
        tag: v0.1.4-rancher2-client
      command:
        - "pushprox-client"
        - "--log.level=warn"
        - "--log.format=json"
      copyCertsImage:
        repository: rancher/mirrored-library-busybox
        tag: "1.37.0"
    proxy:
      image:
        repository: rancher/pushprox-proxy
        tag: v0.1.4-rancher2-proxy
      command:
        - "pushprox-proxy"
        - "--log.level=warn"
        - "--log.format=json"
    serviceMonitor:
      endpoints:
        - port: metrics
          honorLabels: true
          relabelings:
            - targetLabel: source
              replacement: kubernetes
```
