### ISSUE TITLE
Set useDefaultAllowList: false not working in feature-integrations chart

### ISSUE THREAD

**Issue by fplantinga-guida** [grafana/k8s-monitoring-helm#1148]
The value of keep_metrics in the alloy_integration_scrape still contains the default allow_list if I specify useDefaultAllowList: false. Reproduce with the following values:
```
alloy:
  instances:
    - name: alloy-logs
      labelSelectors:
        app.kubernetes.io/name: alloy-logs
      metrics:
        tuning:
          useDefaultAllowList: false
          includeMetrics: ['example_metric']
```

If you modify the alloyList variable to include the .instance.metrics.tuning.useDefaultAllowList you can see it remains true. 
```
{{- if .instance.metrics.tuning.useDefaultAllowList -}}
{{- $allowList = concat (list .instance.metrics.tuning.useDefaultAllowList) $allowList (list "up" "scrape_samples_scraped") (.Files.Get "default-allow-lists/alloy.yaml" | fromYamlArray) -}}
{{- end -}}
```

Output:
```
      alloy_integration_scrape  "alloy_logs" {
        targets = alloy_integration_discovery.alloy_logs.output
        job_label = "integrations/alloy"
        clustering = true
        keep_metrics = "true|up|scrape_samples_scraped|<default_allow_list_alloy>|example_metric"
        scrape_interval = "60s"
        max_cache_size = 100000
        forward_to = argument.metrics_destinations.value
      }
```

My guess is that something goes wrong at {{- with $defaultValues | merge (deepCopy .instance) }}
