### ISSUE TITLE
v2: Add the ability to enable the faro receiver as part of application observability

### ISSUE THREAD

**Issue by ceastman-r7** [grafana/k8s-monitoring-helm#1179]
Something like:

    applicationObservability = {
      enabled = true,
      receivers = {
        faro = { enabled = true }
        }
      }

**Comment by rlankfo** [comment]
hey @ceastman-r7 👋 

The existing `faro.receiver` component in Alloy is incompatible with the Grafana Cloud Frontend Observability solution so we are unlikely to add it here. 

The good news is that we're actively developing OpenTelemetry compatible Faro components that will be compatible with our cloud offerings as well as any OTLP destination. Once these components are available in Alloy, I anticipate we'll make the Faro receiver available in the helm chart.

You can follow along with our progress on these components here:
- https://github.com/grafana/faro/pull/29
- https://github.com/grafana/faro/pull/29

cc @t00mas 

Thanks!

**Comment by cxk314** [comment]
Hi @rlankfo,
Is there any update on OTEL Faro receiver support in k8s-monitoring? We are also interested in using Faro. Right now, `faro.receiver` from Alloy has issues with correctly sending labels on logs. It is just one string and makes Faro logs useless when ingesting to Loki. The new OTEL Faro receiver should address that? We will be getting correctly labeled logs that can be then searched in Loki?

**Comment by rlankfo** [comment]
> Hi [@rlankfo](https://github.com/rlankfo), Is there any update on OTEL Faro receiver support in k8s-monitoring? We are also interested in using Faro. Right now, `faro.receiver` from Alloy has issues with correctly sending labels on logs. It is just one string and makes Faro logs useless when ingesting to Loki. The new OTEL Faro receiver should address that? We will be getting correctly labeled logs that can be then searched in Loki?

These components are currently being added upstream to opentelemetry collector contrib and then we'll release them in Alloy. 
You can track the issues here:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35319
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19180

>  It is just one string and makes Faro logs useless when ingesting to Loki. 

This doesn't sound correct to me, I believe faro logs should have proper labels in loki when using the existing `faro.receiver` component. Can you provide your alloy config?

**Comment by cxk314** [comment]
Thank you @rlankfo for the reply.

>These components are currently being added upstream to opentelemetry collector contrib and then we'll release them in Alloy.
You can track the issues here:

Do you have ETA when they will be available in Alloy? Is it possible to use them by building ourselves into Docker and deploying on K8S?

> This doesn't sound correct to me, I believe faro logs should have proper labels in loki when using the existing `faro.receiver` component. Can you provide your alloy config?

We are running self-hosted Grafana, Loki, Mimir, Tempo and k8s-monitoring on AKS cluster. We are getting logs and traces from Faro but for logs, it is just one string without labels. I found this is also happening for others and reported [here](https://github.com/grafana/faro-web-sdk/discussions/460#discussioncomment-8743215). The labels are also not coming into Loki index labels, which is because of that. We added additional labels to Loki index label configuration. Here is how the Faro log looks like:

![Image](https://github.com/user-attachments/assets/7839edfd-3b1c-4ca5-b2f9-be82a6d18c88)

Here is our configuration:
```
cluster:
  name: np-cluster

destinations:
  - name: prometheus
    type: prometheus
    url: http://mimir-nginx.observability.svc:80/api/v1/push
    tls:
      insecure: true
      insecureSkipVerify: true
  - name: prometheus_otlp
    type: otlp
    protocol: http
    url: http://mimir-nginx.observability.svc:80/otlp
    tls:
      insecure: true
      insecureSkipVerify: true
    metrics:
      # -- Whether to send metrics to the OTLP destination.
      # @section -- Telemetry
      enabled: true
    logs:
      enabled: false
    traces:
      enabled: false
  - name: loki
    type: loki
    url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
    tls:
      insecure: true
      insecureSkipVerify: true
  - name: loki_otlp
    type: otlp
    protocol: http
    url: http://loki-gateway.observability.svc.cluster.local/otlp
    tls:
      insecure: true
      insecureSkipVerify: true
    logs:
      enabled: true
    metrics:
      enabled: false
    traces:
      enabled: false
  - name: tempo
    type: otlp
    url: http://tempo-distributor.observability.svc.cluster.local:4317
    tls:
      insecure: true
      insecureSkipVerify: true
    logs:
      enabled: false
    metrics:
      enabled: false
    traces:
      enabled: true

clusterMetrics:
  enabled: true
  apiServer:
    enabled: true
  cadvisor:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: ["(.+)"]
  kubeControllerManager:
    enabled: true
    deploy: true
  kube-state-metrics:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: ["(.+)"]
    metricLabelsAllowlist:
      - pods=[*]
      - namespaces=[*]
  kubelet:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: ["(.+)"]
  kubeProxy:
    enabled: true
    selectorLabel: "component=kube-proxy"
  kubeletResource:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics: ["(.+)"]
  node-exporter:
    metricsTuning:
      useIntegrationAllowList: false
      includeMetrics: ["(.+)"]

clusterEvents:
  enabled: true
  destinations: [loki]

podLogs:
  enabled: true
  volumeGatherSettings:
    onlyGatherNewLogLines: true
  destinations: [loki]

nodeLogs:
  enabled: true
  journal:
    maxAge: "2h"
  destinations: [loki]

windows-exporter:
  enabled: false
  deploy: false

# selfReporting:
#   enabled: false

# -- Application Observability.
applicationObservability:
  enabled: true
  logs.enabled: true
  metrics.enabled: true
  traces:
    enabled: true
    filters:
      span: 
        - attributes["http.route"] == "/ready"
        - attributes["http.route"] == "/live"
        - attributes["http.target"] == "/ready"
        - attributes["http.target"] == "/live"
        - attributes["http.target"] == "/healthz"
  receivers:
    http:
      enabled: true
      port: 4318
    otlp:
      grpc:
        enabled: true
        port: 4317

alloy-metrics:
  enabled: true
  alloy:
    enableReporting: false

alloy-singleton:
  enabled: true
  liveDebugging:
    enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
  alloy:
    enableReporting: false
  extraConfig: |-
    mimir.rules.kubernetes "default" {
      address = "http://mimir-ruler.observability.svc:8080"
      tenant_id = "anonymous"
    }
    remote.kubernetes.secret "k8s_monitoring_secrets" {
      namespace = "observability"
      name = "k8s-monitoring-secrets"
    }

alloy-logs:
  enabled: true
  liveDebugging:
    enabled: true
  alloy:
    enableReporting: false
    stabilityLevel: experimental
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}

# An Alloy instance for opening receivers to collect application data.
alloy-receiver:
  enabled: true
  liveDebugging:
    enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
  extraConfig: |-
      faro.receiver "integrations_app_agent_receiver" {
        server {
          listen_address           = "0.0.0.0"
          listen_port              = 8027
          cors_allowed_origins     = ["*"]
          max_allowed_payload_size = "10MiB"

          rate_limiting {
            rate = 100
          }
        }
        sourcemaps {
          download = false
        }
        output {
          logs   = [otelcol.receiver.loki.loki_otlp.receiver]
          traces = [otelcol.processor.attributes.tempo.input]
        }
      }
  alloy:
    enableReporting: false
    stabilityLevel: experimental
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: faro
        port: 8027
        targetPort: 8027
        protocol: TCP
# -- Deploy additional manifest objects
extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: alloy-receiver-ingress
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: vault-issuer
        cert-manager.io/common-name: alloy-receiver.np-aks.com
    spec:
      rules:
        - host: alloy-receiver.np-mosaic-aks.shwaks.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: "{{.Release.Namespace}}-alloy-receiver" # this is the name of the kubernetes endpoint for the receiver. need to make this dynamic
                    port:
                      number: 8027
      tls:
        - hosts:
            - alloy-receiver.np-aks.com
          secretName: alloy-receiver-secret
```

**Comment by rlankfo** [comment]
Thanks for the update, I see what you were saying.  Looks like the recommendation here is to use loki's logfmt function as indicated in the comment you linked.

As far as ETA, I don't have an exact timeline.

**Comment by cxk314** [comment]
We solved our issue with Faro. Putting it here so it will be useful for someone. We basically wanted for Faro to work with standardized Faro dashboard from [here](https://grafana.com/grafana/dashboards/17766-frontend-monitoring/). The key was to send Faro metrics to Loki regular endpoint (not the OTEL one) and add two more labels(Application, Environment). Here is the configuration:
```
alloy-receiver:
  enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
  extraConfig: |-
    loki.process "logs_process_client" {
        forward_to = [loki.write.logs_write_client.receiver]

        stage.logfmt {
            mapping = { "kind" = "", "service_name" = "", "app" = "",app_name="",app_environment="", }
        }

        stage.labels {
            values = { "kind" = "kind", "service_name" = "service_name", "app" = "app", "app_name"="app_name", "app_environment"="app_environment",Application="app_name",Environment="app_environment", }
        }
      }
      logging {
        level  = "debug"
        format = "logfmt"
      }
      loki.write "logs_write_client" {
        endpoint {
          url = "http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push"
          tls_config {
            insecure_skip_verify = true
          }
        }
      }
      faro.receiver "integrations_app_agent_receiver" {
        log_format = "logfmt"
        server {
          listen_address           = "0.0.0.0"
          listen_port              = 8027
          cors_allowed_origins     = ["*"]
          max_allowed_payload_size = "10MiB"

          rate_limiting {
            rate = 100
          }
        }
        sourcemaps {
          download = false
        }
        output {
          logs   = [loki.process.logs_process_client.receiver]
          traces = [otelcol.processor.attributes.tempo.input]
        }
      }
  alloy:
    enableReporting: false
    stabilityLevel: experimental
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: faro
        port: 8027
        targetPort: 8027
        protocol: TCP
```

**Comment by carlosjgp** [comment]
How do people add "destinations" to `alloy-receiver`?
eg:
```
destinations:
  - name: grafana-cloud-logs
    type: loki
    url: "https://<GRAFANA CLOUD>/loki/api/v1/push"
    ...
```

```
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
      - name: "faro"
        port: 12347
        targetPort: 12347
        protocol: "TCP"
        appProtocol: "h2c"
    stabilityLevel: experimental

  logging:
    level: "debug"
    format: "json"
  liveDebugging:
    # -- Enable live debugging for the Alloy instance.
    # Requires stability level to be set to "experimental".
    # @section -- General
    enabled: true
  extraConfig: |-
    faro.receiver "integrations_app_agent_receiver" {
      log_format = "logfmt"


      server {
        listen_address           = "0.0.0.0"
        listen_port              = 12347
        cors_allowed_origins     = ["*"]
        max_allowed_payload_size = "10MiB"

        rate_limiting {
          rate = 100
        }
      }
      sourcemaps {
        download = false
      }

      extra_log_labels = {
        rum = "faro-sdk"
      }

      output {
        // traces = [otelcol.processor.attributes.grafana_cloud_otlp_endpoint.input]
        logs = [otelcol.receiver.loki.grafana_cloud_otlp_endpoint.receiver]
        traces = [otelcol.exporter.otlphttp.grafana_cloud_otlp_endpoint.input]
      }
    }

    // loki.process "logs_process_client" {
    //   forward_to = [otelcol.receiver.loki.grafana_cloud_otlp_endpoint.receiver]

    //   stage.logfmt {
    //       mapping = { "kind" = "", "service_name" = "", "app" = "",app_name="",app_environment="", }
    //   }

    //   stage.labels {
    //       values = { "kind" = "kind", "service_name" = "service_name", "app" = "app", "app_name"="app_name", "app_environment"="app_environment",Application="app_name",Environment="app_environment", }
    //   }
    // }
```

I tried to debug this but no logs are published to Grafana cloud :(
