### ISSUE TITLE
Add ability to set log processing stages per `loki` destination

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1182]
This would mean that multiple destinations could be set, each with different rules. I would imagine the primary use would be drop/keep rules:

```yaml
destinations:
- name: localLoki
  type: loki
  url: loki.default.svc
- name: remoteLoki
  type: loki
  url: remote-loki.example.com
  extraLogProcessingStages: |
    stage.drop {
      expression = ".*debug.*"
    }
```

In this case, all logs go to `localLoki`, but only non-debug logs are shipped offsite to `remoteLoki`
