### ISSUE TITLE
Add ability to set filters per `otlp` destination

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1183]
Same as https://github.com/grafana/k8s-monitoring-helm/issues/1182, but for otelcol.processors.filter.

**Comment by jangaraj** [comment]
IMHO it's implemented:
```
  - name: otlpdestination
    type: otlp
    ...
    processors:
      filters:
        enabled: true 
        metrics:
          metric:
            # drop app1_.* and app2_.* metrics
            - IsMatch(metric.name, "app1_.*|app2_.*")
```
