### ISSUE TITLE
Applying adaptive metrics recommendations in Alloy v2

### ISSUE THREAD

**Issue by ChrisMcKee** [grafana/k8s-monitoring-helm#1203]
I've changed our setup over to V2 but had to roll back; initially we couldn't get the traces to ship because we had reciever set but it disabled in `applicationObservability` which I think we were associating with the Application tab in Grafana that adds host-hours etc to the bill.

Everything seems to now be piping through, but it's literally everything. When the agent was just prometheus in a dress we had all our config nailed down, but with each increment we've lost our filtering.

I've been fiddling with the config and going back and forth in the repo between v1/v2/and the docs to start boiling the ocean of metrics down before it leaves our cluster.

![Image](https://github.com/user-attachments/assets/0b46a255-0cc0-419c-a9d9-4ca4e37b80c6)

You can tell when we switched to the mess of a config below and when we switched to using the otel gateway for everything (which does simplify things)

Adaptive Metrics is useful but ultimately means we're still pumping noise into grafana cloud and paying for the ingress as well. We currently have 29 pages of recommendations.

Is there a single place I could aggregate the rule export and exclude them in the new layout or do I need to 
cram them in the `prometheus.relabel "unused_labels"` area. 

Is `useIntegrationAllowList` supposed to be the built in default whitelist for Grafana Cloud? If it is, what is `useDefaultAllowList` in comparison and why does `useIntegrationAllowList` only seem to exist in certain sections?

Some ability in grafana cloud to export the currently used metrics in alloy format would be useful (like reverse adapative metrics). But any help pointing me in the right direction would be appreciated.

```yaml
cluster:
  name: ${CLUSTER_NAME}

global:
  scrapeInterval: 120s

destinations:
  # https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/examples/destinations/otlp-endpoint/README.md
  # https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/destinations/otlp-values.yaml
  - name: oltp-gateway
    type: otlp
    url: https://${OLTP_GATEWAY_HOST}/otlp
    protocol: http
    auth:
      type: basic
      username: '${OLTP_GATEWAY_USER}'
      password: '${OLTP_GATEWAY_PASSWORD}'
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true

# requires pods to specify labels for discovery https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-annotation-autodiscovery
annotationAutodiscovery:
  enabled: true
  excludeNamespaces: ['kube-system', 'kube-public', 'default']
  metricsTuning:
    excludeMetrics: ['go_*']
  globals:
    scrapeInterval: 120s

podLogs:
  enabled: false
nodeLogs:
  enabled: false
profiling:
  enabled: false

selfReporting:
  enabled: true
  scrapeInterval: 90s

#https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-cluster-metrics/values.yaml
clusterMetrics:
  enabled: true
  kepler: #Energy Consumption Monitor
    enabled: false
  opencost:
    enabled: false
    metricsSource: prometheus
    global:
      scrapeInterval: 300s
    metricsTuning:
      excludeMetrics: []
      includeMetrics: []
    opencost:
      exporter:
        defaultClusterId: ${CLUSTER_NAME}
      prometheus:
        existingSecretName: prometheus-grafana-k8s-monitoring
        external:
          url: https://${GRAFANA_CLOUD_PROMETHEUS_HOST}/api/v1/query
  podLogs:
    enabled: false
  kubelet:
    enabled: true
    extraMetricProcessingRules: ''
    metricsTuning:
      excludeMetrics: []
      includeMetrics: []
      useDefaultAllowList: true
    scrapeInterval: 90s
  kubeletResource:
    enabled: true
    metricsTuning:
      excludeMetrics: []
      includeMetrics: []
      useDefaultAllowList: true
    scrapeInterval: 120s
  cadvisor:
    enabled: true
    metricsTuning:
      dropEmptyContainerLabels: true
      dropEmptyImageLabels: true
      excludeMetrics: []
      includeMetrics: []
      keepPhysicalFilesystemDevices:
        - mmcblk.p.+
        - nvme.+
        - rbd.+
        - sd.+
        - vd.+
        - xvd.+
        - dasd.+
      keepPhysicalNetworkDevices:
        - en[ospx][0-9].*
        - wlan[0-9].*
        - eth[0-9].*
      normalizeUnnecessaryLabels:
        - labels:
            - boot_id
            - system_uuid
          metric: machine_memory_bytes
      useDefaultAllowList: true
    scrapeInterval: 120s
  kube-state-metrics:
    deploy: true
    enabled: true
    global:
      scrapeInterval: 90s
    affinity: {}
    metricAllowlist: []
    metricAnnotationsAllowList: []
    metricDenylist: []
    metricLabelsAllowlist:
      - >-
        nodes=[agentpool,alpha.eksctl.io/cluster-name,alpha.eksctl.io/nodegroup-name,beta.kubernetes.io/instance-type,cloud.google.com/gke-nodepool,cluster_name,ec2_amazonaws_com_Name,ec2_amazonaws_com_aws_autoscaling_groupName,ec2_amazonaws_com_aws_autoscaling_group_name,ec2_amazonaws_com_name,eks_amazonaws_com_nodegroup,k8s_io_cloud_provider_aws,karpenter.sh/nodepool,kubernetes.azure.com/cluster,kubernetes.io/arch,kubernetes.io/hostname,kubernetes.io/os,node.kubernetes.io/instance-type,topology.kubernetes.io/region,topology.kubernetes.io/zone]
    metricsTuning:
      excludeMetrics: []
      includeMetrics: []
      useDefaultAllowList: true
  node-exporter:
    global:
      scrapeInterval: 300s
    enabled: true
    deploy: true
    scrape_interval: 300s
    metricsTuning:
      useDefaultAllowList: true
      useIntegrationAllowList: true
      dropMetricsForFilesystem:
        - tempfs
      excludeMetrics:
        - go_*
        - node_filesystem_device_error
        - node_filesystem_readonly
        - node_filesystem_files
  windows-exporter:
    enabled: true
    deploy: true
    releaseLabel: false
    scrape_interval: 300s
    metricsTuning:
      excludeMetrics:
        - go_*
      includeMetrics: []
      useDefaultAllowList: true
    image:
      registry: 'docker.io'
      repository: 'chrismckee/windows-exporter-test'
      tag: latest
      pullPolicy: IfNotPresent
      digest: ''
    config: |-
      collectors:
        enabled: cpu,cs,container,logical_disk,memory,net,os
      collector:
        service:
          services-where: "Name='containerd' or Name='kubelet'"

#https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-prometheus-operator-objects/values.yaml
prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true
  probes:
    enabled: false
  global:
    scrapeInterval: 120s
  podMonitors:
    enabled: true
    excludeNamespaces: ['monitoring', 'kube-system', 'kube-public', 'default',"haproxy-controller"]
  serviceMonitors:
    excludeNamespaces: ['monitoring', 'kube-system', 'kube-public', 'default',"haproxy-controller"]
    extraDiscoveryRules: ''
    extraMetricProcessingRules: ''
    metricsTuning:
      excludeMetrics:
        - go_*
        - node_filesystem_device_error
        - node_filesystem_readonly
        - node_filesystem_files
      includeMetrics: []

clusterEvents:
  enabled: true
  global:
    scrapeInterval: 120s
  labelsToKeep:
    - job
    - level
    - namespace
    - node
    - source

#https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-application-observability/values.yaml
applicationObservability:
  enabled: true
  global:
    scrapeInterval: 120s
  metrics:
    enabled: true
  logs:
    enabled: false # we use vector for logs
  traces:
    enabled: true
    filters: # taken from https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring-v1/docs/examples/traces-enabled/README.md as v2 has no example https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.processor.filter/
      span:
        - attributes["http.route"] == "health"
        - attributes["http.route"] == "health/ready"
        - attributes["http.route"] == "api/health/ready"
        - attributes["http.route"] == "api/health"
        - attributes["http.route"] == "health/live"
        - attributes["http.route"] == "api/health/live"
        - attributes["http.route"] == "ping"
        - attributes["http.route"] == "api/ping"
        - attributes["http.route"] == "api/hc"
        - attributes["http.route"] == "hc"
  receivers:
    otlp:
      includeDebugMetrics: false
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
  processors:
    batch:
      maxSize: 0
      size: 16384
      timeout: 2s
    k8sattributes:
      annotations: []
      labels: []
      metadata:
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.deployment.name
        - k8s.statefulset.name
        - k8s.daemonset.name
        - k8s.cronjob.name
        - k8s.job.name
        - k8s.node.name
        - k8s.pod.uid
        - k8s.pod.start_time
    memoryLimiter:
      checkInterval: 1s
      enabled: false
      limit: 0MiB
  connectors: # This adds to the application host costs
    grafanaCloudMetrics:
      enabled: false
    spanLogs:
      enabled: false
    spanMetrics:
      enabled: false
  collector: alloy-receiver

alloy-receiver:
  enabled: true
  global:
    scrapeInterval: 90s
  liveDebugging:
    enabled: false
  alloy:
    enableReporting: true
    extraPorts:
      - name: otlp-grpc
        port: 4317
        protocol: TCP
        targetPort: 4317
      - name: http
        port: 4318
        protocol: TCP
        targetPort: 4318
  controller:
    type: daemonset
    enableStatefulSetAutoDeletePVC: true
    nodeSelector:
      kubernetes.io/os: linux
      type: system
    tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: system

alloy-singleton:
  enabled: true
  controller:
    type: deployment
    replicas: 1
    global:
      scrapeInterval: 120s
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    nodeSelector:
      kubernetes.io/os: linux
      type: system
    tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: system
    enableStatefulSetAutoDeletePVC: true

alloy-metrics:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: '1m'
        memory: '500Mi'
    clustering:
      name: alloy-metrics
      enabled: true
  controller:
    type: statefulset
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 0
      targetMemoryUtilizationPercentage: 80
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: 'peristent'
        operator: 'Equal'
        value: 'true'
        effect: 'NoSchedule'
  extraConfig: |
    // to scrape node metrics from windows instances
    discovery.ec2 "win_exporter" {
      port = 9182
      filter {
        name  = "tag:prometheus" 
        values = ["true"]
      }
    }
    prometheus.scrape "win_exporter" {
      targets    = discovery.ec2.win_exporter.targets
      forward_to = [otelcol.receiver.prometheus.otlp_gateway.receiver]
      scrape_interval = "300s"
    }

    // to scrape quoteware app metrics from windows instances
    discovery.ec2 "prom_exporter" {
      port = 9598
      filter {
        name  = "tag:prometheus" 
        values = ["true"]
      }
    }

    prometheus.scrape "prom_exporter" {
      targets    = discovery.ec2.prom_exporter.targets
      forward_to = [otelcol.receiver.prometheus.otlp_gateway.receiver]
      scrape_interval = "300s"
    }

    prometheus.relabel "unused_labels" {
      forward_to = [otelcol.receiver.prometheus.otlp_gateway.receiver]
      rule {
        source_labels = ["__name__"]
        regex         = "probe_all_duration_seconds_bucket|dns_lookup_duration_bucket|dns_lookup_duration_drop|dns_lookup_duration_sum|windows_service_status|kube_replicaset_metadata_generation|kube_replicaset_status_fully_labeled_replicas|kube_replicaset_status_observed_generation|kube_replicaset_status_replicas|http_client_request_duration_bucket|windows_service_start_mode|http_client_request_time_in_queue_bucket|funder_processing_time_bucket|http_client_connection_duration_bucket|http_server_duration_bucket|windows_service_info|traces_service_graph_request_client_seconds_bucket|traces_service_graph_request_server_seconds_bucket|kestrel_connection_duration_bucket|windows_exporter_collector_success|windows_exporter_collector_timeout|windows_exporter_collector_duration_seconds|kube_persistentvolume_status_phase|windows_process_pool_bytes|kube_job_complete|dns_lookup_duration_sum|dns_lookup_duration_count|http_server_request_duration_sum"
        action        = "drop"
      }
    }

alloy-logs:
  enabled: false
alloy-profiles:
  enabled: false

extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: grafana-alloy-agent-ui-${CLUSTER_NAME}
      namespace: monitoring
      labels:
        app.kubernetes.io/name: alloy-receiver
    spec:
      ports:
        - name: http-metrics
          port: 80
          protocol: TCP
          targetPort: 12345
      selector:
        app.kubernetes.io/instance: grafana-k8s-monitoring
        app.kubernetes.io/name: alloy-receiver
  - apiVersion: v1
    kind: Service
    metadata:
      name: otel-collector
      namespace: monitoring
      labels:
        app.kubernetes.io/name: alloy-receiver
    spec:
      ports:
        - appProtocol: grpc
          name: otlp
          port: 4317
          protocol: TCP
          targetPort: 4317
        - name: otlp-http
          port: 4318
          protocol: TCP
          targetPort: 4318
      selector:
        app.kubernetes.io/instance: grafana-k8s-monitoring
        app.kubernetes.io/name: alloy-receiver
```
