### ISSUE TITLE
Can't turn MySQL log integration off

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1217]
```
integrations:
  mysql:
    instances:
      - name: staging-db
        logs:
          enabled: false # <--- doesn't work
```
