### ISSUE TITLE
Add ability to attach node labels to all scrape jobs regardless of role

### ISSUE THREAD

**Issue by bentonam** [grafana/k8s-monitoring-helm#1223]
Alloy `discover.kubernetes` has an `attach_metadata{}` block that can optionally include additional node information on discoveries that are not `role="node"` for example `role="pod"` this would also include all `__meta_kubernetes_node` labels and annotations.  

Oftentimes we need to know the region, availability zone, node pool that a pod belongs in.  

**Proposal** for each job in `clusterMetrics:` have a setting: 

```yaml
clusterMetrics:
  cadvisor:
    metricsTuning:
      nodeLabels: 
        # Whether or not to attach the node pool 
        nodepool: true
        # Whether or not to add the region
        region: true
        # Whether or not to add the availability_zone
        availability_zone: true
```
