### ISSUE TITLE
Error calling eq: incompatible types for comparison

### ISSUE THREAD

**Issue by Archer-Li** [grafana/k8s-monitoring-helm#1224]
This issue pops up when I'm installing the helm chart through terraform option with grafana cloud provided value.

```
│ Error: template: k8s-monitoring/templates/secrets/test/secrets.yaml:13:7: executing "k8s-monitoring/templates/secrets/test/secrets.yaml" at <eq .Values.testing "true">: error calling eq: incompatible types for comparison
```
It seems we need to ensure that `.Values.testing` is treated as a string here? Is there any configuration I missed?
https://github.com/grafana/k8s-monitoring-helm/blob/37f67c8d4afeae4304e61e34743e2b3cabb266c3/charts/k8s-monitoring/templates/secrets/test/secrets.yaml#L13

Helm version: 2.0.5+
Helm value.yaml:
```
destinations:
  - name: my-prom
    type: prometheus
    auth:
      type: basic
  - name: my-logs
    type: loki
    auth:
      type: basic
clusterMetrics:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true

```
