### ISSUE TITLE
kube_horizontalpodautoscaler_metadata_info/generation not ingested

### ISSUE THREAD

**Issue by churtado-tech** [grafana/k8s-monitoring-helm#1225]
I'm experiencing an issue where the "kube_horizontalpodautoscaler_metadata_info/generation" metric, exposed by kube-static, is not being ingested by Prometheus. I can see the metric when querying kube-static directly, but it's not present in Prometheus.

I would like to use a community dashboard to monitorize the correct hpa.

How can i check if it's correctly parsed or scraped?

My k8s-monitoring config is the following.

```yaml
cluster:
  name: dev-xxx-cluster

destinations:
  - name: prometheus
    type: prometheus
    url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
    
  - name: loki
    type: loki
    url: "http://grafana-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push"


alloy-singleton:
  enabled: true
  alloy:
    stabilityLevel: experimental
  liveDebugging:
    enabled: true

alloy-metrics:
  enabled: true

prometheusOperatorObjects:
  enabled: true

alloy-logs:
  enabled: true

clusterMetrics:
  enabled: true
  cadvisor:
    enabled: true

clusterEvents:
  enabled: true
``` 

Thanks in advance for all your amazing job.

**Comment by petewall** [comment]
These are currently the only HPA metrics from kube-state-metrics we're keeping:
https://github.com/grafana/k8s-monitoring-helm/blob/main/allowLists/kube-state-metrics.yaml#L12-L15

If you want to add those metrics, add this to your values file:
```
clusterMetrics:
  kube-state-metrics:
    metricsTuning:
      includeMetrics:
        - kube_horizontalpodautoscaler_info
        - kube_horizontalpodautoscaler_metadata_generation
```
