### ISSUE TITLE
Error calling ne: incompatible types for comparison

### ISSUE THREAD

**Issue by Archer-Li** [grafana/k8s-monitoring-helm#1241]
`
template: k8s-monitoring/templates/validations.yaml:5:4: executing "k8s-monitoring/templates/validations.yaml" at <include "destinations.validate" .>: error calling include: template: k8s-monitoring/templates/destinations/_destination_validations.tpl:40:46: executing "destinations.validate" at <ne $destination.protocol "http">: error calling ne: incompatible types for comparison
`

I think `(ne $destination.protocol "http")` will be evaluated for every destination item (including loki, prometheus...etc.). Without protocol set will immediately causing mismatch type error.  
```   
{{- if and (eq $destination.type "otlp") (ne $destination.protocol "http") (regexMatch "otlp-gateway-.+grafana\\.net" $destination.url) }}
```
Helm version: 2.0.10
Helm value.yaml:
```
destinations:
  - name: my-prom
    type: prometheus
    auth:
      type: basic
  - name: my-logs
    type: loki
    auth:
      type: basic
clusterMetrics:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-logs
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
alloy-logs:
  enabled: true
```
