### ISSUE TITLE
[v2] Annotation Autodiscovery improvements

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1244]
Some improvements to the annotationAutodiscovery feature:
* Have a switch to enable/disable pods or services:
```
pods:
  enabled: true

services:
  enabled: true
```

* Make it easy to set static labels and extract common labels:

```
pods:
  labels:
    pod: __meta_kubernetes_pod_name
    namesapace: __meta_kubernetes_namespace
    node: __meta_kubernetes_pod_node_name
    region: __meta_kubernets_pod_label_region
  staticLabels:
    color: red
```

* Add the ability to extract `__param_<key>__` parameters:
```
annotations:
  metricsScrapeParams: k8s.grafana.com/metrics.param.
```

Which would set:
```
    rule {
      action = "labelmap"
      regex = "__meta_kubernetes_pod_annotation_k8s_grafana_com_metrics_param_(.+)"
      replacement = "__param_$1"
    }
```

* Add label matchers to better filter pods and services:
```
labelMatchers:
  region: us
pods:
  labelMatchers:
    color: blue
```

will result in:
```
discovery.kubernetes "pods" {
  role = "pod"
  selectors {
    role = "pod"
    label = "region=us,color=blue"
  }
}
```
This is more efficient that filtering in the discovery.relabel section. It could be, and should be, unique per pods and services.
