### ISSUE TITLE
[v2] feature-annotation-autodiscovery not setting namespace on metrics?

### ISSUE THREAD

**Issue by mikl** [grafana/k8s-monitoring-helm#1289]
I have been trying to use feature-annotation-autodiscovery from this Helm chart to scrape various Prometheus endpoints, but I’m a little surprised that it does not label the metrics with the usual labels like namespace:

<img width="418" alt="Image" src="https://github.com/user-attachments/assets/aecfe9f4-2a28-4c64-978d-e8eb1d01aff4" />

(the prod namespace is coming from OpenTelemetry metrics).

On the service in question, I have

```yaml
  annotations:
    k8s.grafana.com/scrape: "true"
    k8s.grafana.com/metrics.portName: prometheus
```

in the values for this Helm chart, I have

```yaml
annotationAutodiscovery:
  enabled: true
```

It clearly finds the service in the `prod` namespace (Alloy runs in a `grafana-cloud` namespace), so it should be aware of what the namespace is and be able to tag it.

Am I doing something wrong, or is this the expected behavior?
