### ISSUE TITLE
kube-prometheus-stack compatibility

### ISSUE THREAD

**Issue by Utwo** [grafana/k8s-monitoring-helm#1296]
Not really an issue, but a helpful tip. 
For anyone interested in running the dashboards/rules/alerts from `kube-prometheus-stack` with the `k8s-monitoring-helm` alloy collector, I have managed to make it work with the following config:

```yaml
cluster:
   name: <nameOfTheCluster>

destinations:
  - name: prometheus
    type: prometheus
    url: ...
  - name: loki
     ...

clusterEvents:
  enabled: true

clusterMetrics:
  enabled: true
  apiServer:
    enabled: true
    jobLabel: apiserver
  kubelet:
    jobLabel: kubelet
    extraMetricProcessingRules: |
      rule {
        replacement   = "/metrics"
        target_label  = "metrics_path"
      }
  cadvisor:
    jobLabel: kubelet
    extraMetricProcessingRules: |
      rule {
        replacement   = "/metrics/cadvisor"
        target_label  = "metrics_path"
      }
  node-exporter:
    jobLabel: node-exporter
    metricsTuning:
      includeMetrics:
        - node_uname_info
        - node_time_seconds
        - node_disk_io_time_seconds_total
        - node_disk_io_time_weighted_seconds_total
        - node_load1
        - node_vmstat_pgmajfault
  kube-state-metrics:
    jobLabel: kube-state-metrics
  windows-exporter:
    deploy: false
    enabled: false

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

podLogs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true

alloy-singleton:
  enabled: true

integrations:
  collector: alloy-singleton
```

With the following helm values, you should have all the kube-prometheus-stack dashboards populated and alerts active.

**Comment by tanvp112** [comment]
Do you install prometheus via kube-prometheus-stack in this case? Wonder if it is possible to just to install prometheus but not any of the scraping feature of kube-prometheus-stack...

**Comment by Utwo** [comment]
No, Prometheus is installed from this repo, `grafana/k8s-monitoring-helm`. I'm using `kube-prometheus-stack` just for dashboards, rules, alerts, and grafana(optional).

Here is the helm value file for `kube-prometheus-stack`.

```
fullnameOverride: "kube-prometheus-stack"

defaultRules:
  create: true

grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true
prometheusOperator:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubernetesServiceMonitors:
  enabled: false
kubeProxy:
  enabled: false
alertmanager:
  enabled: false
  forceDeployDashboards: true
nodeExporter:
  enabled: false
  forceDeployDashboards: true
kubeStateMetrics:
  enabled: false
crds:
  enabled: false
prometheus:
  enabled: false
```

**Comment by Utwo** [comment]
I have copied/pasted the values from the `kube-prometheus-stack` and `k8s-monitoring-helm` helm charts above. In my case, I've installed grafana separately. You should have `grafana_dashboard: "1"` label on every grafana dashboard configMap for the Grafana sidecar to register the dashboard.

On the Grafana side (kube-prometheus-stack), you should have something like this:
```
grafana:
  forceDeployDashboards: false
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      # Allow discovery in all namespaces for dashboards
      searchNamespace: ALL
```

You can set `forceDeployDashboards: true` if you want to deploy just the dashboards without Grafana.
