### ISSUE TITLE
[v2] Duplicated cluster label with no way to disable it

### ISSUE THREAD

**Issue by marcinmigda-spoton** [grafana/k8s-monitoring-helm#1308]
Current setup for v2 by default configure 2 external labels https://github.com/grafana/k8s-monitoring-helm/blob/f2cfba4ec0ddd2fa3be3eeb4793118fa9882742c/charts/k8s-monitoring/templates/destinations/_destination_loki.tpl#L110

```
external_labels = {
  cluster = "my-cluster-name",
  "k8s_cluster_name" = "my-cluster-name"
}
```

This makes both labels to be indexed which makes it redundant. I don't need to have both indexed when the number of labels I can have indexed in Loki is limited. I thought I'll be able to add `extraLabels` with `k8s_cluster_name` and empty value to overwrite one of external_labels I don't need but because of quotes hardcoded in helm chart it's not possible because extraLabels remove quotes during a deployment.

Is there any way to disable indexing one of it using v2 helm chart configuration?

**Comment by kpinarci** [comment]
I’m encountering a similar issue: despite using stage.label_drop within extraLogProcessingStages to remove the k8s_cluster_name label, it continues to appear in the log stream and isn’t being excluded as expected.

```yaml
podLogs:
  enabled: true
  destinations:
    - hostedLogs
  collector: alloy-logs
  namespaces: [mimir, k8s-monitoring, consul]
  extraLogProcessingStages: |-
    stage.label_drop {
      values = ["k8s_cluster_name"]
    }
```
Additionally, I’d like to remove the following two labels, as they effectively duplicate existing metadata:
	•	`app_kubernetes_io_name`, which replicates the combination of the `namespace` and `container` name
	•	`k8s_cluster_name`, which simply reflects the `cluster` identifier

Is there a recommended or supported approach to reliably strip these labels from the log stream?
