### ISSUE TITLE
v2 - How to add pod + namespace to metrics receivied by OTLP

### ISSUE THREAD

**Issue by marquesj2-ppb** [grafana/k8s-monitoring-helm#1312]
How can I enrich prometheus metrics exported by the OTLP Receiver with namespace + pod name?

**Comment by marquesj2-ppb** [comment]
Figured it out 😅 

```yaml
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  metrics:
    transforms:
      datapoint:
        - set(attributes["pod"], resource.attributes["k8s.pod.name"])
        - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
        - set(attributes["serviceName"], resource.attributes["service.name"])
```

I wonder if this screws up OTLP data in the future 🤔
