### ISSUE TITLE
Override Image registry for all features

### ISSUE THREAD

**Issue by undefinedhuman** [grafana/k8s-monitoring-helm#1344]
If a company has the requirement to pull all Docker images through a private registry, it would be very helpful if the registry + imagePullSecrets could be overriden by one single global setting.

For Grafana Charts (Beyla and Alloy) this can be achieved by setting:

```
global:
  image:
    registry: bla.registry.com/docker
    pullSecrets:
      - name: docker-auth-config-secret-name
```

All other features have to be overriden manually.
