### ISSUE TITLE
MySQL integration doesn't work with `dataSource`

### ISSUE THREAD

**Issue by antoineozenne** [grafana/k8s-monitoring-helm#1346]
When using the following config (with `dataSource`):

```yaml
  integrations:
    mysql:
      instances:
        - name: fooMariadb
          logs:
            enabled: true
            labelSelectors:
              app.kubernetes.io/instance: foo-mariadb
          metrics:
            enabled: true
          exporter:
            dataSource:
              host: foo-mariadb.foo-mariadb.svc.cluster.local
              port: 3306
              auth:
                usernameKey: foo-mariadb-username
                passwordKey: foo-mariadb-password
          secret:
            create: false
            embed: false
            name: foo-k8s-monitoring
            namespace: foo-k8s-monitoring
```

I get the following error:

```console
ts=2025-03-20T16:08:19.36692122Z level=error msg="Error opening connection to database" component_path=/mysql_integration.integration component_id=prometheus.exporter.mysql.foomariadb err="Error 1045 (28000): Access denied for user 'myuser'@'10.240.1.97' (using password: YES)"
```

However, it works when using the following config (with `dataSourceName` and the same user, password, host and port):

```yaml
integrations:
    mysql:
      instances:
        - name: fooMariadb
          logs:
            enabled: true
            labelSelectors:
              app.kubernetes.io/instance: foo-mariadb
          metrics:
            enabled: true
          exporter:
            dataSourceName: "myuser:my-password@(foo-mariadb.foo-mariadb.svc.cluster.local:3306)/"
          secret:
            create: false
            embed: false
            name: foo-k8s-monitoring
            namespace: foo-k8s-monitoring
```

I haven't found a way to log the `data_source_name` variable in the generated alloy config to check it. Is there an issue with the generated `data_source_name` when using the `dataSource` block?

The password only contains alphanumeric characters and dashes.

**Comment by petewall** [comment]
When you're using the `dataSource` method, can you find the section within the alloy-metrics configmap?
Using that method should just build a `data_source_name` field for the `prometheus.exporter.mysql` component, i.e.

```
              prometheus.exporter.mysql "my_database" {
                data_source_name = string.format("%s:%s@(%s:%d)/",
                  convert.nonsensitive(remote.kubernetes.secret.foomariadb.data["usernameKey"]),
                  remote.kubernetes.secret.foomariadb.data["passwordKey"],
                  "foo-mariadb.foo-mariadb.svc.cluster.local",
                  3306,
                )
                enable_collectors = ["heartbeat","mysql.user"]
              }
```

**Comment by antoineozenne** [comment]
Yes, the section is here:

```alloy
prometheus.exporter.mysql "foomariadb" {
  data_source_name = string.format("%s:%s@(%s:%d)/",
    convert.nonsensitive(remote.kubernetes.secret.foomariadb.data["foo-mariadb-username"]),
    remote.kubernetes.secret.foomariadb.data["foo-mariadb-password"],
    "foo-mariadb.foo-mariadb.svc.cluster.local",
    3306,
  )
  enable_collectors = ["heartbeat","mysql.user"]
}
```

**Comment by petewall** [comment]
Ok, cool.
And the pre-existing secret `foo-k8s-monitoring` has these keys (according to your examples):
* `foo-mariadb-username` with the value `myuser`
* `foo-mariadb-password` with the value `my-password`

It looks like its building the string correctly, but maybe it's not accessing the secret or the secret keys are slightly off. If the key is not correct, the strings will return empty values, likely causing the "Access denied for user 'myuser" error.

**Comment by petewall** [comment]
This is really bizzare.
I've updated the MySQL integration test ([PR](https://github.com/grafana/k8s-monitoring-helm/pull/1371)) to make sure there wasn't an issue with loading the username. that's working fine.

The error message:

> Access denied for user 'myuser'@'10.240.1.97' (using password: YES)"

implies that the connection is working, the username is being sent, but the password is incorrect. Can you try, temporarily, doing this to embed the password:

```yaml
  integrations:
    mysql:
      instances:
        - name: fooMariadb
          logs:
            enabled: true
            labelSelectors:
              app.kubernetes.io/instance: foo-mariadb
          metrics:
            enabled: true
          exporter:
            dataSource:
              host: foo-mariadb.foo-mariadb.svc.cluster.local
              port: 3306
              auth:
                usernameKey: foo-mariadb-username
                passwordFrom: "\"my-db-password\""			# Change this, the quotes and escaped quotes are important.
          secret:
            create: false
            embed: false
            name: foo-k8s-monitoring
            namespace: foo-k8s-monitoring
```

If this works, then there must be something related to the entry in the password that's affected.
