### ISSUE TITLE
Helm Installation fails with Azure AKS

### ISSUE THREAD

**Issue by TomDoesb** [grafana/k8s-monitoring-helm#1361]
Hi, 

Im using the grafana cloud generated template for Azure AKS. but when running it I get the following error:

```bash
"grafana" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "prometheus-community" chart repository
Update Complete. ⎈Happy Helming!⎈
Release "grafana-k8s-monitoring" does not exist. Installing it now.
Error: execution error at (k8s-monitoring/templates/validations.yaml:1:4):
This Kubernetes cluster appears to be Azure AKS.
To ensure connectivity to the API server, please set:
clusterMetrics:
  kube-state-metrics:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
```

When I check the clusterMetrics section it is already there:
```yaml
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: MY-CLUSTER
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  kepler:
    enabled: true
  kube-state-metrics:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
```

Below the full by grafana cloud generated helm command (secrets and cluster name are replaced for security reasons):

```yaml
helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --version ^2 --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "grafana" --create-namespace --values - <<'EOF'
cluster:
  name: MY-CLUSTER
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
  - name: grafana-cloud-traces
    type: otlp
    url: https://tempo-eu-west-0.grafana.net:443
    protocol: grpc
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: MY-CLUSTER
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  kepler:
    enabled: true
  kube-state-metrics:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
  connectors:
    grafanaCloudMetrics:
      enabled: true
alloy-metrics:
  enabled: true
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: MY-CLUSTER
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-003.grafana.net
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
alloy-singleton:
  enabled: true
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: MY-CLUSTER
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-003.grafana.net
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
alloy-logs:
  enabled: true
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-logs-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: MY-CLUSTER
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-003.grafana.net
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: MY-CLUSTER
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-003.grafana.net
    auth:
      type: basic
      username: "REMOVED-FOR-SECURITY"
      password: REMOVED-FOR-SECURITY
EOF
```

My Helm version: `version.BuildInfo{Version:"v3.17.2", GitCommit:"cc0bbbd6d6276b83880042c1ecb34087e84d41eb", GitTreeState:"clean", GoVersion:"go1.24.1"}`

To me it seems that the validation check is incorrect, but im not a helm expert. Can you see whats going wrong?
