### ISSUE TITLE
Support Referencing External Secret for Credentials

### ISSUE THREAD

**Issue by thebeanogamer** [grafana/k8s-monitoring-helm#1364]
To make deployment easier when using GitOps tools, it's often helpful to define credentials through something external then reference them within the Helm values. This doesn't seem to currently be possible for the destination or remote management credentials within this Chart.

I'd expect this to look something like the below.

```yaml
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push
    auth:
      type: basic
      existingSecret: <name>
```

This allows for keeping the Alloy deployment within GitOps but removes the need to commit plaintext credentials.

Apologies if this is already possible, but I couldn't see a way to do it when tracing through the Helm Chart. Several of my attempts at bodging it ran afoul of #1005.

**Comment by petewall** [comment]
This example should help: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/auth/external-secrets

The key is setting `secret.create = false`, which tells the Helm chart to expect the secret to already exist in the system. `secret` also has `name` and `namespace`, so you can select the specific secret object.

You can use `usernameKey` and `passwordKey` in place of `username` and `password` to choose the right fields within that secret.

**Comment by thebeanogamer** [comment]
Ah that looks like exactly what I was looking for. Does that also work for Remote Config?

**Comment by thebeanogamer** [comment]
> > Does that also work for Remote Config?
> 
> Yep!

Ah awesome, TYSM!

Am trying to switch over now with the below values:

```yaml
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-05-gb-south-0.grafana.net/api/prom/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
      secret:
        create: false
        name: "grafana-cloud-metrics-demo-grafana-cloud-k8s-monitoring"
        namespace: "grafana"
```

But #1005 is blocking me

```shell
$ helm template . --name-template demo-grafana-cloud --namespace grafana --kube-version 1.32 --values <path to cached source>/applications/grafana-alloy/cloud/demo/helm/values.yaml <api versions removed> --include-crds

Error: execution error at (k8s-monitoring/templates/validations.yaml:1:4): Destination #0 (grafana-cloud-metrics) is using basic auth but does not have a username. Please set: destinations: - name: grafana-cloud-metrics auth: type: basic username: my-username password: my-password Use --debug flag to render out invalid YAML
```
