### ISSUE TITLE
Kepler default value is True

### ISSUE THREAD

**Issue by sokato-mdsol** [grafana/k8s-monitoring-helm#1369]
There's a discrepancy between the actual default value and the document.
If  a user deploys with only the following value.yaml referencing , it will result in Kepler to be deployed.

```
dependencies:
  - name: k8s-monitoring
    version: "2.0.21"
    repository: https://grafana.github.io/helm-charts
```
```
  clusterMetrics:
    enabled: true
```

https://github.com/grafana/k8s-monitoring-helm/blob/292d4725dc29c4befdbfbc4ac7f8241c5bde3c70/charts/k8s-monitoring/charts/feature-cluster-metrics/README.md?plain=1#L184

Expected result: Kepler shouldn't be deployed be default.

**Comment by petewall** [comment]
Kepler is disabled by default.
The deployment is controlled by `kepler.enabled`:
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-cluster-metrics/Chart.yaml#L31-L34

And that's set to false in the values.yaml file:
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-cluster-metrics/values.yaml#L842-L846

**Comment by petewall** [comment]
There must be other values.yaml involved. This chart will not pass validation if the only values.yaml passed in is:
```yaml
  clusterMetrics:
    enabled: true
```

It will require the `cluster.name` field to be enabled, for `alloy-metrics` to be enabled, and for destinations to be defined at minimum.

Check your deployment system and see if there are other fields being set in another means.

**Comment by sokato-mdsol** [comment]
Apologies, I redacted some info on my values file. Here's the full values file. This is a running configuration.
```
---
k8s-monitoring:
  cluster:
    name: <masked>
  destinations:
    - name: mimir
      type: prometheus
      url: <masked>
  clusterMetrics:
    enabled: true
    node-exporter:
      deploy: false
    kepler:
      enabled: false
    opencost:
      opencost:
        prometheus:
          external:
            url: <masked>
  alloy-metrics:
    enabled: true
  ```
Once I comment out the kepler section, I can confirm that it is trying to deploy the kepler service.

![Image](https://github.com/user-attachments/assets/2acec9ed-697c-40fc-8408-3c9497ca1807)

**Comment by petewall** [comment]
Interesting. I've tried with my own argocd deployment and using `clusterMetrics.kepler.enabled = false` or just not having kepler section defined at all. In both cases, I don't get a kepler deployment.

Another good check, does the configmap for `alloy-metrics` include config for scraping kepler? If so, that would imply that kepler is being enabled somehow. If not, that would imply that the Helm conditional is not being respected by Argo.

**Comment by kubicgruenfeld** [comment]
I face the same issue. Must be something odd with argoCD. With the same chart and values but deployed with helmfile it behaves like expected and opencost and kepler aren't getting deployed.

**Comment by Pionerd** [comment]
Similar behavior here for OpenCost (also using ArgoCD). Will dig into it.

**Comment by Utwo** [comment]
I'm experiencing a similar issue, and I'm not sure if it is related to argoCD or this helm chart. When I run locally `helm template grafana/k8s-monitoring --values=...` everything renders as expected. However, in argoCD, the resources->requests/limits are not overwritten at all. The default values are used.

Here is my value file using k8s-monitoring 3.3.:
```
cluster:
   name: test

destinations:
...

clusterEvents:
  enabled: true
  destinations: [loki]

clusterMetrics:
  enabled: true
  destinations: [vm]
  apiServer:
    enabled: true
    jobLabel: apiserver
  kubelet:
    jobLabel: kubelet
    extraMetricProcessingRules: |
      rule {
        replacement   = "/metrics"
        target_label  = "metrics_path"
      }
  cadvisor:
    jobLabel: kubelet
    extraMetricProcessingRules: |
      rule {
        replacement   = "/metrics/cadvisor"
        target_label  = "metrics_path"
      }
  node-exporter:
    jobLabel: node-exporter
    metricsTuning:
      includeMetrics:
        - node_uname_info
        - node_time_seconds
        - node_disk_io_time_seconds_total
        - node_disk_io_time_weighted_seconds_total
        - node_load1
        - node_vmstat_pgmajfault
  kube-state-metrics:
    jobLabel: kube-state-metrics
  windows-exporter:
    deploy: false
    enabled: false

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

podLogs:
  enabled: true
  gatherMethod: filelog
  destinations: [loki]

alloy-metrics:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 20m
        memory: 650Mi
      limits:
        cpu: 30m
        memory: 700Mi

alloy-logs:
  enabled: true
  controller:
    tolerations:
      - effect: NoSchedule
        operator: Exists
  alloy:
    stabilityLevel: public-preview
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 20m
        memory: 150Mi

alloy-singleton:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 10m
        memory: 60Mi
      limits:
        cpu: 20m
        memory: 100Mi

integrations:
  collector: alloy-singleton
```
