### ISSUE TITLE
Loki custom cluster label doesn't work

### ISSUE THREAD

**Issue by alextricity25** [grafana/k8s-monitoring-helm#1395]
I think [this PR ](https://github.com/grafana/k8s-monitoring-helm/pull/1381)broke the cluster name labels for loki. I have this setting in my values.yaml:

    'cluster': {
      name: 'my-cluster-label',
    },
And after upgrading to version 2.0.23 this morning my loki metrics no longer have this label. They now have the label cluster: loki, which I presume is the default for this destination.

Even after adding the clusterLabels to my loki destination, the cluster label still appears as loki, rather than my-cluster-label.

      {
        name: 'localLoki',
        type: 'loki',
        clusterLabels: ['cluster'],
        url: <my-url>
        logs: {
          enabled: true,
        },
      },

Reverting back to v2.0.22 fixed the issue.

cc @petewall 

Edit: changed log labels to **metric** labels

**Comment by jhychan** [comment]
Working fine for me on v2.0.23, helm charts via argocd.

Have tested both OTLP and native destinations and the rendered alloy config correctly sets the cluster label according to clusterLabels.

**Comment by rlankfo** [comment]
@alextricity25 can you share your values.yaml? It looks like integration tests we have are still working with the change. If you can share your values.yaml, I'll see if I can reproduce the issue.

**Comment by alextricity25** [comment]
> [@alextricity25](https://github.com/alextricity25) can you share your values.yaml? It looks like integration tests we have are still working with the change. If you can share your values.yaml, I'll see if I can reproduce the issue.

Sure thing:
```
alloy-logs:
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    tolerations:
    - effect: NoSchedule
      key: kubernetes.io/arch
      operator: Equal
      value: arm64
  enabled: true
alloy-metrics:
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    replicas: 2
    tolerations:
    - effect: NoSchedule
      key: kubernetes.io/arch
      operator: Equal
      value: arm64
  enabled: true
alloy-singleton:
  controller:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    tolerations:
    - effect: NoSchedule
      key: kubernetes.io/arch
      operator: Equal
      value: arm64
  enabled: true
cluster:
  name: my-cluster-name
clusterEvents:
  enabled: true
clusterMetrics:
  desinations:
  - http://mimir-distributed-gateway.mimir.svc.cluster.local/prometheus
  enabled: true
  kube-state-metrics:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    tolerations:
    - effect: NoSchedule
      key: kubernetes.io/arch
      operator: Equal
      value: arm64
  kubeStateMetrics:
    enabled: true
destinations:
- metrics:
    enabled: true
  name: localMimir
  type: prometheus
  url: http://mimir-distributed-gateway.mimir.svc.cluster.local:80/api/v1/push
- clusterLabels:
  - cluster
  logs:
    enabled: true
  name: localLoki
  type: loki
  url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
- name: localTempo
  traces:
    enabled: true
  type: otlp
  url: http://tempo-gateway.tempo.svc.cluster.local:80/v1/traces
podLogs:
  enabled: true
prometheusOperatorObjects:
  enabled: true
```
