### ISSUE TITLE
Possible missing metric features during v1 to v2 migration

### ISSUE THREAD

**Issue by anwbtom** [grafana/k8s-monitoring-helm#1400]
We've spent quite a bit of effort to try to migrate from v1 to v2 of the k8s-monitoring chart.  
Mostly we've been successful to translate stuff towards the new setup (although some features/settings are quite 'hidden' but mostly with checking the source or other issues were able to figure it out.  

There's two things related to the metric setup that I cannot seem to find an alternative to, both relating to the kube-state-metrics service.
One is we used to set some rbac settings (which seems to have been added relatively recent: https://github.com/grafana/k8s-monitoring-helm/issues/1219#issuecomment-2679534856) for it so it could collect metrics from flux and the secondary were some customResourceState for said flux-system, is this indeed something that no longer can be done?  

To not make this issue to long, won't post the full configuration (since its just a repeat for some other resources, but otherwise repeating the same "bit" a couple of times), but what we were setting was:

``` yaml
kube-state-metrics:
  enabled: true
  rbac:
    extraRules:
      - apiGroups:
          - source.toolkit.fluxcd.io
          - kustomize.toolkit.fluxcd.io
          - helm.toolkit.fluxcd.io
          - notification.toolkit.fluxcd.io
        resources:
          - gitrepositories
          - buckets
          - helmrepositories
          - helmcharts
          - ocirepositories
          - kustomizations
          - helmreleases
          - alerts
          - providers
          - receivers
        verbs: [ "list", "watch" ]
  customResourceState:
    enabled: true
    config:
      spec:
        resources:
          - groupVersionKind:
              group: notification.toolkit.fluxcd.io
              version: v1beta3
              kind: Provider
            metricNamePrefix: gotk
            metrics:
              - name: "resource_info"
                help: "The current state of a GitOps Toolkit resource."
                each:
                  type: Info
                  info:
                    labelsFromPath:
                      name: [ metadata, name ]
                labelsFromPath:
                  exported_namespace: [ metadata, namespace ]
                  suspended: [ spec, suspend ]
          - groupVersionKind:
              group: notification.toolkit.fluxcd.io
              version: v1
              kind: Receiver
            metricNamePrefix: gotk
            metrics:
              - name: "resource_info"
                help: "The current state of a GitOps Toolkit resource."
                each:
                  type: Info
                  info:
                    labelsFromPath:
                      name: [ metadata, name ]
                labelsFromPath:
                  exported_namespace: [ metadata, namespace ]
                  ready: [ status, conditions, "[type=Ready]", status ]
                  suspended: [ spec, suspend ]
                  webhook_path: [ status, webhookPath ]
```

Hope I am just missing something and its already a possibility (or maybe no longer necessary), if some information is missing or something is unclear please let me know.

Thanks in advance for the information/help!

**Comment by rlankfo** [comment]
@anwbtom This `customResourceState` block comes from the kube-state-metrics helm chart which I believe is embedded in the feature-cluster-metrics section of the chart.

Does something like this work for you?

```yaml
clusterMetrics:
  enabled: true
  kube-state-metrics:
    deploy: true
    rbac:
      ...
    customResourceState:
      ...
```

With the latest version of the chart, we're embedded 5.31.0 of the kube-state-metrics chart here:
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/charts/feature-cluster-metrics/Chart.yaml#L14-L17
