### ISSUE TITLE
Setting tenantId in loki destination doesn't work

### ISSUE THREAD

**Issue by majkshkurti** [grafana/k8s-monitoring-helm#1402]
The `tenantId` does not appear to work as expected in the Helm configuration for Loki authentication. 
According to the documentation, it should be possible to set it inside auth section but the following doesn't work:

```
  - name: loki
      type: loki
      url: https://loki.example.com/loki/api/v1/push
      auth:
        type: basic
        usernameKey: o11y_username
        passwordKey: o11y_password
        tenantIdFrom: o11y-basic-auth -----> configMap
      secret:
        create: false
        name: o11y-basic-auth
        namespace: monitoring

     
```

It looks like the only way a user can define a `tenantId` is configuring it inside the configMap which has a "tenantId" key but this isn't very clear in the helm docs. 

```
    - name: loki
      type: loki
      url: https://loki.o11y.plan4better.de/loki/api/v1/push
      tenantId: "o11y-basic-auth" -----> configMap Should have the "tenantId" as a key
      auth:
        type: basic
        usernameKey: o11y_username
        passwordKey: o11y_password
      secret:
        create: false
        name: o11y-basic-auth
        namespace: monitoring

```
What is the function of `tenantIdFrom` and `tenantIdKey` and where can it be defined ?
