### ISSUE TITLE
How to not install windows-exporter

### ISSUE THREAD

**Issue by gregorycox** [grafana/k8s-monitoring-helm#1403]
What do I need to do to not install windows-exporter when running the chart below?

https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring

**Comment by dunningdan** [comment]
@gregorycox what did you to do disable it?

**Comment by petewall** [comment]
```
clusterMetrics:
  windows-exporter:
    enabled: false
    deploy: false
```
