### ISSUE TITLE
Missing Label when using OTLP Destination

### ISSUE THREAD

**Issue by AchimGrolimund** [grafana/k8s-monitoring-helm#1404]
We have switched to the OTLP destination, but since then we no longer see any events in the Kubernetes tab. in the Explorer, however, the events are still visible as logs.

Now we have found out from the support case (177817) that it is due to a missing label.

`job=“integrations/kubernetes/eventhandler”`

For me, I would expect that if I change the destination to OTLP, the Helmchart itself inserts this adjustment based on checks without the customer having to add additional extra configuration in the Healm chart (values.yaml), which is also not documented how to do it and what exactly you have to define where.

Best Regards Achim

Config:

```yaml

global:
  platform: openshift

cluster:
  name: rosa-eng

destinations:
  - name: otlp-gateway
    type: otlp
    url: https://xxxxxxx.cloud
    tls:
      insecureSkipVerify: true
    protocol: http
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: otlp-secret
      namespace: grafana-poc
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}

clusterMetrics:
  enabled: true
  node-exporter:
    enabled: true
    deploy: false
    namespace: openshift-monitoring
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    service:
      scheme: https
      portName: https
  kube-state-metrics:
    enabled: true
    deploy: false
    namespace: openshift-monitoring
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    service:
      scheme: https
      portName: https-main
  windows-exporter:
    deploy: false
    enabled: false

clusterEvents:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: false
      port: 9411
  connectors:
    grafanaCloudMetrics:
      enabled: true

integrations:
  alloy:
    instances:
      - name: alloy
        labelSelectors:
          app.kubernetes.io/name:
            - alloy-metrics
            - alloy-singleton
            - alloy-receiver

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP

```
