### ISSUE TITLE
[feature-cluster-metrics] labelSelector is not working as expected

### ISSUE THREAD

**Issue by avantasia1975** [grafana/k8s-monitoring-helm#1406]
We have node-exporters deployed by default with a label like
`app=node-exporter` 
So i added this to the values file
```
  node-exporter:
    deploy: false
    jobLabel: "node_exporter"
    labelMatchers:
      app: node-exporter
    namespace: kube-system
```
Unfortunantely not only this selector is used but also the "default" one is merged into it like
```
      // Node Exporter
      discovery.kubernetes "node_exporter" {
        role = "pod"

        selectors {
          role = "pod"
          label = "app=node-exporter,app.kubernetes.io/name=node-exporter"
        }
        namespaces {
          names = ["kube-system"]
        }
      }
```
So the job is not working

I fixed this for myself by changing the template _node_exporter.alloy.tpl like 
```
{{- if (index .Values "node-exporter").labelMatchers }}
  {{- range $label, $value := (index .Values "node-exporter").labelMatchers }}
    {{- $labelSelectors = append $labelSelectors (printf "%s=%s" $label $value) }}
  {{- end }}
{{- else }}
   {{- $labelSelectors = append $labelSelectors (printf "app.kubernetes.io/name=node-exporter") }}
{{- end }}
```
And set the default value in the values.yaml to 
```
  # -- Labels used to select the Node Exporter pods.
  # @section -- Node Exporter
  labelMatchers: {}
  #  app.kubernetes.io/name: node-exporter
```
This isnt very professional i guess so i do not create a pull request :D 

I was searching for a way to overwrite or deleting the existing value but only found things to set the value to Null which not helps. 

Is there a way to just overwrite the existing value? 

Kind regards
Andi

**Comment by petewall** [comment]
Try with this:
```
  node-exporter:
    deploy: false
    jobLabel: "node_exporter"
    labelMatchers:
      app: node-exporter
	  app.kubernetes.io/name: null
    namespace: kube-system
```
