### ISSUE TITLE
Pod logs of pods in namespace kube-system missing with gatherMethod: volumes

### ISSUE THREAD

**Issue by spimmer** [grafana/k8s-monitoring-helm#1415]
I want to use the Grafana K8s Monitoring Helm Chart to collect all pod logs as well as node logs from my RKE2 cluster. However, when I use `gatherMethod: volumes`, the logs of all pods in the kube-system namespace are missing. When I change to `gatherMethod: kubernetesApi` and configure all other requirements, such as disabling node logs, the logs of pods in the kube-system namespace are collected. But in this case, I do not have the node logs and I want all pod logs **and** node logs.

My `values.yaml` looks as follows:
```yaml
cluster:
  name: clustername
global:
  scrapeInterval: 30s
destinations:
  - name: central-mimir
    type: prometheus
    url: http://mimir-gateway.mimir.svc:80/api/v1/push
    extraHeaders:
      X-Scope-OrgID: clustername
  - name: central-loki
    type: loki
    url: http://loki-gateway.loki.svc:80/loki/api/v1/push
    extraHeaders:
      X-Scope-OrgID: clustername
clusterEvents:
  enabled: true
nodeLogs:
  enabled: true
podLogs:
  enabled: true
integrations:
  alloy:
    instances:
      - name: alloy-metrics
        labelSelectors:
          app.kubernetes.io/name: alloy-metrics
      - name: alloy-singleton
        labelSelectors:
          app.kubernetes.io/name: alloy-singleton
      - name: alloy-logs
        labelSelectors:
          app.kubernetes.io/name: alloy-logs
  loki:
    instances:
      - name: loki
        labelSelectors:
          app.kubernetes.io/name: loki
  mimir:
    instances:
      - name: mimir
        labelSelectors:
          app.kubernetes.io/name: mimir
alloy-metrics:
  enabled: true
  alloy:
    extraArgs:
      - --disable-reporting
alloy-singleton:
  enabled: true
  alloy:
    extraArgs:
      - --disable-reporting
alloy-logs:
  enabled: true
  alloy:
    clustering:
      enabled: true
    extraArgs:
      - --disable-reporting
    mounts:
      dockercontainers: false
```

Thanks a lot for any advises!
