### ISSUE TITLE
When traces enabled, offer to create a named service that proxies to the Grafana Agent

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#142]
Enabling traces makes the Agent behave as a trace receiver, meaning other applications send their trace data to the agent, which then forwards that to Tempo. That means that each of those applications need to provide an OTLP Host parameter. Currently, the agent deployed by this chart will have a service accessible at: `<chart release name>-grafana-agent.<namespace>.svc.cluster.local:4317`.

So, it's dependent on the chart name and namespace.

The chart could also create a service (when traces are enabled), with a specified name, that would proxy to the grafana agent. That way, applications could be defined once and the chart could deploy the service that they are targeting.

Potential changes to values.yaml:
```yaml
traces:
  enabled: true
  service:
    create: true
    name: otlp-collector
    namespace: default
```

Will create:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: otlp-collector
  namespace: default
spec:
  type: ExternalName
  externalName: k8smon-grafana-agent.monitoring.svc.cluster.local
  ports:
  - port: 4317
  - port: 4318
```

**Comment by hedss** [comment]
I like this a lot, but do we want to be explicit on the service ports? Config for the Agent is very specific on which trace protocols to receive, and opening both gRPC and HTTP explicitly seems a bit contrary to that.

**Comment by danstadler-pdx** [comment]
I have been looking for an easy way to use Helm to drop in the Grafana Agent in place of the Otel Collector, in the Otel Demo project (https://opentelemetry.io/docs/demo/architecture/) - and in that demo both gRPC and HTTP are enabled. I relayed that in my request to Pete, that may be a reason why they're both being specified here.

**Comment by hedss** [comment]
OK, but we shouldn't be making major changes to components just to satisfy the OTel demo, I would have thought. This still really feels like you need to select which protocols you want. What happens when we want to demo something that still relies on Jaeger, for example?

**Comment by rknightion** [comment]
I guess it depends on how "easy" you want said demoing to be. 

We use Jaeger exclusively. To get that working on the agent we added

```
    extraPorts:
      - name: "jaeger-compact"
        port: 6831
        targetPort: 6831
        protocol: "UDP"
```
To grafana-agent.agent and then added

```
  otelcol.receiver.jaeger "default" {
    protocols {
      thrift_compact {
        endpoint = "0.0.0.0:6831"
      }
    }
    output {
      traces = [otelcol.processor.batch.trace_batch_processor.input]
      }
```
To the extraConfig and then point our apps to send all traffic to grafana-agent service.

Having the chart set up the batch processor input was helpful although it does mean we've got an OTel receiver that'll never get used. 

It makes me wonder if there's a "core" tracing featureset that should get set up when traces.enabled=true but then tweak the receiver. options to support more customisation or even disabling the receiver all together but have the processor.
If that's there as a base then users can easily add the extraConfig to suit their needs without the chart needing to be able to accommodate X number of configs while still being able to opt into a "recommended" setup for those new to tracing or migrating to tempo (which is what I think the current OTel setup in the chart provides).
