### ISSUE TITLE
v2.0.25 broke Authentication with Pre-existing Secrets

### ISSUE THREAD

**Issue by pschiffe** [grafana/k8s-monitoring-helm#1441]
The config:
```yaml
    destinations:
      - name: lgtmxMetrics
        type: prometheus
        url: xxx
        extraLabels:
          env: "${ENVIRONMENT}"
        auth:
          type: basic
        secret:
          create: false
          name: lgtmx-secret
          namespace: k8s-monitoring
```

Doesn't work anymore, it errors out with:
```
Error: /etc/alloy/config.alloy:1195:39: component "remote.kubernetes.secret.lgtmxmetrics.data" does not exist or is out of scope
1194 |     basic_auth {
1195 |       username = convert.nonsensitive(remote.kubernetes.secret.lgtmxmetrics.data["username"])
     |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1196 |       password = remote.kubernetes.secret.lgtmxmetrics.data["password"]
```

Because this snippet is missing in the config file:
```
remote.kubernetes.secret "lgtmxmetrics" {
  name      = "lgtmx-secret"
  namespace = "k8s-monitoring"
}
```

v2.0.24 is working fine.
