### ISSUE TITLE
Support for stage.geoip in loki.process

### ISSUE THREAD

**Issue by pschiffe** [grafana/k8s-monitoring-helm#1442]
Hello, is there a way how to utilize [stage.geoip](https://grafana.com/docs/alloy/latest/reference/components/loki/loki.process/#stagegeoip) in loki.process in this helm? It needs Maxmind DB file, which should be periodically updated.

**Comment by petewall** [comment]
You can add additional log stages with `podLogs.extraLogProcessingStages`. Here's an example that uses it:
https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/extra-rules

**Comment by pschiffe** [comment]
Nice, thank you @petewall. Maxmind or another geoip database is probably not included, right?

**Comment by petewall** [comment]
Not built-in, you'd have to volume mount it to the alloy container. Let me see if I can find a doc that might help.

**Comment by MattiasSegerdahl** [comment]
@pschiffe try something like this. It will initiate your alloy-logs deployment with a mount with a Maxmind GeoIP database (you will need to sign up for a key). And then use it in your podLogs. In this example {container="web-gateway"} and extract a value for ip=x.x.x.x and use it.

```
alloy-logs:
  enabled: true
  alloy:
    stabilityLevel: public-preview
    mounts:
      extra: 
        - name: geoip
          mountPath: /geoip
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        value: "<YOUR_GRAFANA_CLOUD_API_KEY>"
    controller:
      volumes:
        extra:
          - name: geoip
            emptyDir: {}
      initContainers:
      - name: geoip-init
        image: curlimages/curl:7.85.0
        command: ['sh', '-c']
        args:
          - |
            for i in {1..5}; do
              curl -o /geoip/GeoLite2-City.tar.gz -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=<YOUR_MAXMIND_LICENSE_KEY>&suffix=tar.gz" && break || sleep 10;
            done && \
            tar -xzf /geoip/GeoLite2-City.tar.gz -C /geoip --strip-components=1 && \
            rm /geoip/GeoLite2-City.tar.gz
        volumeMounts:
          - name: geoip
            mountPath: /geoip

```

```
podLogs:
  enabled: true
  extraLogProcessingStages: |-
    stage.match {
      selector = "{container=\"web-gateway\"}"
      stage.logfmt {
        mapping = { "ip" = "" }
      }

      stage.geoip {
        source  = "ip"
        db      = "/geoip/GeoLite2-City.mmdb"
        db_type = "city"
      }
      stage.labels {
        values = {
          geoip_country_name       = "",
          geoip_country_code       = "",
          geoip_continent_name     = "",
          geoip_continent_code     = "",
        }
      }
    }
  labelsToKeep:["app_kubernetes_io_name","container","instance","job","level","namespace","pod","service_name","mynamespacelabel","cluster","k8s_cluster_name","geoip_city_name","geoip_country_name","geoip_country_code","geoip_continent_name","geoip_continent_code"]

```
