### ISSUE TITLE
[Question] - Whiteliste / blacklist Events

### ISSUE THREAD

**Issue by AchimGrolimund** [grafana/k8s-monitoring-helm#1447]
Hey all

is there a way to whitelist Events for the ClusterEvents Receiver?

actually it sends all Events and on huge Clusters this would be a massiv ammount of Data. Often Dev / DevOps are only intrestet in some Events.

It would be nice if something like this is posible:

```
clusterEvents:
  enabled: true
  allowedEventReasons:
    - Scheduled
    - BackOff
    - .....
```

Best Achim
