### ISSUE TITLE
v2: Destination name can lead to invalid Kubernetes secret name generated

### ISSUE THREAD

**Issue by julian-waibel** [grafana/k8s-monitoring-helm#1453]
Deploying this Helm chart in version `2.0.26` with the following `values.yaml` file:

```yaml
cluster:
  name: my-cluster

destinations:
  - name: this_destination_will_break_k8s_secret_naming_convention
    type: otlp
    url: https://example.com
    auth:
      type: basic
      username: my-user
      password: my-password

clusterMetrics:
  enabled: true

alloy-metrics:
  enabled: true
```

will generate a `templates/destination_secret.yaml` file with following content:

```yaml
---
# Source: k8s-monitoring/templates/destination_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "this_destination_will_break_k8s_secret_naming_convention-k8s-mo"
  namespace: "k8s-monitoring"
type: Opaque
data:
  username: "bXktdXNlcg=="
  password: "bXktcGFzc3dvcmQ="
```

As can be seen the generated Kubernetes secret name is not valid and Kubernetes will throw an error like this:

```
Secret "xxx" is invalid: metadata.name:
          Invalid value: "xxx": a lowercase RFC 1123
          subdomain must consist of lower case alphanumeric characters, ''-'' or ''.'',
          and must start and end with an alphanumeric character (e.g. ''example.com'',
          regex used for validation is ''[a-z0-9[]([-a-z0-9[]*[a-z0-9[])?(\.[a-z0-9[]([-a-z0-9[]*[a-z0-9])?)*'')
```

I think either the destination name should be validated to not contain invalid characters or the Helm helper function that generates the Kubernetes secret name should take care of such a case:
https://github.com/grafana/k8s-monitoring-helm/blob/a7c5b2f46d8c5de148d644f11fdac3a676ca2adb/charts/k8s-monitoring/templates/secrets/_helpers.tpl#L166-L177

Thank you for your work!
