### ISSUE TITLE
v2: Using `podLogs.gatherMethod=kubernetesApi` triggers a validation error with a wrong hint and forgets to trigger an additional validation error

### ISSUE THREAD

**Issue by julian-waibel** [grafana/k8s-monitoring-helm#1472]
Deploying this Helm chart in version 2.0.26 with the following `values.yaml` file:

```yaml
cluster:
  name: my-cluster

destinations:
  - name: my-destination
    type: otlp
    url: https://example.com/otlp
    protocol: http
    auth:
      type: basic
      username: my-user
      password: my-password

podLogs:
  enabled: true
  destinations: [my-destination]
  gatherMethod: kubernetesApi

alloy-logs:
  enabled: true
```

triggers the following Helm chart validation error:

```
Error: execution error at (k8s-monitoring/templates/validations.yaml:1:4): 
Pod Logs feature should not mount /var/log when using the "kubernetesApi" gather method.
Please set:
alloy-logs:
  mounts:
    varlog: false
```

The validation error itself is correct (and a great idea from a security perspective). However the shown hint is wrong, because following the hint by setting:

```yaml
alloy-logs:
  enabled: true
  mounts:
    varlog: false
```

is not resolving the validation error. The Helm value that has to be set is nested within an `alloy` property. Meaning only this will fix it:

```yaml
alloy-logs:
  enabled: true
  alloy: # <-- Nested
    mounts:
      varlog: false
```

I think the validation error hint should be fixed.

Also note that a validation error is triggered if `alloy-logs.alloy.mounts.varlog` is enabled but no validation error is triggered if `alloy-logs.alloy.mounts.dockercontainers` remains enabled. Shouldn't this be validated the same way as `varlog`?

Thank you!
