### ISSUE TITLE
Support kube-state-metrics customResourceState

### ISSUE THREAD

**Issue by karlkeppner1** [grafana/k8s-monitoring-helm#1485]
Without support for customResourceState in the kube-state-metrics chart I cannot define custom metrics.

**Comment by petewall** [comment]
Anything you can define in the `kube-state-metrics` chart, you can define here, just inside the `clusterMetrics` feature:

```yaml
clusterMetrics:
  kube-state-metrics:
    customResourceState:
      enabled: true
      config:
        ...
```
