### ISSUE TITLE
Chart 2.0.26 trying to send pod logs to Prometheus destination

### ISSUE THREAD

**Issue by johnjeffers** [grafana/k8s-monitoring-helm#1491]
I upgraded today from 2.0.18 to 2.0.26, and it broke the alloy log pods. What appears to be happening is that it's trying to send logs to a Prometheus destination, whereas the previous version only sent logs to a Loki destination.

My `destinations` config looks something like this. The Prometheus destination is AWS Managed Prometheus, and therefore uses an AWS IAM role for authentication.
```
    - name: metricsService
      type: prometheus
      url: https://my-prometheus
      auth:
        type: sigv4
        sigv4:
          region: us-west-2
          roleArn: arn:aws:iam::123456789012:role/prom-writer
    - name: logsService
      type: loki
      url: https://my-loki
      secret:
        create: false
        name: loki-auth
        namespace: monitoring
      auth:
        type: basic
        usernameKey: LOKI_USERNAME
        passwordKey: LOKI_PASSWORD
```

With the following `podLogs` config:
```
  podLogs:
    enabled: true
    extraLogProcessingStages: |-
      stage.multiline {
        firstline = "^(\\d{4})\\-\\d{2}\\-\\d{2} \\d{2}:\\d{2}:\\d{2}.\\d{3} (AM|PM) ERROR"
      }
      stage.decolorize {}
```

In the previous version (2.0.18) the generated alloy-logs configmap would correctly contain only the Loki destination.

```
    // Destination: logsService (loki)
    otelcol.exporter.loki "logsservice" {
      forward_to = [loki.write.logsservice.receiver]
    }
```

However, in 2.0.26, the alloy-logs configmap contains destinations for both Loki and Prometheus.

```
    // Destination: metricsService (prometheus)
    otelcol.exporter.prometheus "metricsservice" {
      add_metric_suffixes = true
      forward_to = [prometheus.remote_write.metricsservice.receiver]
    }

    // Destination: logsService (loki)
    otelcol.exporter.loki "logsservice" {
      forward_to = [loki.write.logsservice.receiver]
    }
```

In my case, this causes the alloy log pods to crash-loop, because they are trying to authenticate to the AWS Managed Prometheus instance, which they have no permissions to do.

I did try adding `podLogs.destinations: [logsService]` to the values file, but this didn't make any difference to how the configmap was rendered.
