### ISSUE TITLE
Can't set custom valid transform statement for otlp destination, because quote function

### ISSUE THREAD

**Issue by jangaraj** [grafana/k8s-monitoring-helm#1505]
There is a problem to configure transformation statements for otlp destinations, because they are quoted:

For example:
https://github.com/grafana/k8s-monitoring-helm/blob/6305493c0245b19c71a54d1e74555515ac454eb8/charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl#L191C1-L191C37

Helm otlp destination config:
```
    processors:
      transform:
        logs:
          resource:
            -  '`delete_key(attributes, "mykey")`'
```
is rendered as incorrect statement:
```
      log_statements {
        context = "resource"
        statements = [
          `set(attributes["k8s.cluster.name"], "my-cluster")`,
          "`delete_key(attributes, \"mykey\")`",
        ]
      }
```

I think `quote` function shouldn't be used in those custom user logs/metric/trace statements.

**Comment by maxlemieux** [comment]
Hi @jangaraj thank you for this report. I've reproduced the issue, using the configuration provided here.

When I remove the `quote` function from the OTLP destination logs transform section of the template, using the following configuration in values.yaml (or with double quotes surrounding, and quotes on "mykey" escaped with \\):
```
    processors:
      transform:
        logs:
          resource:
            - '`delete_key(attributes, "mykey")`'
```
it renders the template successfully and installs/runs.

```
  log_statements {
    context = "resource"
    statements = [
      `set(attributes["cluster"], "maxlemieux-gke")`,
      `set(attributes["k8s.cluster.name"], "maxlemieux-gke")`,
      `delete_key(attributes, "mykey")`,
    ]
  }  
```

Branch with this change is here: https://github.com/maxlemieux/k8s-monitoring-helm/blob/maxlemieux/otlp-transform-syntax/charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl#L172

However, I'm not sure if there are edge cases that will make this fix invalid, or require updates in other similar areas. @petewall what do you think?

**Comment by petewall** [comment]
What's important to Alloy is that the entries to the `log_statements.statements` are a list of strings:
https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.processor.transform/#log_statements-block

That's why we quote the entry. The `quote` directive will ensure that it's treated as a string and not as raw alloy config.

Can you try this:
```
    processors:
      transform:
        logs:
          resource:
            -  delete_key(attributes, "mykey")
```

It'll quote that line and escape the embedded quotes.
