### ISSUE TITLE
Documentation for OpenCost tolerations

### ISSUE THREAD

**Issue by jonfairbanks** [grafana/k8s-monitoring-helm#1511]
Can you please update the tolerations [examples](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/tolerations) to include OpenCost?

Based on the open source chart for OpenCost, it appears that this should be set as `opencost.tolerations`. I've also seen references to this being set under `opencost.grafana.tolerations`. 

When setting either of these in the values.yaml file provided during Grafana onboarding, I still see that pod failing to schedule. 

Sample:
```
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    grafana:
      tolerations:
        - key: "CriticalAddonsOnly"
          value: ""
          operator: "Exists"
          effect: "NoSchedule"
```

Reference: https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml#L514
