### ISSUE TITLE
Unable to Provide Custom CA Certificate to Alloy for External TLS Destinations (Prometheus, Loki)

### ISSUE THREAD

**Issue by kpinarci** [grafana/k8s-monitoring-helm#1528]
Issue Description:

I’m encountering an issue when trying to send logs and metrics from Alloy to external Prometheus and Loki instances over TLS. Unless I set insecureSkipVerify: true in the destination configuration, I receive x509: certificate signed by unknown authority errors.

While disabling verification works, I would prefer to securely provide my custom CA certificate to the Alloy containers instead.

I’ve already created the certificate as a Kubernetes Secret, but I haven’t found a documented or elegant way to mount it into the alloy-* containers so that it’s used for TLS verification.

I would prefer to pass the custom CA certificate to the Alloy containers using the standard Helm options such as extraVolumes, extraVolumeMounts, and environment variables. However, these options don’t seem to be available for the Alloy components in the current values.yaml schema of the chart.

What I’ve Tried:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ca-certificate
  namespace: k8s-monitoring
type: Opaque
data:
  ca_certficate.crt: |
```

Alloy helm values.yaml
```yaml
---
cluster:
  name: mimir-meta-monitoring

destinations:
  - name: hostedLogs
    type: loki
    url: http://logs.example.de/loki/api/v1/push
    auth:
      type: basic
      username: "*********"
      password: "*********"
    tls:
      #caFile: "/etc/ssl/certs/ca_certificate.crt"
      insecureSkipVerify: false

  - name: hostedMetrics
    type: prometheus
    url: https://prometheus.example.de/api/v1/write
    auth:
      type: basic
      username: "*********"
      password: "*********"
    tls:
      #caFile: "/etc/ssl/certs/ca_certificate.crt"
      insecureSkipVerify: false

# Self-reporting creates a single metric and log that reports anonymized information about how this Helm chart was configured.
selfReporting:
  enabled: false

integrations:
  mimir:
    instances:
      - name: mimir
        namespaces:
          - mimir-prod
        labelSelectors:
          app.kubernetes.io/name: mimir
        logs:
          enabled: true

podLogs:
  enabled: true
  namespaces: 
    - mimir-prod
    - consul
    - k8s-monitoring

alloy-metrics:
  enabled: true
  alloy:
    extraVolumes:
      - name: ca-certificate
        secret:
          secretName: ca-certificate
    extraVolumeMounts:
      - name: ca-certificate
        mountPath: /etc/ssl/certs/ca_certificate.crt
        subPath: ca_certificate.crt
        readOnly: true
    env:
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/ca_certificate.crt

alloy-logs:
  enabled: true
  alloy:
    extraVolumes:
      - name: ca-certificate
        secret:
          secretName: ca-certificate
    extraVolumeMounts:
      - name: ca-certificate
        mountPath: /etc/ssl/certs/ca_certificate.crt
        subPath: ca_certificate.crt
        readOnly: true
    env:
      - name: SSL_CERT_FILE
        value: /etc/ssl/certs/ca_certificate.crt
```

**Comment by petewall** [comment]
What happens when you try this?

Using this aspect of the Alloy values:
* Extra volume mounts: https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml#L108-L110
* Extra volumes: https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml#L364-L366

```yaml
---
cluster:
  name: mimir-meta-monitoring

destinations:
  - name: hostedLogs
    type: loki
    url: http://logs.example.de/loki/api/v1/push
    auth:
      type: basic
      username: "*********"
      password: "*********"
    tls:
      caFile: "/etc/ssl/certs/ca_certificate.crt"
      insecureSkipVerify: false

...

alloy-metrics:
  enabled: true
  alloy:
    mounts:
      extra:
        - name: ca-certificate
          mountPath: /etc/ssl/certs/ca_certificate.crt
          subPath: ca_certificate.crt
          readOnly: true
  controller:
    volumes:
      extra:
        - name: ca-certificate
          secret:
            secretName: ca-certificate
...
```
