### ISSUE TITLE
Multiple integrations with metrics tuning could copy

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1531]
With this integrations feature:
```yaml
integrations:
  cert-manager:
    instances:
      - name: cert-manager
        namespace: cert-manager
        labelSelectors:
          app.kubernetes.io/name: cert-manager

  mysql:
    instances:
      - name: mysql-cluster
        exporter:
          enabled: true
          dataSourceName: "grafana:REDACTED@(mysql-cluster-router.mysql-cluster:3306)/"
          collectors:
            - perf_schema.replication_group_members

        logs:
          enabled: true
          labelSelectors:
            app.kubernetes.io/component: mysql

        metrics:
          tuning:
            excludeMetrics: [mysql_exporter_collector_duration_seconds, mysql_exporter_collector_success]
```

the metrics tuning on mysql is copied to the cert-manager metrics tuning.
