### ISSUE TITLE
v2: Consider changing the `destinations` Helm value type from list to map

### ISSUE THREAD

**Issue by julian-waibel** [grafana/k8s-monitoring-helm#1534]
Currently, destinations are defined as list items within Helm value `destinations`, e.g.:

```yaml
destinations:
  - name: hostedMetrics
    type: prometheus
    ...
  - name: hostedLogs
    type: loki
    ...
```

I use GitOps via Argo CD to deploy the `grafana/k8s-monitoring` Helm chart to multiple clusters. I have the use case that I want to use the same defined destination for all clusters (through a shared `values.yaml` file) but for some edge location clusters I need to be able to override / set the `proxyURL` within this defined destination (a cluster specific `values.yaml` file gets applied in addition to the shared `values.yaml` file).

Overriding a value which is a collection within Helm is very easy if the type is of map. But not easy if the type is of list.

E.g. for above example I would need to pass `--set destinations[1].proxyURL` in order to set the proxy URL for the `hostedLogs` destination. And doing it via an additional cluster-specific `values.yaml` file is not possible at all as lists get overwritten, not merged, see https://stackoverflow.com/a/59430330.

While if `destinations` would be of type map, I could just create a cluster-specific `values.yaml` file with the following content, while maintaining all other destination related config shared by all clusters within the shared `values.yaml` file:

```yaml
# values.yaml file shared across all clusters
destinations:
  hostedLogs:
    type: loki
    url: https://my-url.com
    ...

# values.yaml file for a specific edge cluster, where a proxy needs to be defined but all other config is the same
destinations:
  hostedLogs:
    proxyURL: xxx
```

and also the Helm `set` command would be more clear and not prone to index changes of list elements: `--set destinations.hostedLogs.proxyURL`.

This is also what the [Helm Docs: Values: Consider How Users Will Use Your Values](https://helm.sh/docs/chart_best_practices/values/#consider-how-users-will-use-your-values) recommend:
> the first guidelines for writing your values.yaml file is make it easy to override from --set.
> For this reason, it's often better to structure your values file using maps.

According to the docs, every grafana/k8s-monitoring destination needs to have a name defined, so the destination name is a great candidate to function as a map key.

I know that this change might break things or is not desirable due to other reasons. I just wanted to share my use case and opinion.

Thank you!
