### ISSUE TITLE
Missing auto-instrumentation generated metrics

### ISSUE THREAD

**Issue by ampc** [grafana/k8s-monitoring-helm#1545]
Hello, I upgraded from chart v1 to v2 and noticed the Beyla generated metrics stopped reaching Mimir.
With live-debugging I can see them in alloy (they're in OTEL format).

In the previous version I was using Beyla independent chart with these destinations:
```yaml 
otel_traces_export:
  endpoint: http://monitoring-k8s-monitoring-alloy.monitoring.svc.cluster.local:4317
  instrumentations: ["http"]
otel_metrics_export:
  endpoint: http://monitoring-k8s-monitoring-alloy.monitoring.svc.cluster.local:4317
  instrumentations: ["http"]
```
Current chart values:
```yaml
values:
  cluster:
    name: REDACTED
  destinations:
    - name: metricsService
      type: prometheus
      url: http://REDACTED.monitoring/mimir/api/v1/push
      secret:
        create: false
        name: mimir-auth-secret
        namespace: monitoring
      tenantIdKey: mimir-tenant-id
      auth:
        type: basic
        usernameKey: username
        passwordKey: password
    - name: logsService
      type: loki
      url: http://REDACTED.monitoring/loki/
      secret:
        create: false
        name: mimir-auth-secret
        namespace: monitoring
      tenantIdKey: loki-tenant-id
      auth:
        type: basic
        usernameKey: loki-auth-username
        passwordKey: loki-auth-password
    - name: tracesService
      type: otlp
      protocol: http
      url: http://REDACTED.monitoring/tempo
      metrics:
        enabled: false
      logs:
        enabled: false
      traces:
        enabled: true
      secret:
        create: false
        name: mimir-auth-secret
        namespace: monitoring
      tenantIdKey: tempo-tenant-id
      auth:
        type: basic
        usernameKey: tempo-auth-username
        passwordKey: tempo-auth-password
  clusterMetrics:
    enabled: true
    kube-state-metrics:
      podAnnotations:
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"
      deploy: true
  alloy-metrics:
    enabled: true
    liveDebugging:
      enabled: true
    alloy:
      mounts:
        extra:
          - name: secrets-store-inline
            mountPath: /mnt/secrets-store
            readOnly: true
    controller:
      podAnnotations: 
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"
      priorityClassName: high-priority
      volumes:
        extra:
          - name: secrets-store-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: mimir-secret-provider-class
  clusterEvents:
    enabled: true
  alloy-singleton:
    liveDebugging:
      enabled: true
    controller:
      podAnnotations: 
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"
    enabled: true
  podLogs:
    enabled: true
    gatherMethod: volumes
    collector: alloy-logs
    namespaces:
      - flux-system
  alloy-logs:
    liveDebugging:
      enabled: true
    controller:
      podAnnotations: 
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"
      priorityClassName: high-priority
    enabled: true
  autoInstrumentation:
    enabled: true
    beyla:
      image:
        tag: "2.2.2"
      config:
        data:
          filter:
            application:
              url_path:
                not_match: "{/.internal/v1/health/self,/grpc.health.v1.Health/Check,/_healthz,/Contrast/*,/contrastassess/*}"
          otel_metrics_export:
            enabled: true
            endpoint: http://monitoring-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4317
          otel_traces_export:
            enabled: true
            endpoint: http://monitoring-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4317
            instrumentations: ["http", "sql"]
            sampler:
              name: "traceidratio"
              arg: "0.05"
          attributes:
            kubernetes:
              enable: true
          routes:
            unmatched: heuristic
          ebpf:
            track_request_headers: true
            context_propagation: "all"
          discovery:
            exclude_otel_instrumented_services: true
            services:
              - open_ports: "80,443,8000-9999"
                k8s_namespace: "^(REDACTED|REDACTED)$"
  applicationObservability:
    enabled: true
    metrics:
      transforms:
        datapoint:
        - set(attributes["service_name"], resource.attributes["service.name"])
    receivers:
      otlp:
        grpc:
          enabled: true
    connectors:
      spanMetrics:
        enabled: true
        events:
          enabled: true
        exemplars:
          enabled: true
  alloy-receiver:
    enabled: true
    liveDebugging:
      enabled: true
    alloy:
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
    controller:
      podAnnotations: 
        kubernetes.azure.com/set-kube-service-host-fqdn: "true"
      priorityClassName: high-priority
  annotationAutodiscovery:
    enabled: true
  prometheusOperatorObjects:
    enabled: true
    crds:
      deploy: true
    podMonitors:
      enabled: true
      namespaces:
        - monitoring
      scrapeInterval: 30s
  integrations:
    alloy:
      instances:
        - name: alloy
          labelSelectors:
            app.kubernetes.io/name:
              - alloy-metrics
              - alloy-singleton
              - alloy-logs
              - alloy-receiver
          metrics:
            tuning:
              useDefaultAllowList: true
              includeMetrics:
                - alloy_build_info

```
Chart version: 2.0.29
Beyla: 2.2.2
