### ISSUE TITLE
[ApplicationObservability] Invalid detector: kubernetesNode

### ISSUE THREAD

**Issue by fculpo** [grafana/k8s-monitoring-helm#1557]
Enabling kubernetesNode resource detector in v2 chart, crashes alloy-receiver.

Logs:
```
Error: /etc/alloy/config.alloy:36:3: Failed to build component: decoding configuration: invalid detector: kubernetesNode

|     // Resource Detection Processor
|     otelcol.processor.resourcedetection "default" {
|  ___^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
| |     detectors = ["env","kubernetesNode"]
| |     override = true
| |
| |     kubernetes_node {
| |       auth_type = "serviceAccount"
| |       node_from_env_var = "K8S_NODE_NAME"
| |     }
| |
| |     output {
| |       traces = [otelcol.processor.k8sattributes.default.input]
| |     }
| |   }
| |_^^^
|

{"ts":"2025-05-16T10:51:14.963185327Z","level":"error","msg":"failed to start reporter","err":"context canceled"}
Error: could not perform the initial load successfully
```

Should be `detectors = ["env","kubernetes_node"]` cf. https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.processor.resourcedetection/#kubernetes_node

Example values.yaml:

```yaml
...
applicationObservability:
  enabled: true
  logs:
    enabled: false
  metrics:
    enabled: false
  processors:
    resourceDetection:
      kubernetesNode:
        enabled: true
```
