### ISSUE TITLE
Add dnsConfig support in k8smonitoring Helm chart

### ISSUE THREAD

**Issue by ukatru** [grafana/k8s-monitoring-helm#1565]
Enhancement Request
Please add support for specifying dnsConfig in the k8smonitoring Helm chart, to allow users to customize the DNS settings for the deployed pods.

Proposal
Introduce an optional dnsConfig section in the values.yaml file, which will be passed directly to the pod spec. For example:

```
dnsConfig:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8
  searches:
    - my.custom.domain
```
