### ISSUE TITLE
[2.1/2.0] Incorrect selectorLabels for extraService

### ISSUE THREAD

**Issue by marcinmigda-spoton** [grafana/k8s-monitoring-helm#1571]
I want to define extraService for alloy-receiver, i.e.:

```
alloy-receiver:
  enabled: true
  extraService:
    enabled: true
    name: alloy-cluster
```

and selector for new service should look like this:
```
app.kubernetes.io/instance=grafana-k8s-monitoring-alloy-receiver,app.kubernetes.io/name=alloy-receiver
```

however because of this default selectorLabels (https://github.com/grafana/k8s-monitoring-helm/blob/a27323188147ba935876154db3e6e66785c99d81/charts/k8s-monitoring/templates/collectors/_collector_helpers.tpl#L84)
new service is deployed with selector labels like this:
```
app.kubernetes.io/instance=grafana-k8s-monitoring,app.kubernetes.io/name=grafana-k8s-monitoring-alloy-receiver
```

Which is incorrect and causes new service to not include any pods that it supposed to.
