### ISSUE TITLE
[Tail Sampling] Remote K8s secret reference not included in config

### ISSUE THREAD

**Issue by bradleypettit** [grafana/k8s-monitoring-helm#1581]
When the new tail sampling processor is enabled, the `remote.kubernetes.secret` component is not included in the config for the Alloy instances responsible for sampling.

Using chart version 2.1.1, and a destination defined like this:

```
  - name: otlp
    type: otlp
    url: https://otlp-gateway-prod-au-southeast-0.grafana.net/otlp
    protocol: http
    auth:
      type: basic
      usernameKey: grafanaCloudOtlpGatewayUsername
      passwordKey: grafanaCloudToken
    metrics: { enabled: true }
    logs:    { enabled: true }
    traces:  { enabled: true }
    secret:
      create: false
      name: k8s-monitoring-credentials
      namespace: k8s-monitoring-v2
    processors:
      tailSampling:
        enabled: true
        policies:
        - name: latency-policy
          type: latency
          threshold_ms: 5000
```

The sampler-alloy pods will crashloop with errors like:
```
/etc/alloy/config.alloy:51:17: component "remote.kubernetes.secret.otlp.data" does not exist or is out of scope
```
