### ISSUE TITLE
Upgrade k8s-monitoring 2.0.30 -> 2.1.3 breaks pod label and breaks on using servicemonitors/hpa

### ISSUE THREAD

**Issue by stefanandres** [grafana/k8s-monitoring-helm#1587]
Hey,
we've just tried to upgrade from 2.0.30 to 2.1.3 and are seeing the following issues:

## Failing on ServiceMonitor and HPA

```
monitoring-dev-alloy-operator-7b87b999c-4nf4g alloy-operator {"level":"error","ts":"2025-05-22T11:09:48Z","msg":"Reconciler error","controller":"alloy-controller","object":{"name":"monitoring-dev-alloy-metrics","namespace":"monitoring-dev"},"namespace":"monitoring-dev","name":"monitoring-dev-alloy-metrics","reconcileID":"4fcdf93f-8c46-4cdf-82c6-ddfb9e473006","error":"failed to install release: Unable to continue with install: could not get information about the resource HorizontalPodAutoscaler \"monitoring-dev-alloy-metrics\" in namespace \"monitoring-dev\": horizontalpodautoscalers.autoscaling \"monitoring-dev-alloy-metrics\" is forbidden: User \"system:serviceaccount:monitoring-dev:monitoring-dev-alloy-operator\" cannot get resource \"horizontalpodautoscalers\" in API group \"autoscaling\" in the namespace \"monitoring-dev\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224"}
monitoring-dev-alloy-operator-7b87b999c-4nf4g alloy-operator {"level":"error","ts":"2025-05-22T11:10:18Z","msg":"Reconciler error","controller":"alloy-controller","object":{"name":"monitoring-dev-alloy-singleton","namespace":"monitoring-dev"},"namespace":"monitoring-dev","name":"monitoring-dev-alloy-singleton","reconcileID":"c8f0dac0-3349-4422-9390-c151edd1b34f","error":"failed to install release: Unable to continue with install: could not get information about the resource ServiceMonitor \"monitoring-dev-alloy-singleton\" in namespace \"monitoring-dev\": servicemonitors.monitoring.coreos.com \"monitoring-dev-alloy-singleton\" is forbidden: User \"system:serviceaccount:monitoring-dev:monitoring-dev-alloy-operator\" cannot get resource \"servicemonitors\" in API group \"monitoring.coreos.com\" in the namespace \"monitoring-dev\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.7/pkg/internal/controller/controller.go:224"}
```

This probably caused because we use ServiceMonitors and HPAs for the individually alloy deployments/ds

e.g.
```
alloy-metrics:
  enabled: true
  alloy:
[...]
  controller:
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetMemoryUtilizationPercentage: 150

  serviceMonitor:
    enabled: true
  liveDebugging:
    enabled: true
```

We are using the ServiceMonitors to be able to easily get the benefit of the existing upstream mixin that configures alert rules and dashboards for all alloy instances. -> https://github.com/grafana/alloy/tree/main/operations/alloy-mixin

### Workaround

It seems it is simply missing the proper permissions. Those can be added as extraObjects, but that really is a workaround that should be build in some component of this deployment chain. Probably in https://github.com/grafana/alloy-operator/blob/f9cb6cf3d53bf2eaac71da7f3dc5a48f1f18d93c/charts/alloy-operator/templates/rbac.yaml

```
extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: monitoring-dev-alloy-operator-rolebinding-manual
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: monitoring-dev-alloy-operator-role-manual
    subjects:
      - kind: ServiceAccount
        name: monitoring-dev-alloy-operator
        namespace: monitoring-dev
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: monitoring-dev-alloy-operator-role-manual
    rules:
      - apiGroups: ["autoscaling"]
        resources: ["horizontalpodautoscalers"]
        verbs: ["get", "create", "list", "watch"]
      - apiGroups: ["monitoring.coreos.com"]
        resources: ["servicemonitors"]
        verbs: ["get", "create", "list", "watch"]
```

## Missing pod label

I saw in the diff

![Image](https://github.com/user-attachments/assets/d240d01d-67fb-4e3a-b1c8-c1ca885e3462)
that some logic changed around pod labels and the result is that the pod label is just simply missing. That is a very important label and I did not find a workaround to get that back yet. Any help would be appreciated here again.

With 2.0.30:
![Image](https://github.com/user-attachments/assets/7b90d941-bd40-4de8-a811-988829fb2d98)

With 2.1.3:
![Image](https://github.com/user-attachments/assets/63f8a3f8-b391-4e41-8f46-b87fd3e7eb56)

(screenshot taken on different alloy setups, that is why the timestamps are not in logical order)

## Additional unrelated feedback
Overall, I know this is not the place, but we really feel like the k8s-monitoring chart abstraction goes too far right now.
We were very very happy(!) in the beginning (with the v1 chart) where it was a more or less simple abstraction for the values of the alloy helm chart.
We had multiple breaking bugs where we lost labels or had to do manually value migrations in minor and major updates of the chart. Especially the v1 -> v2 migration took multiple days of finding the correct combination of values, even with the migration tool (that was broken for our config).
I don't really see a good reason for this massive amount of abstraction this chart is doing. It is pretty hard to find out any possible configuration you can do and how to do that.
It's also pretty funny that we now do:
* k8s-monitoring chart -> alloy-operator helm chart -> alloy operator USES HELM to install the alloy chart again

We are seriously considering switching back to the vanilla alloy helm chart now. The constant breaking changes and the abstraction complexity is nothing I can explain to my colleagues. I don't want to be the only person in my team to be able to understand and possibly debug this deployment chain.

(I know this text reads probably very frustrated, because I am - I am sorry for posting this here, but it just fits context. I was very appreciative of the k8s-monitoring chart and the work done here - mostly by @petewall - until this started to create more work than it solved)

**Comment by petewall** [comment]
I'm bringing in a new release of alloy-operator that'll fix the HPA and ServiceMonitor creation.

Thank you for your comments. I appreciate how you've been a part of this journey for a long time. We've had four-ish major evolutions over the years:
1. 0.x -- early version 1.x: Kubernetes Infrastructure monitoring
2. later version 1.x: K8s infra on by default, lots of other functionality possible (traces, profiles, beyla, etc...)
3. 2.0.x - Nothing on by default, opt-in model, refactored features around intent, rather than technologies
4. 2.1 - Dynamic alloy deployments

The move from v1.6 to v2.0 was monumental because it changed a lot of the idioms. The goal was to be less reliant on observability insider lingo and more welcoming for users that aren't already experts.

The move from v2.0 to v2.1 was also a significant update where we are using new tooling for deploying alloy. I hope to prove out the benefits for this more and more in the coming releases. It's already allowing us to do things we weren't capable of before: tail sampling. It also removes ~90% of the values file, which was mostly boiler-plate alloy configuration.

So, thank you for sharing your feelings. This is a massively community-driven project and we truly want to make something that is delightful and enables you to be more productive, not less. My apologies for the recent breaking changes, I know there are some things to iron out with the new methods.

**Comment by petewall** [comment]
For reference, these are the fixes in alloy-operator:
* [HPAs](https://github.com/grafana/alloy-operator/commit/db8788992f8fadb2665f04d5b4698075e4766111)
* [ServiceMonitors](https://github.com/grafana/alloy-operator/commit/91f29e25047ad25ee6ca9685eba31416c5ce610c)

**Comment by petewall** [comment]
I'm discussing with some folks within Grafana about how to handle translating Loki-style logs with structured metadata into OpenTelemetry format and where they should belong.

Here's how I'm "disabling" structured metadata, knowing that i'll be translating to OTLP internally:
https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/tests/integration/prom-and-loki-to-otlp/values.yaml#L41-L65

In my experience, it's worth keeping loki as loki and otlp logs as otlp. Thankfully, you can define two destinations:
```yaml
destinations:
- name: loki
  type: loki
- name: otlp-logs
  type: otlp
  logs: { enabled: true }
```

The k8s-monitoring Helm chart is smart enough to keep send the loki style logs only to the loki destination, and the otlp style logs only to the otlp destination.

**Comment by stefanandres** [comment]
@petewall 
> Here's how I'm "disabling" structured metadata, knowing that i'll be translating to OTLP internally

Thanks for the context. So that reads to me like it should still work, but at least for our setup, the label is still just lost. 🤔 

We also don't override the podLogs.labelsToKeep key, so I am not sure why that would be.
The dev setup on which we try to upgrade has this configured:

```
  - name: logs_service
    type: loki
    url: http://loki-central-gateway.loki-central.svc.cluster.local/loki/api/v1/push
    secret:
      create: true
  - name: traces_service
    type: otlp
    protocol: http
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true
    url: http://tempo-central-gateway.tempo-central.svc.cluster.local:80
    secret:
      create: true
    tls: {}
```

Does your answer above imply that we should enable logs.enabled for the otlp destination as well? Respectively, do we need to define an additional otlp-logs destination?

I've added that, but I still don't the `pod` label

```
  - name: logs_service
    type: loki
    url: http://loki-central-gateway.loki-central.svc.cluster.local/loki/api/v1/push
    secret:
      create: true
  - name: otlp-logs
    type: loki
    url: http://loki-central-gateway.loki-central.svc.cluster.local/loki/api/v1/push
    secret:
      create: true
    logs:
      enabled: true
```

What could we be missing here?
