### ISSUE TITLE
Support Secret-based configuration for extraHeaders/extraHeadersFrom in OTLP destinations

### ISSUE THREAD

**Issue by bmenzel0** [grafana/k8s-monitoring-helm#1594]
Currently, the k8s-monitoring Helm chart (v2, Alloy-based) allows setting custom extraHeaders in destinations, e.g.:
`
destinations:
  - name: otlp-gateway
    type: otlp
    url: http://my-collector-server
    protocol: http
    auth:
      type: none
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}
    extraHeaders:
      ROUTING_KEY: aSecretToEveryone
`
This works fine for static values, but becomes problematic when we want to inject secrets, e.g., for authentication headers or API keys. AFAIK Helm itself does not support dynamic secret loading into values.yaml, and the current chart doesn't allow referencing Kubernetes Secrets via valueFrom, env, or volumeMounts to populate headers like extraHeaders.

We would like to see support for secret-based configuration of headers (especially extraHeaders and extraHeadersFrom) in the destination section.

Possible implementation ideas:

    Allow referencing a Kubernetes Secret by name and key:
    `
    extraHeadersFromSecret:
      name: otel-secret
      keys:
        ROUTING_KEY: password
    `

 Why it matters:
  
      Avoids storing sensitive values like OTLP auth keys directly in versioned values.yaml.
  
      Aligns with best practices for Kubernetes secret management.
  
      Was more feasible in previous (v1) versions of the chart, where components like Grafana Agent allowed envFromSecrets.

If such a feature or a suitable workaround exists, we’d appreciate it being made more visible in the documentation.

**Comment by petewall** [comment]
`extraHeadersFrom` lets you specify the value comes from any source, including secrets or environment variables.

## Using environment variables:

```
destinations:
- name: otlp-gateway
  type: otlp
  url: http://my-collector-server/
  protocol: http
  auth:
    type: none
  metrics: {enabled: true}
  logs: {enabled: true}
  traces: {enabled: true}
  extraHeadersFrom:
    ROUTING_KEY: sys.env("ROUTING_KEY")

alloy-receiver:
  alloy:
    envFrom:
      - secretRef:
        name: routing-secret  # Should have "ROUTING_KEY" defined
```

## Using secret components:
This loads the secret at runtime and does not have it persist as an environment variable.

```
destinations:
- name: otlp-gateway
  type: otlp
  url: http://my-collector-server/
  protocol: http
  auth:
    type: none
  metrics: {enabled: true}
  logs: {enabled: true}
  traces: {enabled: true}
  extraHeadersFrom:
    ROUTING_KEY: remote.kubernetes.secret.routing.data["ROUTING_KEY"]

alloy-receiver:
  extraConfig: |-
    remote.kubernetes.secret "routing" {
      name = "routing-secret"
      namespace = "default"
    }
```

**Comment by bmenzel0** [comment]
Yes, we tried this initially, but we encountered the following error every time:
```
Error: /etc/alloy/config.alloy:295:23: component "remote.kubernetes.secret.routing.data" does not exist or is out of scope

294 |     headers = {
295 |       "ROUTING_KEY" = remote.kubernetes.secret.routing.data["ROUTING_KEY"],
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
296 |     }
interrupt received
Error: could not perform the initial load successfully
```

It’s possible we did something wrong during the setup.

Here’s what we did:

  We created the secret:
  ```
  apiVersion: v1
  kind: Secret
  metadata:
   name: routing
   namespace: grafana
  type: Opaque
  data:
   ROUTING_KEY: MTIzNHNlY3JldDEyMzQ1
  
  ```

We created the values.yaml file:

  ```
  cluster:
    name: rke
  
  destinations:
    - name: otlp-gateway
      type: otlp
      url: http:/my-collector-server
      protocol: http
      auth:
        type: none
      metrics: {enabled: true}
      logs: {enabled: true}
      traces: {enabled: true}
      extraHeadersFrom:
        ROUTING_KEY: remote.kubernetes.secret.routing.data["ROUTING_KEY"]
  
  alloy-receiver:
    extraConfig: |-
      remote.kubernetes.secret "routing" {
        name = "routing"
        namespace = "grafana"
      }
  
  
  clusterMetrics:
    enabled: true
  
  podLogs:
    enabled: true
  
  alloy-metrics:
    enabled: true
  
  alloy-logs:
    enabled: true
  
  clusterEvents:
    enabled: true
  
  selfReporting:
    enabled: false
  
  alloy-singleton:
    enabled: true
  
  ```
Then we installed the Helm chart:
  helm upgrade --install --version ^2 --debug --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring --namespace "grafana" --values grafanak8sV2Secret-values.yaml
