### ISSUE TITLE
[Feature request] Overwrite node exporter label matcher

### ISSUE THREAD

**Issue by lupa95** [grafana/k8s-monitoring-helm#1597]
In some environments, the node exporter is already present and not installed by the k8s-monitoring Helm chart itself. In these situations you might have to configure `cluster-metrics.node-exporter.xxx` values to point Alloy config to the node exporter pods.

In such a case it would be very useful to exclusively customize the `clusterMetrics.node-exporter.labelMatchers`. The current implementation just appends whatever is set in this value to the default label `app.kubernetes.io/name":"node-exporter`.

Minimal example:
```yaml
clusterMetrics:
  enabled: true
  node-exporter:
    deploy: false
    labelMatchers:
      component: node-exporter
```

Helm diff current:
```
...
            role = "pod"
-           label = "app.kubernetes.io/name=node-exporter"
+           label = "app.kubernetes.io/name=node-exporter,component=node-exporter"
          }
...
```

Proposal:
```
...
            role = "pod"
-           label = "app.kubernetes.io/name=node-exporter"
+           label = "component=node-exporter"
          }
...
```
