### ISSUE TITLE
Update Proxies example with OpenCost

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1611]
The [proxies](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/proxies) example should be updated to show how to set proxy settings on the OpenCost exporter:

```
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        extraEnv:
          HTTP_PROXY: ...
          HTTPS_PROXY: ...
          NO_PROXY: ...
```
