### ISSUE TITLE
Pod Log refactoring

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#1614]
The current `podLogs` feature is getting to be a mess. The "gatherMethod" option means that you cannot combine them, it's either/or.

I think it's time to rethink how pod logs are gathered, adding extra options while removing complexity.

Something like this:

```yaml
podLogs: {} # deprecated

podLogsViaVolumes:
  # Capture ecosystem: loki / otlp
  # Choosing loki is essentially the podLogs feature
    # Add the ability to use https://grafana.com/docs/alloy/latest/reference/components/loki/loki.enrich/
  # Choosing otlp is essentially the podLogs with filelog gather method

podLogsViaAPI:
  # Essentially the podLogs feature with kubernetesAPI gather method

logReceivers:
  loki: # Enables receiving log data via loki api

    # Deploys a ClusterLogForwarder: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/logging/logging-6-2#log6x-clf-6-2
    openShiftClusterLogForwarder:
      enabled: true

  syslog: # Enables receiving log data via syslog
```

Validations would ensure that if both volumes and api are enabled at the same time, they're not targeting the same pods.

Add examples for:
* Using multiple log features at once.

Bonus would be to find a way to get logs from pods on Windows nodes with log volumes...
