### ISSUE TITLE
How do I perform an uninstall in version 2.1.x

### ISSUE THREAD

**Issue by mc2285** [grafana/k8s-monitoring-helm#1615]
Maybe I missed something but there does not seem to be any mention neither here nor on the Grafana website on how to do this properly and I am struggling to figure it out myself.

Should I remove the main Helm release first? Shall I uninstall the child ones?
Uninstalled the main Helm release and got stuck (dangling resources left even though it succeeded)

Shall I delete operator CRD's using the inverse (`delete` instead of `apply`) of what's mentioned [here](https://github.com/grafana/k8s-monitoring-helm/blob/a27323188147ba935876154db3e6e66785c99d81/charts/k8s-monitoring/README.md)?

Shall I delete the `alloys.collectors.grafana.com` objects?
They seem to stay even after uninstalling the child Helm releases. I guess I shouldn't have uninstalled them manually. The custom resources have finalisers and cannot be removed. Maybe the child Helm releases should not succeed uninstalling if they are to leave dangling resources?

Or maybe I missed an obvious way to do it. Still I think this way should get mentioned somewhere close to the information on how to install the chart so that people don't break their clusters trying to force-remove alloy resources.

Update:
I ended up removing the finalisers from `alloys.collectors.grafana.com` objects as the `Pods`, `Services` and `Clusterroles` they were supposed to manage were long gone anyway after the Helm uninstall. Afterwards I have been able to install chart `v2.0.30` successfully so I guess this way works. The point still stays though: `helm uninstall` should not report `succeeded` while leaking dangling resources and the intended way to uninstall shall be documented.

**Comment by sjethvani** [comment]
I tried doing helm uninstall k8s-monitoring chart 2.1.4 version yesterday. It took some time & was in `uninstall pending` state during that time. Checking may be after ~10 mins, I saw that helm chart & its other dependency sub-charts (like `alloy-logs` , `alloy-metrics` , `alloy-receiver`, `alloy-singleton`) were removed successfully . While this was going on (since it took 5/10 mins) , I was doing `helm ls` & was checking other subcharts spawned from k8s-monitoring (may be by `alloy-operator`) & was wondering to uninstall them but didn't do that . 
Also I noticed same about not having this `uninstall` process mentioned anywhere on doc. 

Also any reason why you went back from v2.1.x to v2.0.30 ?

**Comment by michaelPotter** [comment]
I've run into this a handful of times today as I've been PoCing this helm chart across several of our clusters. After a few times, the process I found that works best is to delete all `alloys.collectors.grafana.com` resources, then the helm uninstall will complete quickly.

**Comment by sjethvani** [comment]
I have also faced this issue when un installing & re deploying k8s-monitoring helm chart multiple times . Removing filanlizers from `alloy` resources (i.e `kubectl edit/patch alloy <alloyname>`) completes UN-installation process . 

Also one more observation . 
When doing this installation / un-installation (I am actually bundling all our common helm charts & one of them is this `k8s-monitoring` (sort of blueprint where grouping chats), tag that bleurpint (or group of charts), create release candidate version & deploys it on target cluster) , while doing so I noticed that sometimes `k8s-monitoring` helm chart's `alloy-operator` doesn't kick in installation process of other sub helm charts . In that case , doing `helm rollback <myk8smonitoringhelmchartreleasename> <samerevision>` makes `alloy-operator` to retry sub-chart installation process. Sharing here for awareness.

**Comment by Quiwy** [comment]
We're experiencing the same issue. We use Terraform to deploy this Helm chart, and since version 2.1, we've encountered problems during the `destroy` phase.

In some cases, we need to run `terraform destroy` multiple times. Other times, the `k8s-monitoring` helm chart is removed, but some of its child Helm charts remain undeleted.

**Comment by petewall** [comment]
Hey folks!

My theory is that the `kind: Alloy` objects are being deleted, but before the `alloy-operator` can resolve the removal, it itself is removed. I'll see if there are things I can do with helm hooks to stage things in the right order.

**Comment by Quiwy** [comment]
Hi @petewall, maintainers 👋,

Just a bump on this issue. We’re still facing the exact same blocking problem we reported earlier via Terraform deployments. Each time the Helm release ends up in a stuck state, forcing us to manually intervene or run the destroy pipeline again, which disrupts our CI/CD pipeline.

This is actively preventing progress across multiple environments and tools, and we'd highly appreciate any update on a fix or workaround:
- Any known root causes within the k8s-monitoring-helm setup (specifically with Terraform integration)?
- Are there any patches or upcoming releases addressing the stuck deployments?
- Is there a recommended automated mitigation (like secret cleanup, rollback strategies, or adjusted timeouts) to avoid these recurring blocks?

Thanks in advance for any help—this is a major blocker for us at the moment.

**Comment by charlesbalderson** [comment]
@Quiwy we're struggling with this as well, currently using this awful awful awful bodge. Would be good to get this fixed ASAP. 

```terraform
resource "null_resource" "bodgy" {
  triggers = {
    environment = var.environment_name
  }
  provisioner "local-exec" {
    when    = destroy
    command = <<-EOT
    aws eks update-kubeconfig --name ${self.triggers.environment}
    kubectl delete alloys --all --all-namespaces
    EOT
  }
  depends_on = [time_sleep.bodge_wait]
}

resource "time_sleep" "bodge_wait" {
  depends_on = [helm_release.alloy]

  destroy_duration = "30s"
}
```

**Comment by sicil1ano** [comment]
Same problem with v3.2.1. 

I recently installed k8s-monitoring chart v3.2.1 on my own AKS using Terraform and Helm.
I performed some tests and decided to uninstall the chart, using Terraform, by deleting the helm_release resource.

```
resource "helm_release" "grafana-k8s-monitoring" {
  name             = "grafana-k8s-monitoring"
  repository       = "https://grafana.github.io/helm-charts"
  chart            = "k8s-monitoring"
  version          = "3.2.1"
  namespace        = var.namespace
  create_namespace = true
  atomic           = true
  timeout          = 300

values = [file("${path.module}/values.yaml"), yamlencode(local.alloy_authentication_override)]

 // set values here...
}
```

Here my values.yaml:

```
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    auth:
      type: basic
      username: "dummy"
      password: "dummy"
  - name: grafana-cloud-logs
    type: loki
    auth:
      type: basic
      username: "dummy"
      password: "dummy"
clusterMetrics:
  enabled: true
  kube-state-metrics:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
clusterEvents:
  enabled: true
alloy-metrics:
  enabled: true
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: "${CLUSTER_NAME}"
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    auth:
      type: basic
      username: "dummy"
      password: "dummy"
alloy-singleton:
  enabled: true
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
            key: password
      - name: CLUSTER_NAME
        value: "${CLUSTER_NAME}"
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    auth:
      type: basic
      username: "dummy"
      password: "dummy"
```


Some components got removed, but others like grafana-k8s-monitoring-alloy-metrics and grafana-k8s-monitoring-alloy-singleton pods are NOT removed. Both pods are no longer working properly because they are looking for a secret that most likely has been removed.

Here are some events from the alloy metric pod (now crashing):

```
Warning  Failed       114s (x6 over 4m44s)   kubelet  Error: secret "alloy-metrics-remote-cfg-grafana-k8s-monitoring" not found 
Warning  FailedMount  102s (x10 over 5m52s)  kubelet  MountVolume.SetUp failed for volume "config" : configmap "grafana-k8s-monitoring-alloy-metrics" not found
```

and some from alloy singleton pod:

```
Normal   Created      27m                 kubelet            Created container: config-reloader                                                                                                             
Normal   Started      27m                 kubelet            Started container config-reloader                                                                                                             
Warning  FailedMount  69s (x14 over 13m)  kubelet            MountVolume.SetUp failed for volume "config" : configmap "grafana-k8s-monitoring-alloy-singleton" not found 
```

My suspicion is that secrets or other dependencies are removed first, but the pods cannot be removed any more because of dependencies no longer available.
Should the removal order should be changed, like removing the pods/deployments and then removing everything else?

I'm now left with Terraform state updated, without the helm_release in the state, but still pods/deployments of the chart still living on the cluster.
