### ISSUE TITLE
How to control naming of resources (like Podname , Roles , ServiceAccounts , ConfigMaps , ClusterRoles , RoleBinding, ClusterRolebings etc) created by k8s-monitoring helm chart? fullnameOverride ?

### ISSUE THREAD

**Issue by sjethvani** [grafana/k8s-monitoring-helm#1616]
Tl;dr : `k8s-monitoring` helm chart creates resources with namings like `release-name-alloy-operator` , `release-name-kube-state-metrics` etc . I want to override `release-name` with some custom name . I tried overriding `fullnameOverride` at different levels (i.e at parent chart/my umbrella chart/root level, at some chart i.e k8s-monitoring` level) , it is not working (I still see resources named with `release-name` prefix)

We have 3 grafana stacks named `stackdev` , `stackstage`, `stackprod` . Eash grafana stack will have multiple kubernetes clusters sending logs,metrics,traces data. (i.e dev,qa reporting to stackdev , stage to stackstage , all prod clusters to stackprod)

For each of these k8 clusters , I need to install this grafana k8s monitoring helm chart (Btw this is the same helm chart , which gets refered when clicking on grafanacloud site url <ourstack>.grafana.net -> Kubernetes -> Configuration -> Add new cluster , then helm command shows up refering this chart).

To make above things work , I am creating umbrella helm chart , putting this `k8s-monitoring-helm` as subchart . So my `Chart.yaml` looks like 

```
#my-grafana-k8s-monitoring/Chart.yaml
apiVersion: v2
name: my-grafana-k8s-monitoring
description: A Helm chart for Kubernetes
# A chart can be either an 'application' or a 'library' chart.
version: 2.1.4
appVersion: "2.1.4"
dependencies:
  - name: k8s-monitoring
    version: 2.1.4
    repository: https://grafana.github.io/helm-charts

```

```
#my-grafana-k8s-monitoring/Values.yaml
# Blank 
```

```
#my-grafana-k8s-monitoring/Values-override.yaml
fullnameOverride: grafa-cloud-overridename
k8s-monitoring:
  fullnameOverride: grafa-cloud-overridename
  cluster:
    name: my-cluster-name
  destinations:
    - name: grafana-cloud-metrics
      type: prometheus
      url: https://prometheus-<someidentifier>-<region>.grafana.net/api/prom/push
      auth:
        type: basic
        usernameKey: prometheus-username
        passwordKey: access-token
      secret:
        create: false
        name: grafanacloud-secrets  #existing k8 secret
    - name: grafana-cloud-logs
      type: loki
      url: https://logs-<someidentifier>-<region>.grafana.net/loki/api/v1/push
      auth:
        type: basic
        usernameKey: loki-username
        passwordKey: access-token
      secret:
        create: false
        name: grafanacloud-secrets     #existing k8 secret
-----------
----------
---------        
```

Helm packaing & templating test

```
cd my-grafana-k8s-monitoring
helm package . 
helm template grafanacloud-k8s-monitoring-samtest grafana-k8s-monitoring-2.1.4.tgz --debug -f Values-override.yaml

```

I see helm releases named with helm release name , which is fine

```
helm ls
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
grafanacloud-k8s-monitoring-samtest grafanacloudtest 2 2025-05-27 19:08:34.817059217 +0000 UTC deployed grafana-k8s-monitoring-2.1.4 2.1.4
grafanacloud-k8s-monitoring-samtest-alloy-logs grafanacloudtest 1 2025-05-27 19:05:28.870587489 +0000 UTC deployed alloy-1.0.3 v1.8.3
grafanacloud-k8s-monitoring-samtest-alloy-metrics grafanacloudtest 1 2025-05-27 19:05:28.959201995 +0000 UTC deployed alloy-1.0.3 v1.8.3
grafanacloud-k8s-monitoring-samtest-alloy-receiver grafanacloudtest 1 2025-05-27 19:05:28.872090244 +0000 UTC deployed alloy-1.0.3 v1.8.3
grafanacloud-k8s-monitoring-samtest-alloy-singleton grafanacloudtest 1 2025-05-27 19:05:28.870439186 +0000 UTC deployed alloy-1.0.3 v1.8.3
namespace-m1w4vvy-grafanacloudtest grafanacloudtest 1 2025-05-27 12:23:08.251928393 +0000 UTC deployed namespace-0.1.0 1.16.0
```

However , Pods , ServiceAccount etc are also named with release prefix . I was expecting `fullnameOverride` value prefix for them
```
──────────────────────────────────────── ✔  3s my-cluster-name/grafanacloudtest 󱃾  19:58:31
╰─ k get pods
NAME READY STATUS RESTARTS AGE
grafanacloud-k8s-monitoring-samtest-alloy-logs-4r9h2 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-logs-6gndv 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-logs-dppw8 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-logs-hp7fq 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-logs-jqct2 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-logs-nkjmf 2/2 Running 0 14h
grafanacloud-k8s-monitoring-samtest-alloy-metrics-0 2/2 Running 6 (19h ago) 19h
grafanacloud-k8s-monitoring-samtest-alloy-operator-bfcfb9dzwp4h 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-receiver-5tbml 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-receiver-bgctq 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-receiver-mqs4l 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-receiver-p6jxn 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-receiver-wdn4s 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-singleton-6fc9c8jblhs 2/2 Running 0 19h
grafanacloud-k8s-monitoring-samtest-kepler-76h24 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-kepler-l7khm 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-kepler-p5tbw 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-kepler-rckdx 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-kepler-rtdrk 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-kube-state-metrics-7ff5r9mm 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-node-exporter-gqcdq 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-node-exporter-jtbxx 1/1 Running 0 14h
grafanacloud-k8s-monitoring-samtest-node-exporter-n49gq 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-node-exporter-p5pjc 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-node-exporter-rz27h 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-node-exporter-v4c4h 1/1 Running 0 19h
grafanacloud-k8s-monitoring-samtest-opencost-78fb6c9b49-gllc7 1/1 Running 1 (11h ago) 19h

──────────────────────────────────────── ✔  3s my-grafana-k8s-monitoring/grafanacloudtest 󱃾  19:58:36
╰─ k get serviceaccounts
NAME SECRETS AGE
default 0 26h
grafanacloud-k8s-monitoring-samtest-alloy-logs 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-metrics 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-operator 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-receiver 0 19h
grafanacloud-k8s-monitoring-samtest-alloy-singleton 0 19h
grafanacloud-k8s-monitoring-samtest-kepler 0 19h
grafanacloud-k8s-monitoring-samtest-kube-state-metrics 0 19h
grafanacloud-k8s-monitoring-samtest-node-exporter 0 19h
grafanacloud-k8s-monitoring-samtest-opencost 0 19h
grafanacloud-k8s-monitoring-samtest-windows-exporter 0 19h

```

**Comment by petewall** [comment]
There isn't a global fullname override, so, try setting the `fullnameOverride` inside each of the deployment objects:

```
k8s-monitoring:
  clusterMetrics:
    kube-state-metrics:
      fullnameOverride: grafa-cloud-overridename
    node-exporter:
      fullnameOverride: grafa-cloud-overridename
    kepler:
      fullnameOverride: grafa-cloud-overridename
    opencost:
      fullnameOverride: grafa-cloud-overridename
  alloy-metrics:
    fullnameOverride: grafa-cloud-overridename
  alloy-singleton:
    fullnameOverride: grafa-cloud-overridename
  alloy-logs:
    fullnameOverride: grafa-cloud-overridename
  alloy-receiver:
    fullnameOverride: grafa-cloud-overridename
```

kube-state-metrics doesn't appear to al
