### ISSUE TITLE
podLogs.structuredMetadata doesn't work as expected when setting empty string.

### ISSUE THREAD

**Issue by ubarar-poolside** [grafana/k8s-monitoring-helm#1631]
When using the following yaml:

```yaml
podLogs:
  structuredMetadata:
    pod: helloworld
```

this is the diff from `k8s-monitoring-alloy-logs`:

```diff
+         // set the structured metadata values
+         stage.structured_metadata {
+           values = {
+             "pod" = "pod",
+           }
+         }
```

However, when setting empty string as follows:

```yaml
podLogs:
  structuredMetadata:
    pod: ""
```

The resulting diff is as follows:

```diff
+         // set the structured metadata values
+         stage.structured_metadata {
+           values = {
+             "pod" = "pod",
+           }
+         }
```

---

My end goal is to implement the changes that were made [here](https://github.com/grafana/k8s-monitoring-helm/pull/651/files#diff-885d02ab244319c99fb928f1a5694fa578d8b65364c422a066c316c1fae2380aR30-R35)
