### ISSUE TITLE
alloy-operator deployed in different namespace than serviceaccount

### ISSUE THREAD

**Issue by Darthmineboy** [grafana/k8s-monitoring-helm#1689]
When I install the k8s-monitoring chart in the meta namespace, the alloy-operator deployment is created in the default namespace but the serviceaccount is created in the meta namespace. The alloy-operator deployment then fails as the serviceaccount is not found in the default namespace.

The issue can be observed in the events.
```
4m58s       Warning   FailedCreate        replicaset/k8s-alloy-operator-7465cbd8c4   Error creating: pods "k8s-alloy-operator-7465cbd8c4-" is forbidden: error looking up service account default/k8s-alloy-operator: serviceaccount "k8s-alloy-operator" not found
```

As workaround I am now installing the chart in the default namespace.

Chart installed with Terraform:
```
resource "helm_release" "k8s" {
  chart = "k8s-monitoring"
  version = "2.1.4"
  name  = "k8s"
  repository = "https://grafana.github.io/helm-charts"
  namespace = "meta"
  create_namespace = true
  values = ["${file("k8s-monitoring-values.yml")}"]
}
```

Chart values:
```
---
cluster:
  name: monitoring

destinations:
  - name: loki
    type: loki
    url: http://loki:3100/loki/api/v1/push

clusterEvents:
  enabled: true
  collector: alloy-logs
  namespaces:
    - meta
    - test

nodeLogs:
  enabled: false

podLogs:
  enabled: true
  gatherMethod: kubernetesApi
  collector: alloy-logs
  labelsToKeep: ["app_kubernetes_io_name","container","instance","job","level","namespace","service_name","service_namespace","deployment_environment","deployment_environment_name"]
  structuredMetadata:
    pod: pod  # Set structured metadata "pod" from label "pod"
  namespaces:
    - meta
    - test

# Collectors
alloy-singleton:
  enabled: false

alloy-metrics:
  enabled: false

alloy-logs:
  enabled: true
  # Required when using the Kubernetes API to pod logs
  alloy:
    mounts:
      varlog: false
      dockercontainers: false
    clustering:
      enabled: true

alloy-profiles:
  enabled: false

alloy-receiver:
  enabled: false
```
