### ISSUE TITLE
Add more flexibility in label matching

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#17]
For example, Node Exporter always matches the label:
`app.kubernetes.io/name=promethus-node-exporter.*`

But on OpenShift, it's just `app.kubernetes.io/name=node-exporter`

Perhaps, each metric source could have a labelMatcher section with defaults like:

```yaml
metics:
  node-exporter:
    labelMatchers:
    - key: app.kubernetes.io/name
      value: node-exporter
```

but, it would need to be overridable...
