### ISSUE TITLE
Allow referencing existing secrets

### ISSUE THREAD

**Issue by thecodeassassin** [grafana/k8s-monitoring-helm#1719]
Hi,

The only way to currently pass Loki credentials is in plain-text. Which is unacceptable for us because our org does not allow plain text passwords in git.

```
  destinations:
  - name: loki
    type: loki
    url: https://loki/loki/api/v1/push
    tenant: "default"
    auth:
      type: basic
      existingSecret:
        name: loki-credentials
        usernameKey: loki-username
        passwordKey: loki-password

```

I would love to be able to refer to an existing secret instead of only being able to enter plain text username and passwords.
