### ISSUE TITLE
Should it be possible to use alongside separate helm-installed agent?

### ISSUE THREAD

**Issue by moxious** [grafana/k8s-monitoring-helm#178]
I'm installing this helm chart according to standard docs, that process flows fine for the purposes of configuring k8s o11y.  No issues there.

However, this install clashes with a separate install of agent that I was using for app o11y.   

Here is the immediate error which points out what's going on:

```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "open-telemetry" chart repository
...Successfully got an update from the "grafana" chart repository
Update Complete. ⎈Happy Helming!⎈
Release "grafana-k8s-monitoring" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "podlogs.monitoring.grafana.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "grafana-k8s-monitoring": current value is "agent"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "k8s-o11y": current value is "default"
```

This is correct, because prior to this step, I installed agent like so (for the purposes of experimenting with app o11y under a different config)

```
helm install agent grafana/grafana-agent --values agent/config.yaml
```

It seems these two configs are clashing though as indicated by the error message, despite agent being in the `default` namespace and grafana-k8s-monitoring being in the `k8s-o11y` namespace.

Exact install command is as follows:

```
. .env

kubectl create namespace k8s-o11y

helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "k8s-o11y" --create-namespace --values - <<EOF
cluster:
  name: "testy"

externalServices:
  prometheus:
    host: "$PROM_ENDPOINT"
    basicAuth:
      username: "$PROM_USERNAME"
      password: "$PROM_PASSWORD"

  loki:
    host: "$LOGS_ENDPOINT"
    basicAuth:
      username: "$LOGS_USERNAME"
      password: "$LOGS_PASSWORD"

opencost:
  opencost:
    exporter:
      defaultClusterId: "testy"
    prometheus:
      external:
        url: "$PROM_ENDPOINT"
EOF
```
