### ISSUE TITLE
Add proxy support for Tempo and OpenCost

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#193]
[Original slack thread](https://raintank-corp.slack.com/archives/C023M1GG5RD/p1697696669932249)

**Tempo**

Proxy configuration appears to be done via the *nix environment variables (such as `HTTPS_PROXY`), according to the docs:
https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.exporter.otlp/

To maintain compatibility with k8s service discovery, `NO_PROXY` should be used to exclude the API server, e.g.:

```yaml
grafana-agent:
  agent:
    extraEnv:
    - name: HTTPS_PROXY
      value: https://proxy.example.com/
    - name: NO_PROXY
      value: <cluster.kubernetesAPIService, maybe without port>
```
