### ISSUE TITLE
Failed to parse user ID:  ArgoCD + Kustomize + Helm + k8s 1.27

### ISSUE THREAD

**Issue by dmouse** [grafana/k8s-monitoring-helm#225]
Hi All!

I want to install this agent to send my logs to the grafana cloud, I have installed all via Helm handled by Kustomize, I patched the Deployment to change version and update the labels to be compatible with my k8s version, so my kustomization.yaml:

```
namespace: utils

helmCharts:
  - name: grafana
    includeCRDs: true
    releaseName: grafana-k8s-monitoring
    version: 0.3.0
    repo: https://grafana.github.io/helm-charts
    namespace: utils
    valuesFile: values.yaml # configured as the doc specify.

patches:
  - patch: |
      - op: replace
        path: /apiVersion
        value: apps/v1
      - op: add
        path: /spec/selector
        value:
          matchLabels:
            app: grafana-k8s-monitoring-grafana
            component: grafana
            release: grafana-k8s-monitoring
    target:
      group: extensions
      version: v1beta1
      kind: Deployment
```

This was the issue with the labels (fixed using the patch):
```
one or more objects failed to apply, reason: Deployment.apps "grafana-k8s-monitoring-grafana" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"grafana-k8s-monitoring-grafana", "component":"grafana", "release":"grafana-k8s-monitoring"}: `selector` does not match template `labels`, spec.selector: Invalid value: "null": field is immutable]. Retrying attempt #3 at 7:37PM.
```

This is the error that I got in the pod:
```
logger=http.server t=2023-11-01T19:38:29.5848428Z level=error msg="Failed to parse user ID" error="identifier is not initialized"
logger=http.server t=2023-11-01T19:38:39.584174197Z level=error msg="Failed to parse user ID" error="identifier is not initialized"
```

I'm going to try with the grafana agent but I want to let you know what I found.

Update:
BTW argocd reports that all is up:
![image](https://github.com/grafana/k8s-monitoring-helm/assets/198571/fa96dd2f-e043-41ee-8640-311764cbd274)

**Comment by dmouse** [comment]
I found what I did wrong, the final configuration file is this, just in case this helps to others:

```
namespace: utils

helmCharts:
  - name: k8s-monitoring
    includeCRDs: true
    releaseName: k8s-monitoring
    version: 0.3.0
    repo: https://grafana.github.io/helm-charts
    namespace: utils
    valuesFile: values.yaml
```
