### ISSUE TITLE
Extend kube-state-metrics configuration values

### ISSUE THREAD

**Issue by dmitrii-didenko** [grafana/k8s-monitoring-helm#229]
Hello!

We have a necessity of configuring kube-state-metrics to support customResourceState monitoring. The example of such config can be found here: https://github.com/fluxcd/flux2-monitoring-example/blob/main/monitoring/controllers/kube-prometheus-stack/kube-state-metrics-config.yaml
Additional details: https://fluxcd.io/flux/monitoring/custom-metrics/ 
By using kube-state-metrics chart from the prometheus-community directly, I've managed to configure this set up with the following values:
```
    prometheus:
      monitor:
        enabled: true
    collectors: [ ]
    extraArgs:
      - --custom-resource-state-only=true
    rbac:
      extraRules:
        - apiGroups:
            - source.toolkit.fluxcd.io
            - kustomize.toolkit.fluxcd.io
            - helm.toolkit.fluxcd.io
            - notification.toolkit.fluxcd.io
            - image.toolkit.fluxcd.io
          resources:
            - gitrepositories
            - helmrepositories
            - helmcharts
            - kustomizations
            - helmreleases
            - imagerepositories
            - imagepolicies
            - imageupdateautomations
          verbs: [ "list", "watch" ]
    customResourceState:
      enabled: true
      config:
        spec:
          resources:
            - groupVersionKind:
                group: kustomize.toolkit.fluxcd.io
                version: v1
                kind: Kustomization....
```
I'd like to use this functionality in your chart. Would it be possible to extend values in this umbrella chart to support the following values for kube-state-metrics?:
- extraArgs
- rbac
- customResourceState
