### ISSUE TITLE
Fresh install fails with ArgoCD

### ISSUE THREAD

**Issue by Lp-Francois** [grafana/k8s-monitoring-helm#234]
Using ArgoCD ([v2.8.6](https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.6/manifests/install.yaml)), the installation of the latest version fails with:

```txt
Error: execution error at (k8s-monitoring/templates/crds/check-for-crds.yaml:2:6): 
This chart is attempting to deploy the Prometheus Operator CRDs, but they have already been installed on this cluster. 
Please set: prometheus-operator-crds: enabled: false and re-deploy Use --debug flag to render out invalid YAM
```

[k8s-monitoring-helm](https://github.com/grafana/k8s-monitoring-helm) version: 0.3.1

__Before__ installing k8s-monitoring-helm, I used to run the grafana agent with CRDs. After removing the old agent, I did clean the cluster from any leftover CRDs such as:

```sh
alias k=kubectl

k get crds | grep monitoring
# notice several CRDs leftovers

# proceed to clean them all
helm template prometheus-operator-crds prometheus-community/prometheus-operator-crds | kubectl delete -f -

k delete -f https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_podlogs.yaml
k delete -f https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_metricsinstances.yaml
k delete -f https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_logsinstances.yaml
k delete -f https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_integrations.yaml
k delete -f https://raw.githubusercontent.com/grafana/agent/main/production/operator/crds/monitoring.grafana.com_grafanaagents.yaml

k get crds | grep monitoring
# nothing shows
```

The install then cause the error with the CRD being already present... But the helm chart did install the CRD by itself! If I now run the previous commands, I get:

```sh
> k get crds | grep monitoring
alertmanagerconfigs.monitoring.coreos.com                        2023-11-04T22:39:29Z
alertmanagers.monitoring.coreos.com                              2023-11-04T22:39:29Z
podmonitors.monitoring.coreos.com                                2023-11-04T22:39:29Z
probes.monitoring.coreos.com                                     2023-11-04T22:39:29Z
prometheusagents.monitoring.coreos.com                           2023-11-04T22:39:30Z
prometheuses.monitoring.coreos.com                               2023-11-04T22:39:30Z
prometheusrules.monitoring.coreos.com                            2023-11-04T22:39:29Z
scrapeconfigs.monitoring.coreos.com                              2023-11-04T22:39:29Z
servicemonitors.monitoring.coreos.com                            2023-11-04T22:39:29Z
thanosrulers.monitoring.coreos.com                               2023-11-04T22:39:29Z
```

What I think happens, is: Argo templates the helm chart, starts to install the CRDs, then the check fails cause the CRD just got installed.

Could it be a possible issue?

I am not sure that checking if the CRDs are presents shouldn't be left to the user to decide, instead of forcing a helm install to fail 🤔 

As a workaround, I am going to disable the `prometheus-operator-crds`, and install them using kustomize, but it would be more convenient to keep everything together.

**Comment by Lp-Francois** [comment]
If someone is looking for a quick fix, splitting the prometheus operator CRDs in another Application:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  source:
    # https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
    chart: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 6.0.0
```

and install the `k8s-monitoring-helm` chart with `prometheus-operator-crds.enabled: false`

**Comment by dmouse** [comment]
try including this:
```
# ...
syncPolicy:
    syncOptions:
      - ServerSideApply=true
```

**Comment by Lp-Francois** [comment]
Thanks @dmouse , I'll give a try :)

**Comment by Lp-Francois** [comment]
@dmouse Actually I had `ServerSideApply=true` in my grafana-k8s-monitoring application 🤔 

This is how my Application looked like before I disabled the prom CRDs:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring

  source:
    # https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
    chart: k8s-monitoring
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.3.1
    helm:
      valuesObject:
        prometheus-operator-crds:
          enabled: true
        cluster:
          name: my-cluster # to be overriden 
```
