### ISSUE TITLE
Grafana cloud is not detecting CPU usage and Clusters

### ISSUE THREAD

**Issue by dmouse** [grafana/k8s-monitoring-helm#239]
Hi!

I'm testing the grafana cloud and I configured this k8s-monitor in this way:

```yaml
# kustomization.yaml
namespace: utils

helmCharts:
  - name: k8s-monitoring
    includeCRDs: true
    releaseName: k8s-monitoring
    version: 0.4.0
    repo: https://grafana.github.io/helm-charts
    namespace: utils
    valuesFile: values.yaml
```

```yaml
# values.yaml
cluster:
  name: develop

externalServices:
  prometheus:
    host: https://prometheus-prod--prod-us-east-0.grafana.net
    basicAuth:
      username: "1"
      password: ''
  loki:
    host: https://logs-prod-.grafana.net
    basicAuth:
      username: "1"
      password: ''
  tempo:
    host: https://tempo-prod--prod-us-east-0.grafana.net:443
    basicAuth:
      username: "1"
      password: ''

metrics:
  cost:
    enabled: false
  cadvisor:
    enabled: true

opencost:
  enabled: false

logs:
  enabled: true

traces:
  enabled: true

grafana-agent:
  agent:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: "zipkin"
        port: 9411
        targetPort: 9411
        protocol: "TCP"
```

This creates  the following containers:
* k8s-monitoring-prometheus-node-exporter-mp6pv
* k8s-monitoring-kube-state-metrics-7475778df6-8xxqg
* k8s-monitoring-grafana-agent-0
* k8s-monitoring-grafana-agent-logs-zgqw4
![image](https://github.com/grafana/k8s-monitoring-helm/assets/198571/05804f6e-3b38-464d-9cf4-ec48c552e828)

but in the Dashboard is not present any of the CPU metrics

![image](https://github.com/grafana/k8s-monitoring-helm/assets/198571/c6039e96-4092-4579-b331-5f1f75069e9f)

Also in the `Obsevability > Kubernetes > Cluster Navigation` menu is not detecting any metrics but in the explorer it shows some logs, memory...

![image](https://github.com/grafana/k8s-monitoring-helm/assets/198571/6889f0a2-f24e-4339-b1f4-995e4b60f638)

Any thoughts on this?

**Comment by petewall** [comment]
Typically when I see missing data like this, I go to the explore page and check that this query is coming back:
`kube_node_info{cluster="<your cluster name>"}`
We use the `kube_node_info` query from Kube State Metrics as the start of a lot of metric sources.

Since you're on Grafana Cloud, you can also check the cluster status page to get a snapshot if all the right metric sources are coming in:
`Obsevability > Kubernetes > Configuration (side bar) > Metrics status`

**Comment by dmouse** [comment]
The `kube_node_info` metric is not present in the Explore, I opened a support ticket in grafana.org so maybe they can help me to debug this.

Also I notice that the `cAdvisor` pod is not present

**Comment by petewall** [comment]
Do you see any errors in the `k8s-monitoring-grafana-agent-0` pod logs?
What kind of cluster is this? OpenShift, GKE, EKS, bare metal, etc...
cAdvisor runs inside the Kubelet, so you wont see a pod.

**Comment by dmouse** [comment]
I'm running a DigitalOcean k8s manage cluster:

the `k8s-monitoring-grafana-agent-0` looks good, I mean no error in the last log messages.
```
ts=2023-11-08T22:00:53.297891405Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:01:53.297911177Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:02:53.29751227Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:03:53.298268642Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:04:53.297462817Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:05:53.297924314Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:06:53.297700098Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:07:53.297716304Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:08:53.298371035Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:09:53.297675481Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:10:08.281134105Z level=info msg="finished node evaluation" controller_id="" node_id=discovery.relabel.kube_state_metrics duration=919.624µs
ts=2023-11-08T22:10:53.297533592Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:11:53.297922113Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
ts=2023-11-08T22:12:53.29814044Z level=info msg="rejoining peers" peers=10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80,10-244-1-20.k8s-monitoring-grafana-agent-cluster.utils.svc.cluster.local.:80
```

**Comment by dmouse** [comment]
This caught my attention: `msg="finished node evaluation" controller_id=""` the `controller_id` is empty

**Comment by grafana-dylan** [comment]
Hi, I sent a status update in the ticket regarding the kube-state-metrics. Let me know once you have moment to review the details.

**Comment by UbiquitousBear** [comment]
@grafana-dylan is there anything that can be shared here? I'm also seeing the same behaviour with pushing to an LGTM OSS stack

**Comment by petewall** [comment]
@UbiquitousBear , is it just kubelet metrics that are failing or are all metric sources failing? Anything special about the `sentinel` node?

**Comment by dmouse** [comment]
thanks for the follow up @petewall ,

In my scenario, I'm using ArgoCD with a declarative configuration, so I have Argo apps like this:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
  # ...
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
```

my argo app defines the `metadata.name: ARGO-APP-NAME` which is the name that I can see in the UI. I also noticed that this name is used in the `__meta_kubernetes_service_label_app_kubernetes_io_instance`.

`k8s-monitoring` has the `discovery.relabel "kube_state_metrics"` which defines a rule.

```
source_labels ["__meta_kubernetes_service_label_app_kubernetes_io_instance"]
regex "k8s-monitoring"
action "keep"
```

So, in my original Argo app, I declared the name as grafana-develop. Consequently, the value in `__meta_kubernetes_service_label_app_kubernetes_io_instance` was `grafana-develop`, which doesn't match with the expected regex rule k8s-monitoring

This is the definition of the [`discovery.relabel "kube_state_metrics"` ](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/templates/agent_config/_kube_state_metrics.river.txt#L3-L11) it use `regex = "{{ .Release.Name }}"` to create the rule.

Is there a way to use the same value that is in the `__meta_kubernetes_service_label_app_kubernetes_io_instance` ?

**Comment by petewall** [comment]
Ah, i see! ArgoCD takes over the `app.kubernetes.io/instance` label for its own purposes ([doc](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-release-name)).

There's a short-term fix and a long-term fix.

The short-term fix is to deploy KSM yourself, then set:
```yaml
kube-state-metrics:
  enabled: false
```

This will skip the KSM deployment via the k8s-monitoring chart (which will remove the label matcher for that), but it will still be configured to search for KSM and scrape the metrics. You'll likely need to do the same for Node Exporter.

The long term fix will require me to either re-think or remove that specific label matcher.

**Comment by petewall** [comment]
Quick question, where did the `grafana-develop` come from? Was that the name of the app in argocd?

**Comment by dmouse** [comment]
@petewall it comes from this line:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-develop # <- this line
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
  # ...
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
```

**Comment by petewall** [comment]
OK, so this is where the Helm chart, rendered with Kustomize, then deployed with ArgoCD, but using different release and app names.

**Comment by dmouse** [comment]
I tested the version 0.6.0 with a custom name and it's working as expected.

Thank you!

**Comment by sambonbonne** [comment]
Hello,

It seems I have the same issue, deploying with ArgoCD but with the Helm chart (not a Kustomize rendering), on `0.6.1`. I'm not using Grafana Cloud but Grafana on premise, with Mimir to collect metrics (so the agent uses `remote_write`).

I set `releaseName: grafana-kubernetes-monitoring` but nothing change: I have memory metrics but not CPU metrics (and it seems some network metrics don't work as well).

@dmouse how did you use the custom name?

**Comment by dmouse** [comment]
@sambonbonne try changing the release name to `k8s-monitoring` and check if this works

**Comment by sambonbonne** [comment]
@dmouse thanks, we decided to move on and install `node-exporter` and `kube-state-metrics` with the Kube Prometheus community chart for now but it's good to know we can give this a try when we have some more time for this topic

**Comment by templarfelix** [comment]
@dmouse only force release name doesn't solve the problem.

**Comment by templarfelix** [comment]
i found a workaround:

releaseName: k8s-monitoring-{{values.suffix}} equals application/set.spec.template.metadata.name

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-infrastructure
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:xxx/k8s-appsofapps.git
              revision: HEAD
              files:
              - path: apps/_cluster_config/infrastructure/**/**/config.yaml
              pathParamPrefix: target
          - git:
              repoURL: git@github.com:xxx/k8s-appsofapps.git
              revision: HEAD
              files:
              - path: apps/_dataset_config/infrastructure/config.yaml
              pathParamPrefix: app
  template:
    metadata:
      name: 'k8s-monitoring-{{values.suffix}}'
    spec:
      project: "monitoring"
      source:
        repoURL: https://grafana.github.io/helm-charts
        chart: k8s-monitoring
        targetRevision: 0.6.1
        helm:
          valuesObject:
            cluster:
              name: infrastructure
            externalServices:
              prometheus:
                host: https://prometheus-prod-40-prod-sa-east-1.grafana.net
                basicAuth:
                  username: "xxx"
                  password: xxx
              loki:
                host: https://logs-prod-024.grafana.net
                basicAuth:
                  username: "xxx"
                  password: xxx
            opencost:
              enabled: true
              opencost:
                exporter:
                  defaultClusterId: infrastructure
                prometheus:
                  external:
                    url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom
          passCredentials: false
          releaseName: k8s-monitoring-{{values.suffix}}
          ignoreMissingValueFiles: false
          skipCrds: false
          version: v3
      destination:
        name: '{{server}}'
        namespace: monitoring
      syncPolicy: 
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - ServerSideApply=true
```
