### ISSUE TITLE
Grafana-agent seems to be ignoring one specific ServiceMonitor

### ISSUE THREAD

**Issue by Routhinator** [grafana/k8s-monitoring-helm#243]
I've been banging my head off this one for a day or two in a silo, so reaching out here in case I'm missing something obvious.

I have prometheus-server deployed but I have all it's scraping turned off. I would like to maintain one set of relabel configs and I want the prometheus stats for the server to be labeled with podname etc.. so I want the grafana-agent from this chart to scrape Prom.

However... it just won't? I have several PodMonitors and ServiceMonitors in the cluster, and I see it hitting them all in the logs and the metrics coming in with the job names `<namespace>/<monitorname>` - however it just ignores this one.. no errors, no obvious reason.

Is this some sort of expected behaviour? Like grafana-agent see's it's prom and just says no? 

The prom scrape config for itself usually just hits localhost:9090 - so I didn't think there would be anything special here.. just specify port name or number, but no scrape seems to occur.

Anyone see anything I'm missing here?

ServiceMonitor (also tried podmonitor)
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  podMetricsEndpoints:
  - port: containerPort
```

k8s-monitoring config:
```
metrics:
  scrapeInterval: 15s
  agent:
    enabled: true
    allowList: []
  kube-state-metrics:
    enabled: true
    allowList: []
  node-exporter:
    enabled: true
    allowList: []
  kubelet:
    enabled: true
    allowList: []
  cadvisor:
    enabled: true
    allowList: []
  apiserver:
    enabled: true
    allowList: []
  podMonitors:
    enabled: true
    namespaces: []
  probes:
    enabled: true
    namespaces: []
  serviceMonitors:
    enabled: true
    namespaces: []
```
