### ISSUE TITLE
Setting tolerations and nodeSelector for each deployment

### ISSUE THREAD

**Issue by cgill27** [grafana/k8s-monitoring-helm#251]
Is there any way to specify tolerations and nodeSelectors on the individual deployments this chart deploys?
We are wanting to have all of the chart's deployments run on specific node groups.

**Comment by petewall** [comment]
There isn't a single place to do that for every deployment, you'd have to set that in the individual subcharts:
```yaml
grafana-agent:
  controller:
    nodeSelector: {}
    tolerations: []
kube-state-metrics:
  nodeSelector: {}
  tolerations: []
```
etc...
