### ISSUE TITLE
Improve `helm test` so it can assert values

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#257]
Currently, Helm test only checks that metrics or logs exist. I'd love to add an expected result to the query to assert things like the number of nodes is accurate.

Also, would love to do something like:
1. Enable [scrape_samples_scraped](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/#scraping-behavior) in Grafana Agent allow list.
2. Run the query `count_over_time(scrape_samples_scraped[1m])` to [calculate DPM](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/reduce-costs/metrics-costs/adjust-data-points-per-minute/#both-platforms)
3. Check that the value should be 1

**Comment by petewall** [comment]
New queries schema:

```yaml
- query: <string>
  type: <enum:["promql"(def), "logql", "traceql"]>
  expect:
    value: <number>
    operator: <enum:["<","<=","="(def),">=",">","!="]>
```

example:
```yaml
- query: count(kube_node_info{cluster="my-3-node-cluster"})
  type: "promql"
  expect:
    value: 3
- query: up{job="integrations/node_exorter}
  type: "promql"
  expect:
    value: 0
    operator: !=
```
