### ISSUE TITLE
remote.kubernetes.secret.metrics_service.data["tenantId"] secrets may not be converted into strings

### ISSUE THREAD

**Issue by rknightion** [grafana/k8s-monitoring-helm#258]
Since https://github.com/grafana/k8s-monitoring-helm/pull/224, we've been unable to update to the new version.

```
ts=2023-11-22T10:54:40.530186141Z level=info msg="finished complete graph evaluation" controller_id="" trace_id=3e64f9fb4cde878e5d366783e252fe3c duration=36.68563ms
Error: /etc/agent/config.river:590:35: remote.kubernetes.secret.metrics_service.data["tenantId"] secrets may not be converted into strings

589 |     url = nonsensitive(remote.kubernetes.secret.metrics_service.data["host"]) + "/api/v1/push"
590 |     headers = { "X-Scope-OrgID" = remote.kubernetes.secret.metrics_service.data["tenantId"] }
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
591 | 
ts=2023-11-22T10:54:40.530392544Z level=error msg="failed to start reporter" err="context canceled"
```

Looking at our prometheus-k8s-monitoring auto generated secret, the key tenantId is indeed a string.

Relevant externalServices values section:
```
externalServices:
  # Connection information for Prometheus
  prometheus:
    host: http://mimir-distributor.mimir.svc.cluster.local:8080
    externalLabels:
      mimircluster: {{ .Environment.Name }}
      envtype: {{ .Environment.Values.type }}
      customer: {{ .Environment.Values.customer }}
      product: {{ .Environment.Values.product }}
    tenantId: plprod
    authMode: none
```
