### ISSUE TITLE
Opencost UI shows no values

### ISSUE THREAD

**Issue by jorsmatthys** [grafana/k8s-monitoring-helm#263]
We are using the k8s-monitoring-helm with pretty standard configuration to connect our Azure Kubernetes Cluster with our Grafana Cloud (pro) stack. We are enabling opencost and the opencost-ui. We see that opencost metrics seem to get ingested succesfully in Grafana-Cloud, because our cost dashboards in the observability section of grafana cloud are showing data. 

However the opencost UI does not seem to be showing the correct data (pretty much empty, it doesn't even have the namespace names). 

Helm Chart version: 0.5.1

Our config: 

```yaml
    opencost:
      opencost:
        exporter:
          defaultClusterId: aks-aks-poc-dev
        prometheus:
          external:
            url: https://prometheus-prod-22-prod-eu-west-3.grafana.net/api/prom
        ui:
          enabled: true
```

The opencost pod is running, but in the logs we get the following error (logged as info) at startup:

> │ 2023-11-23T16:14:53.265057082Z INF Success: retrieved the 'up' query against prometheus at: https://prometheus-prod-22-prod-eu-west-3.grafana.net/api/prom                                                                                                                                                                                                              │
│ 2023-11-23T16:14:53.270207892Z INF No valid prometheus config file at https://prometheus-prod-22-prod-eu-west-3.grafana.net/api/prom. Error: client_error: client error: 404 . Troubleshooting help available at: http://docs.kubecost.com/custom-prom#troubleshoot. Ignore if using cortex/thanos here.  

In the UI we only get the following:

![image](https://github.com/grafana/k8s-monitoring-helm/assets/67681021/c7d2a40f-23e4-4e7d-8c38-f6ca24cdc9e3)
