### ISSUE TITLE
Deployment errors from subchart dependencies aren't bubbled up

### ISSUE THREAD

**Issue by hedss** [grafana/k8s-monitoring-helm#264]
An install/upgrade can fail silently if the underlying [Grafana Agent chart](https://github.com/grafana/agent/tree/main/operations/helm/charts/grafana-agent) is passed invalid arguments; no warnings are given even though the underlying chart will throw these errors, and the chart claims successful deployment.

For example, given the following configuration snippet:
```yaml
traces:
  enabled: true
grafana-agent:
  agent:
    extraPorts:
      - name: "jaeger-thrift-compact"
        port: 6831
        targetPort: 6831
        protocol: "TCP"
      - name: "jaeger-thrift-binary"
        port: 6832
        targetPort: 6832
        protocol: "TCP"
      - name: "jaeger-thrift-http"
        port: 14268
        targetPort: 14268
        protocol: "TCP"
extraConfig: |-
   ...
```
an install of the Helm chart will show:
```bash
heds@Ahsoka ~/Work/tmp/quick-install-test $ helm upgrade --install -f values-k8s.yaml grafana-k8s-monitoring grafana/k8s-monitoring -n agent
Release "grafana-k8s-monitoring" does not exist. Installing it now.
NAME: grafana-k8s-monitoring
LAST DEPLOYED: Wed Nov 22 17:46:52 2023
NAMESPACE: agent
STATUS: deployed
REVISION: 1
```
However, whilst the logs and metrics Daemonsets will successfull be deployed, the traces instance is not.

By using the same snippet of configuration for extra port opening with the underlying Grafana Agent chart and attempting a Helm install, we see:
```bash
heds@Ahsoka ~/Work/Docs-With-Kim/FederationFrontend/agent-test $ helm install -f values.yaml agent-test grafana/grafana-agent -n agent
Error: INSTALLATION FAILED: 1 error occurred:
        * DaemonSet.apps "agent-test-grafana-agent" is invalid: [spec.template.spec.containers[0].ports[3].name: Invalid value: "jaeger-thrift-compact": must be no more than 15 characters, spec.template.spec.containers[0].ports[4].name: Invalid value: "jaeger-thrift-binary": must be no more than 15 characters, spec.template.spec.containers[0].ports[5].name: Invalid value: "jaeger-thrift-http": must be no more than 15 characters]
```
This shows the underlying issue, the names for the Jaeger ports are actually too long and need to be shortened. If we change the config for the k8s monitoring install and try with shorter names, the install works as expected.

Underlying errors for subchart dependencies should be bubbled up to ensure that users do not run into quiet failures that otherwise claim successul deployment.
