### ISSUE TITLE
Question/Feat - queryEndpoint for Mimir when Ingesting via Distributor

### ISSUE THREAD

**Issue by rknightion** [grafana/k8s-monitoring-helm#281]
We use this chart to push into a central Mimir instance (and thankful to this team every day for such an amazing helm chart that makes it super easy!)

As we use the Mimir API, our externalServices.prometheus.writeEndpoint is /api/v1/push
I notice there's a queryEndpoint in the prometheus section also. I presume this is for KubeCost (unless the agent needs to query prometheus for other things?). 

The natural choice for this would be /api/v1/query. However, I think that in a Mimir environment by default it's expected that those queries go to the Mimir gateway/nginx reverse proxy. We've had challenges with scaling the Mimir Gateway (primarily due to no of gateway replicas needed for the high volume of metrics traffic received so additional nodes required and additional intra-az traffic costs) so instead of using the Mimir Gateway we expose our Mimir Distributors directly via a NLB and set our prometheus host to that value. This has worked really well for prometheus pushes, but of course falls over when it comes to querying. 
We still do run the Gateway component for Grafana/querying/ruler etc it's purely metrics ingest we're exposing this way.

So I guess my question is two fold:
- What is the queryEndpoint used for in this chart is it purely KubeCost? (which we are keen to enable soon)
- In environments like ours where the queryEndpoint is on a different host path, is it feasible to add an additional field to support a query host in the chart? (I may be wrong but I've seen some evidence in the Mimir community of others pushing directly to distributors as well for similar Gateway related reasons).

If this is too niche to be desired in the chart, I wonder if it's possible to use some extraConfig to add it into the agent given extraConfig can't override any existing config just add additional? 
- Of course if the queryEndpoint is only used for KubeCost and not by the agent (which I suspect by our agents working fine for a few months with an invalid queryEndpoint!) then this can be completely closed and I'll figure out how to override in the sub chart directly :)

**Comment by petewall** [comment]
Running `helm test` will also use the query endpoint to check that the metrics the chart expects to publish actually made it to mimir.

**Comment by petewall** [comment]
So, as of now, you can set different urls for both places where metrics are read:
```
test:
  envOverrides:
    PROMETHEUS_URL: "https://prom.example.com/api/prom/api/v1/query" <-- The URL that will be queried during helm test
opencost:
  opencost:
    prometheus:
      external:
        enabled: true
        url: "https://prom.example.com/api/prom" <-- The URL that OpenCost will read metrics from
```
