### ISSUE TITLE
Opencost not supported when using a custom secret

### ISSUE THREAD

**Issue by mischavandenburg** [grafana/k8s-monitoring-helm#285]
I have deployed k8s-monitoring with the following secret setup:

```yaml
  externalServices:
    prometheus:
      hostKey: prometheus-host
      basicAuth:
        usernameKey: prometheus-user
        passwordKey: prometheus-password

      secret:
        create: false
        name: grafana-agent-credentials-akv2k8s
        namespace: k8s-monitoring

    loki:
      hostKey: loki-host
      basicAuth:
        usernameKey: loki-user
        passwordKey: loki-password

      secret:
        create: false
        name: grafana-agent-credentials-akv2k8s
        namespace: k8s-monitoring

```

I have enabled opencost with the following code:

```yaml
  opencost:
    enabled: true
    opencost:
      exporter:
        defaultClusterId: aks-mycluster
      prometheus:
        external:
          url: https://prometheus-dev-22-dev-eu-west-1.grafana.net/api/prom
```

When deployed to the cluster, the opencost pod throws the following error:

`"k8s-monitoring-opencost" in pod "k8s-monitoring-opencost-7d7c9bff9b-6v547" is waiting to start: CreateContainerConfigError`

Then, in the Kubernetes events, I see the following:

`Error: secret "prometheus-k8s-monitoring" not found`

I suspect that opencost is still expecting the secrets which are created by the k8s-monitoring chart, but it is not being created because I set secret.create=false to use custom secrets synched from Azure Key Vaults.

**Comment by petewall** [comment]
You'll need to tell OpenCost where the secret is:
```
opencost:
  opencost:
    prometheus:
      secret_name: grafana-agent-credentials-akv2k8s
      username_key: prometheus-user
      password_key: prometheus-password
```

**Comment by mischavandenburg** [comment]
Thank you very much @petewall! I tried it out and it worked with the custom secret.

I created a PR to update the readme with these values. It was not clear to me from the documentation that I could set these parameters.

**Comment by rhigonet** [comment]
> You'll need to tell OpenCost where the secret is:
> 
> ```
> opencost:
>   opencost:
>     prometheus:
>       secret_name: grafana-agent-credentials-akv2k8s
>       username_key: prometheus-user
>       password_key: prometheus-password
> ```

Update: the field has been changed. Now instead of `secret_name` the field is `existingSecretName`
Source: https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring-v1#deployment-opencost

**Comment by MaxDiOrio** [comment]
@rhigonet  - What about if you don't use a Prometheus username/password?  We have Mimir and don't require auth internally, but the chart is still deployed as if it is required.  I haven't seen a way to disable the auth requirement altogether.  Any ideas? 

```
    - name: DB_BASIC_AUTH_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: prometheus-k8s-monitoring
    - name: DB_BASIC_AUTH_PW
      valueFrom:
        secretKeyRef:
          key: password
          name: prometheus-k8s-monitoring
```
And when describing the failing pod:
```
DB_BASIC_AUTH_USERNAME:                <set to the key 'username' in secret 'prometheus-k8s-monitoring'>  Optional: false                                                                                                      
DB_BASIC_AUTH_PW:                      <set to the key 'password' in secret 'prometheus-k8s-monitoring'>  Optional: false  
```
