### ISSUE TITLE
Missing Metric - kube_node_labels

### ISSUE THREAD

**Issue by edas-smith** [grafana/k8s-monitoring-helm#314]
Hello!

I am using version 0.7.3 of this helm chart.

There is a metric called kube_node_labels which should be published by the kube-state-metrics : https://github.com/kubernetes/kube-state-metrics/blob/main/docs/node-metrics.md .

This is my allowList for kube-state-metrics : 
```
  kube-state-metrics:
    allowList:
    - kube_persistentvolumeclaim_status_phase
    - kube_persistentvolumeclaim_info
    - kube_pod_container_resource_requests
    - kube_pod_status_phase
    - kube_pod_status_reason
    - kube_job_status_succeeded
    - kube_job_status_active
    - kube_job_status_failed
    - kube_pod_container_resource_limits
    - kube_pod_container_resource_requests
    - kube_pod_container_status_waiting_reason
    - kube_pod_info
    - kube_deployment_metadata_generation
    - kube_statefulset_metadata_generation
    - kube_pod_annotations
    - kube_node.*
```

However, I don't seem to be receiving the metric kube_node_labels in Grafana. I am using Grafana Cloud* with the managed prometheus. 

I have also tried adding the metric like this : 
`- kube_node_labels`

But this doesn't seem to work either. Has anyone come across this before? I am sadly unsure how to go about resolving this currently.

**Comment by skl** [comment]
@edas-smith to gather Kubernetes labels and annotations, in addition to adding the desired metrics to the KSM allow list as you have done, CLI arguments are also needed on the KSM deployment such as [--metric-labels-allowlist](https://github.com/kubernetes/kube-state-metrics/blob/fde27ece8aba779d23c6ae53325a0cc7af9da008/docs/cli-arguments.md?plain=1#L60C1-L60C740).

The KSM helm chart has these values to support the above:

- [metricLabelsAllowlist](https://github.com/prometheus-community/helm-charts/blob/7b83b454a0bb76a8ed2cee00eee44b74dc1f3775/charts/kube-state-metrics/values.yaml#L291-L298)
- [metricAnnotationsAllowList](https://github.com/prometheus-community/helm-charts/blob/7b83b454a0bb76a8ed2cee00eee44b74dc1f3775/charts/kube-state-metrics/values.yaml#L300-L307)

You can see in this KSM helm deployment template that the CLI argument is added when these values are used [here](https://github.com/prometheus-community/helm-charts/blob/7b83b454a0bb76a8ed2cee00eee44b74dc1f3775/charts/kube-state-metrics/templates/deployment.yaml#L74-L76).

Those sub-chart values should be able to be used with the k8s-monitoring-helm chart like so:

```yaml
# KSM labels and annotations example
metrics:
  kube-state-metrics:
    metricLabelsAllowlist:
      - namespaces=[k8s-label-1,k8s-label-n]

    metricAnnotationsAllowList:
      - pods=[k8s-annotation-1,k8s-annotation-n]
```

The `nodes` collector/resource is [enabled by default](https://github.com/prometheus-community/helm-charts/blob/7b83b454a0bb76a8ed2cee00eee44b74dc1f3775/charts/kube-state-metrics/values.yaml#L326), so you should be able to do something like:

```yaml
metrics:
  kube-state-metrics:
    metricLabelsAllowlist:
      - nodes=[k8s-label-1,k8s-label-n]
```

I'd be interested to know how you get on - as it could be worth writing up an example about this use case.

**Comment by edas-smith** [comment]
@skl thanks so much for the quick response!

I have just looked into this ( if I understood the above correctly ). 

I've added a couple labels seen here : 
```
  kube-state-metrics:
    allowList:
    - kube_persistentvolumeclaim_status_phase
    - kube_persistentvolumeclaim_info
    - kube_pod_container_resource_requests
    - kube_pod_status_phase
    - kube_pod_status_reason
    - kube_job_status_succeeded
    - kube_job_status_active
    - kube_job_status_failed
    - kube_pod_container_resource_limits
    - kube_pod_container_resource_requests
    - kube_pod_container_status_waiting_reason
    - kube_pod_info
    - kube_deployment_metadata_generation
    - kube_statefulset_metadata_generation
    - kube_pod_annotations
    - kube_node.*
    metricLabelsAllowlist:
      - nodes=[workload-type, node.kubernetes.io/instance-type]
```

However, the metric still doesn't appear to be coming into Grafana. Am not entirely sure why this is.

**Comment by skl** [comment]
@edas-smith Sorry, my fault. I've edited the example in my comment above to the correct helm values, it seems in this case `kube-state-metrics:` needs to be at the top level to pass values to the subchart. `metrics.kube-state-metrics` is used for the KSM scraping in this chart whereas the top level `kube-state-metrics` is the subchart itself.

**Comment by skl** [comment]
Also, maybe remove the space after the comma? So:

```yaml
metrics:
  kube-state-metrics:
    allowList:
    - kube_persistentvolumeclaim_status_phase
    - kube_persistentvolumeclaim_info
    - kube_pod_container_resource_requests
    - kube_pod_status_phase
    - kube_pod_status_reason
    - kube_job_status_succeeded
    - kube_job_status_active
    - kube_job_status_failed
    - kube_pod_container_resource_limits
    - kube_pod_container_resource_requests
    - kube_pod_container_status_waiting_reason
    - kube_pod_info
    - kube_deployment_metadata_generation
    - kube_statefulset_metadata_generation
    - kube_pod_annotations
    - kube_node.*

kube-state-metrics:
  metricLabelsAllowlist:
    - nodes=[workload-type,node.kubernetes.io/instance-type]
```
