### ISSUE TITLE
Add log level to pod logs

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#32]
Suggestion on [slack](https://raintank-corp.slack.com/archives/C023M1GG5RD/p1681896957539719):

I was missing the colorisation of logs from my pods in Loki explore mod. Adding the following to the grafana agents logs ConfigMap fixed it.
Instead of:

```yaml
pipeline_stages:
            - docker: {}
```

I have:

```yaml
pipeline_stages:
            - docker: {}
            - regex:
                expression: “(?P<level>[a-zA-Z]+):(.*)”
            - labels:
                level:
```
