### ISSUE TITLE
excludeMetrics is not working for some metrics scrappers

### ISSUE THREAD

**Issue by khaykingleb** [grafana/k8s-monitoring-helm#356]
Hey! Thanks for you work on decreasing the metrics cardinality! Though, I have an issue with it.

I have the following Helm values:
```
# Cluster settings
cluster:
  # -- The name of this cluster, which will be set in all labels. Required.
  name: ${cluster_name} # there will be `meetingmap-gpu` here

# Settings related to capturing and forwarding metrics
metrics:
  ...
  
  # Cluster object metrics from Kube State Metrics
  kube-state-metrics:
    # -- Scrape cluster object metrics from Kube State Metrics
    enabled: true

    # Adjustments to the scraped metrics to filter the amount of data sent to storage.
    metricsTuning:
      # -- Filter the list of metrics from Kube State Metrics to a useful, minimal set. See https://github.com/grafana/k8s-monitoring-helm/blob/85d679e23af4e79eeaae5f2207237e30fef06ff8/charts/k8s-monitoring/README.md#allow-list-for-kube-state-metrics
      useDefaultAllowList: true
      # -- Metrics to keep. Can use regex.
      includeMetrics: []
      # -- Metrics to drop. Can use regex.
      excludeMetrics:
        - kube_lease_owner
        - kube_lease_renew_time
        - kube_pod_tolerations
        - kube_pod_status_ready
        - kube_pod_status_scheduled
        - kube_pod_owner
        - kube_pod_start_time
        - kube_pod_container_state_started
        - kube_node_status_allocatable
        - kube_pod_created
        - kube_pod_ips
        - kube_pod_restart_policy
        - kube_pod_service_account
        - kube_pod_status_initialized_time
        - kube_pod_status_scheduled_time
        - kube_pod_status_container_ready_time
        - kube_pod_status_ready_time
        - kube_horizontalpodautoscaler_status_condition
        - kube_replicaset_created
        - kube_replicaset_metadata_generation
        - kube_replicaset_spec_replicas
        - kube_replicaset_status_fully_labeled_replicas
        - kube_replicaset_status_observed_generation
        - kube_replicaset_status_ready_replicas
        - kube_replicaset_status_replicas
        - kube_deployment_status_condition
        - kube_namespace_status_phase
        - kube_endpoint_ports
        - kube_endpoint_address
        - kube_secret_created
        - kube_secret_metadata_resource_version

  # Node metrics from Node Exporter
  node-exporter:
    # -- Scrape node metrics
    enabled: true

    # Adjustments to the scraped metrics to filter the amount of data sent to storage.
    metricsTuning:
      # -- Filter the list of metrics from Node Exporter to the minimal set required for Kubernetes Monitoring. See https://github.com/grafana/k8s-monitoring-helm/blob/85d679e23af4e79eeaae5f2207237e30fef06ff8/charts/k8s-monitoring/README.md#allow-list-for-node-exporter
      useDefaultAllowList: true
      # -- Filter the list of metrics from Node Exporter to the minimal set required for Kubernetes Monitoring as well as the Node Exporter integration.
      useIntegrationAllowList: false
      # -- Metrics to keep. Can use regex.
      includeMetrics: []
      # -- Metrics to drop. Can use regex.
      excludeMetrics:
        - node_filesystem_readonly
        - node_filesystem_free_bytes
        - node_scrape_collector_duration_seconds
        - node_scrape_collector_success
        - node_cpu_guest_seconds_total

  # Cluster metrics from the Kubelet
  kubelet:
    # -- Scrape cluster metrics from the Kubelet
    enabled: true

    # Adjustments to the scraped metrics to filter the amount of data sent to storage.
    metricsTuning:
      # -- Filter the list of metrics from the Kubelet to the minimal set required for Kubernetes Monitoring. See https://github.com/grafana/k8s-monitoring-helm/blob/85d679e23af4e79eeaae5f2207237e30fef06ff8/charts/k8s-monitoring/README.md#allow-list-for-kubelet
      useDefaultAllowList: true
      # -- Metrics to keep. Can use regex.
      includeMetrics: []
      # -- Metrics to drop. Can use regex.
      excludeMetrics:
        - kubelet_pod_worker_duration_seconds_bucket
        - kubelet_cgroup_manager_duration_seconds_bucket
        - kubelet_runtime_operations_total
        - kubelet_pleg_relist_duration_seconds_bucket
        - kubelet_pleg_relist_interval_seconds_bucket
        - kubelet_pod_start_duration_seconds_bucket
        - rest_client_requests_total
        - storage_operation_duration_seconds_count
        - volume_manager_total_volumes

  # Container metrics from cAdvisor
  cadvisor:
    # -- Scrape container metrics from cAdvisor
    enabled: true

    # Adjustments to the scraped metrics to filter the amount of data sent to storage.
    metricsTuning:
      # -- Filter the list of metrics from cAdvisor to the minimal set required for Kubernetes Monitoring. See https://github.com/grafana/k8s-monitoring-helm/blob/85d679e23af4e79eeaae5f2207237e30fef06ff8/charts/k8s-monitoring/README.md#allow-list-for-cadvisor
      useDefaultAllowList: true
      # -- Metrics to keep. Can use regex.
      includeMetrics: []
      # -- Metrics to drop. Can use regex.
      excludeMetrics:
        - container_memory_cache
        - container_memory_swap
        - container_fs_reads_total
        - container_fs_writes_total
        - container_fs_reads_bytes_total
        - container_fs_writes_bytes_total
```

And it seems that `excludeMetrics` is working for `kubelet` and `cadvisor`. Alas, it is not for `kube-state-metrics` and `node-exporter`. On the graphs, you can see that the `cadvisor` metrics have been excluded as intended, but the same cannot be said for `kube-state-metrics`. Is there a possibility that I might be making an error in this process?

<img width="1440" alt="Screenshot 2024-01-30 at 13 08 06" src="https://github.com/grafana/k8s-monitoring-helm/assets/42534632/24303ff9-6a2e-41fc-b091-e5bbe9333434">
<img width="1440" alt="Screenshot 2024-01-30 at 13 07 58" src="https://github.com/grafana/k8s-monitoring-helm/assets/42534632/15b6b0b6-7d34-4cbb-b495-b884b9e96006">
<img width="1440" alt="Screenshot 2024-01-30 at 13 08 23" src="https://github.com/grafana/k8s-monitoring-helm/assets/42534632/270cf27b-1d75-44d3-9005-13e3be2b4874">
<img width="1440" alt="Screenshot 2024-01-30 at 13 08 30" src="https://github.com/grafana/k8s-monitoring-helm/assets/42534632/271bf4e9-517d-4abe-a482-995b7ee2f264">

**Comment by petewall** [comment]
Something I noticed on your Kube State Metrics screenshot is that the job label is `job="prometheus.scrape.annotation_autodiscovery.http"`

That means that the scraping it's not being done via the normal `metrics.kube-state-metrics` config, but because of the annotations on the KSM pods or service. I'm guessing either the KSM deployment has `k8s.grafana.com/scrape: true` or you've changed the annotations into something that matches the KSM pods or services.

**Comment by khaykingleb** [comment]
Yes, indeed. As of now, I use the basic annotations, so I don't break scrapping from pods running at `staging`/`qa`/`production` k8s clusters using [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) Helm chart:
```
  # Annotation-based autodiscovery allows for discovering metric sources solely on their annotations and does
  # not require adding any extra configuration.
  autoDiscover:
    # Enable annotation-based autodiscovery
    enabled: true


    # -- Annotations that are used to discover and configure metric scraping targets. Add these annotations
    # to your services or pods to control how autodiscovery will find and scrape metrics from your service or pod.
    annotations:
      # -- Annotation for enabling scraping for this service or pod. Value should be either "true" or "false"
      scrape: "prometheus.io/scrape"  # "k8s.grafana.com/scrape"
      # -- Annotation for setting or overriding the metrics path. If not set, it defaults to /metrics
      metricsPath: "prometheus.io/path"  # "k8s.grafana.com/metrics.path"
      # -- Annotation for setting the metrics port by number.
      metricsPortNumber: "prometheus.io/port"  # "k8s.grafana.com/metrics.portNumber"
```

All my k8s deployments include this annotations. For instance:
```
kind: Deployment
apiVersion: apps/v1
spec:
  template:
    metadata:
      labels:
        App: GpuWorkerSpeechProduction
        Env: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8102"
```

**Comment by khaykingleb** [comment]
Why are those metrics—such as `kube_horizontalpodautoscaler_status_condition`—captured via autodiscovery annotations? I do have annotations for some pods in k8s clusters to enable autoscrapping but not for KSM.

```
$ kubectl get pods -n monitoring
NAME                                                 READY   STATUS    RESTARTS   AGE
k8s-monitoring-grafana-agent-0                       2/2     Running   0          10h
k8s-monitoring-grafana-agent-logs-7tltv              2/2     Running   0          10h
k8s-monitoring-grafana-agent-logs-c96ht              2/2     Running   0          10h
k8s-monitoring-grafana-agent-logs-xtgg6              2/2     Running   0          10h
k8s-monitoring-kube-state-metrics-849c7f97f6-x646v   1/1     Running   0          10h
k8s-monitoring-prometheus-node-exporter-cggrg        1/1     Running   0          10h
k8s-monitoring-prometheus-node-exporter-mhzf5        1/1     Running   0          10h
k8s-monitoring-prometheus-node-exporter-s824v        1/1     Running   0          10h

$ kubectl describe pod k8s-monitoring-kube-state-metrics-849c7f97f6-x646v -n monitoring                                       
Name:             k8s-monitoring-kube-state-metrics-849c7f97f6-x646v
Namespace:        monitoring
Priority:         0
Service Account:  k8s-monitoring-kube-state-metrics
Node:             <DELETED>
Start Time:       Tue, 30 Jan 2024 12:57:46 +0400
Labels:           app.kubernetes.io/component=metrics
                  app.kubernetes.io/instance=k8s-monitoring
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=kube-state-metrics
                  app.kubernetes.io/part-of=kube-state-metrics
                  app.kubernetes.io/version=2.10.1
                  helm.sh/chart=kube-state-metrics-5.15.3
                  pod-template-hash=849c7f97f6
Annotations:      <none>
Status:           Running
SeccompProfile:   RuntimeDefault
IP:               <DELETED>
IPs:
  IP:           <DELETED>
Controlled By:  ReplicaSet/k8s-monitoring-kube-state-metrics-849c7f97f6
Containers:
  kube-state-metrics:
    Container ID:  containerd://5000de38f9afa4cdd7105b4b46353dd97fbc68d41804f4cc6fb12928ab3f5354
    Image:         registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
    Image ID:      registry.k8s.io/kube-state-metrics/kube-state-metrics@sha256:af8220f534938de121a694cb7314313a6195c9d494fc30bfa6885b08a276bb82
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --port=8080
      --resources=certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
    State:          Running
      Started:      Tue, 30 Jan 2024 12:57:47 +0400
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8080/healthz delay=5s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/ delay=5s timeout=5s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s5q2k (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-s5q2k:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

**Comment by petewall** [comment]
Can you check the annotations on the services? I think KSM keeps `prometheus.io/scrape` on.

**Comment by petewall** [comment]
So, yeah, the Kube State Metrics and Node Exporter that this chart deploys was setting `prometheus.io/scrape`. I have a PR to turn that off:
https://github.com/grafana/k8s-monitoring-helm/pull/359

**Comment by khaykingleb** [comment]
Yes, you are right.

```
meetingmap-infra git:(decrease-monitoring-metrics-cardinality) kubectl get services -n monitoring
NAME                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                      AGE
k8s-monitoring-grafana-agent              ClusterIP   10.43.217.204   <none>        80/TCP,4317/TCP,4318/TCP,9999/TCP,9411/TCP   11h
k8s-monitoring-grafana-agent-cluster      ClusterIP   None            <none>        80/TCP,4317/TCP,4318/TCP,9999/TCP,9411/TCP   11h
k8s-monitoring-grafana-agent-logs         ClusterIP   10.43.250.210   <none>        80/TCP                                       11h
k8s-monitoring-kube-state-metrics         ClusterIP   10.43.150.184   <none>        8080/TCP                                     11h
k8s-monitoring-prometheus-node-exporter   ClusterIP   10.43.237.177   <none>        9100/TCP                                     11h
➜  meetingmap-infra git:(decrease-monitoring-metrics-cardinality) kubectl describe svc k8s-monitoring-kube-state-metrics -n monitoring
Name:              k8s-monitoring-kube-state-metrics
Namespace:         monitoring
Labels:            app.kubernetes.io/component=metrics
                   app.kubernetes.io/instance=k8s-monitoring
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=kube-state-metrics
                   app.kubernetes.io/part-of=kube-state-metrics
                   app.kubernetes.io/version=2.10.1
                   helm.sh/chart=kube-state-metrics-5.15.3
Annotations:       meta.helm.sh/release-name: k8s-monitoring
                   meta.helm.sh/release-namespace: monitoring
                   prometheus.io/scrape: true
Selector:          app.kubernetes.io/instance=k8s-monitoring,app.kubernetes.io/name=kube-state-metrics
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.150.184
IPs:               10.43.150.184
Port:              http  8080/TCP
TargetPort:        8080/TCP
Endpoints:         10.42.1.59:8080
Session Affinity:  None
Events:            <none>
```

Also I define this annotations in my Helm Chart to transition smoothly from that of [kube-prometheus-stack]:
```
  # Annotation-based autodiscovery allows for discovering metric sources solely on their annotations and does
  # not require adding any extra configuration.
  autoDiscover:
    # Enable annotation-based autodiscovery
    enabled: true


    # -- Annotations that are used to discover and configure metric scraping targets. Add these annotations
    # to your services or pods to control how autodiscovery will find and scrape metrics from your service or pod.
    annotations:
      # -- Annotation for enabling scraping for this service or pod. Value should be either "true" or "false"
      scrape: "prometheus.io/scrape"  # "k8s.grafana.com/scrape"
      # -- Annotation for setting or overriding the metrics path. If not set, it defaults to /metrics
      metricsPath: "prometheus.io/path"  # "k8s.grafana.com/metrics.path"
      # -- Annotation for setting the metrics port by number.
      metricsPortNumber: "prometheus.io/port"  # "k8s.grafana.com/metrics.portNumber"
```
