### ISSUE TITLE
Service Integration via annotations

### ISSUE THREAD

**Issue by edas-smith** [grafana/k8s-monitoring-helm#357]
Hello!

Figured id ask this here as I can't seem to find any details/information in regards to something like this. 

So this helm chart can gather metrics from 3rd party services via annotations ( which is super useful ) i.e., 
```
k8s.grafana.com/scrape: "true"
k8s.grafana.com/job: "integrations/cert-manager"
```
 
In the config of this helm chart you can specify something like this, which will add the given labels to the metrics that are being collected : 
```
externalServices:
  prometheus:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "prometheus-secret"
    externalLabels: 
      cluster: my-cluster
```
 
 The question I have is whether it is possible to for example, add some new labels specifically to the metrics being scraped from 3rd party services via annotations rather than adding them to all? For example in the above annotations for something like cert-manager, I would like to be able to add say a label called "cert-manager-label: xxx" to the cert-manager metrics. I am not entirely sure if something like this is possible / where or how it would be done?
 
 Any pointers would be greatly appreciated! Thank you
