### ISSUE TITLE
Missing externalServices.prometheus component when otlp receivers enabled but kubernetes metrics are disabled

### ISSUE THREAD

**Issue by mar4uk** [grafana/k8s-monitoring-helm#398]
**Desription**
When receivers.http.enabled=true or receivers.grpc.enabled=true but metrics.enabled=false, externalServices prometheus is missing. That leads to OTLP metrics are not exported to Prometheus

**Steps to reproduce:**
1. Turn on OTLP receivers
2. Turn off Metrics
3. Other settings don't matter
4. Generated helm command

```
helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "default" --create-namespace --values - <<EOF
cluster:
  name: k3d-app-o11y-k8s-monitoring-intg
externalServices:
  loki:
    host: https://logs-dev-002.grafana-dev.net
    basicAuth:
      username: "149099"
      password: glc_xxx
  tempo:
    host: https://tempo-dev-02-dev-us-east-0.grafana-dev.net:443
    basicAuth:
      username: "4191"
      password: glc_xxx
metrics:
  enabled: false
  cost:
    enabled: true
  node-exporter:
    enabled: false
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: k3d-app-o11y-k8s-monitoring-intg
    prometheus:
      external:
        url: https://prometheus-dev-05-dev-us-east-0.grafana-dev.net/api/prom
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-operator-crds:
  enabled: false
grafana-agent: {}
grafana-agent-logs: {}
EOF
```
**Actual result**
OTLP metrics are not exported

**Expected results**
OTLP metrics are exported
Generated helm command should contain
```
externalServices:
  prometheus:
    host: https://prometheus-dev-05-dev-us-east-0.grafana-dev.net
    basicAuth:
      username: "17907"
      password: glc_xxx
```
