### ISSUE TITLE
Adding postgres_exporter to k8s-monitoring

### ISSUE THREAD

**Issue by kenderipa** [grafana/k8s-monitoring-helm#399]
Hello,

I hava a Grafana stack (Grafana, Loki, Mimir) running on a k8s cluster. On another cluster with an application that should be monitored runs a k8s-monitroing stack. Now, I've deployed postgres-exporter on the app cluster. It works, it scrapes Metrics (can be seen in the /metrics endpoint of the postgres_exporter pod). Question is, how do I add the postgres_exporter to the k8s-monitoring configuration? It looks pretty easy with native prometheus: just adding following in prometheus.yaml:

```
  # PostgreSQL Monitoring with postgres_exporter
  - job_name: 'postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.5.21:9187']
```

Is there something similar for the k8s-monitoring helm chart?
