### ISSUE TITLE
Gathering node logs - extra volumes and mounts

### ISSUE THREAD

**Issue by kenderipa** [grafana/k8s-monitoring-helm#409]
Hello,

we're trying to gather logs from the k8s nodes. For that, we're have the following configuration in the k8s-monitoring Helm chart:
 
```
grafana-agent:
  agent:
    mounts:
      extra:
      - name: kubernetes-monitoring-telemetry
        mountPath: /etc/kubernetes-monitoring-telemetry
      - name: journal
        mountPath: /run/log/journal
        readOnly: true
      - name: machine-id
        mountPath: /etc/machine-id
        readOnly: true
      - name: kubernetes-local
        mountPath: /var/log/cce/kubernetes
        readOnly: true
      - name: yangtse
        mountPath: /var/log/cce/yangtse/yangtse-cni.log
        readOnly: true
      - name: everest-csi
        mountPath: /var/log/cce/everest-csi-driver/everest-csi-driver.log
        readOnly: true

    volumes:
      extra:
      - name: kubernetes-monitoring-telemetry
        configMap:
          name: kubernetes-monitoring-telemetry
      - name: journal
        hostPath:
          path: /run/log/journal
          type: Directory
      - name: machine-id
        hostPath:
          path: /etc/machine-id
          type: Directory
      - name: kubernetes-local
        hostPath:
          path: /var/log/cce/kubernetes
          type: Directory
      - name: yangtse
        hostPath:
          path: /var/log/cce/yangtse/yangtse-cni.log
          type: File
      - name: everest-csi
        hostPath:
          path: /var/log/cce/everest-csi-driver/everest-csi-driver.log
          type: FileOrCreate
```

Not only it doesn't work, it undeploys the agent pod itself. Could someone perhaps help us with that?
