### ISSUE TITLE
Send logs to an OTPL endpoint

### ISSUE THREAD

**Issue by jasuade** [grafana/k8s-monitoring-helm#410]
Looking at the following configuration: https://github.com/grafana/k8s-monitoring-helm/tree/main/examples/otel-metrics-service

We can see that this generated an agent river configuration that sends [Prometheus metrics to an OTPL endpoint.](https://github.com/grafana/k8s-monitoring-helm/blob/main/examples/otel-metrics-service/metrics.river) However, it does not deliver the logs via OTPL, but still using Loki endpoint:

```
  loki:
    host: https://loki.example.com
    basicAuth:
      username: 12345
      password: "It's a secret to everyone"
```

[Generated .river config](https://github.com/grafana/k8s-monitoring-helm/blob/main/examples/otel-metrics-service/logs.river)
```
loki.write "grafana_cloud_loki" {
  endpoint {
    url = nonsensitive(remote.kubernetes.secret.logs_service.data["host"]) + "/loki/api/v1/push"
    tenant_id = nonsensitive(remote.kubernetes.secret.logs_service.data["tenantId"])

    basic_auth {
      username = nonsensitive(remote.kubernetes.secret.logs_service.data["username"])
      password = remote.kubernetes.secret.logs_service.data["password"]
    }
  }
  external_labels = {
    cluster = "otel-metrics-service-test",
  }
```

We required a configuration that similarly can configure an otpl endpoint as follows:
```
otelcol.processor*...

otelcol.exporter.otlphttp "default" {
    client {
        endpoint = <OTEL endpoint>
        auth     = otelcol.auth.basic.credentials.handler
[...] // Other configuration
    }
}
otelcol.auth.basic "credentials" {
    // Retrieve credentials using environment variables.
    username = "xxx"
    password = "xxx"
}
```

**Comment by jasuade** [comment]
Hello @petewall just to double-check, with this change we can still use the values:
```
  loki:
    host: <OTPL endpoint>
    basicAuth:
      username: 12345
      password: "It's a secret to everyone"
```

But defining the OTPL endpoint directly in the host, correct?

**Comment by carlmagnusholmstrom-tomtom** [comment]
Can we also add processors here, similar to the Prometheus block?

```
    processors:
      memoryLimiter:
        enabled: true
        limit: 100MiB
```
