### ISSUE TITLE
[Question] Trouble scraping additional metrics

### ISSUE THREAD

**Issue by Sandared** [grafana/k8s-monitoring-helm#425]
Hi everyone,

I tried to scrape application specific metrics as explained [here](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/docs/ScrapeApplicationMetrics.md) but could neither get the annotation-based nor the CRD-based approach to work. I would like to ask you if I did something wrong during my setup (probably, because I'm a complete newbie to Grafana ;))

The steps that I've taken so far:
First I installed the K8s monitoring helm chart (basically copied the command from Grafana Cloud as this is only a test setup.
```
helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "default" --create-namespace --values - <<EOF
cluster:
  name: my-cluster
externalServices:
  prometheus:
    host: https://xxx.grafana.net
    basicAuth:
      username: "xxx"
      password: xxx
  loki:
    host: https://xxx.grafana.net
    basicAuth:
      username: "xxx"
      password: xxx
  tempo:
    host: https://xxx.grafana.net:443
    basicAuth:
      username: "xxx"
      password: xxx
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: my-cluster
    prometheus:
      external:
        url: https://xxx.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
grafana-agent: {}
grafana-agent-logs: {}
EOF
```

Then I tried the two different approaches to scrape the custom metrics that are exposed by my application directly on "/" at port 8282.

1) The annotation-based approach:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-namespace
annotations:
  k8s.grafana.com/scrape: "true"
  k8s.grafana.com/instance: "my-instance"
  k8s.grafana.com/metrics.portName: "metrics"
  k8s.grafana.com/metrics.path: "/"
spec:
  ports:
  - name: app
    port: 80
    targetPort: 8181
  - name: metrics
    port: 8282
    targetPort: 8282
  selector:
    app: my-app
```

2) The ServiceMonitor-based approach
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      qbinstance: my-instance
  namespaceSelector:
    matchNames:
      - mynamespace
  targetLabels:
    - qbinstance
  endpoints:
    - port: metrics
      interval: 10s
      path: /
```

For both approaches I didn't see anything specific pop up in the logs of the grafana agent. Grafana Cloud also never receives any metrics with the label "my-instance". 
Maybe I'm doing something obviously wrong here, but I really can't tell what.
I checked the documentation, but it says that the service monitor approach should be working out of the box, same goes for the annotation based approach.
The CRD for ServiceMonitor is also installed (at least it shows up when I do `k get crds | grep servicemonitor`)

Any advice is highly appreciated :)

Kind regards,
Thomas

**Comment by petewall** [comment]
Both of these approaches seem OK at first glance.

Let's try to debug the annotation approach first.

With the chart running and your service with the annotations, can you run `helm test <release name> -n <namespace>` Then get the logs for a pod called `analyze-<release>`. That'll show the services discovered by annotations:
```
discovery.relabel.annotation_autodiscovery_services
  Inputs: discovery.kubernetes.services (58)
  Outputs: discovery.relabel.annotation_autodiscovery_http (1)
```

and then later, the activity of scraping that service:
```
prometheus.scrape.annotation_autodiscovery_http
  Inputs: 1
  - cert-manager.cert-manager.svc:9402
  Scrapes: 1
  - URL: http://cert-manager.cert-manager.svc:9402/metrics
    Health: up
    Last scrape: 2024-03-19T22:04:40.243234053Z (4.58325ms)
```

In my example, I'm scraping Cert Manager using annotations. See if your service shows up. It should be indicated by a non-zero output in the discovery.relabel.annotation_autodiscovery_http component and an entry in the prometheus.scrape.annotation_autodiscovery_http component.

**Comment by petewall** [comment]
You'll find information about the ServiceMonitors in there as well. From my example:
```
prometheus.operator.servicemonitors.service_monitors
  Discovered: 1
  - ServiceMonitor: loki/loki
  Scrapes: 1
  - URL: http://10.244.1.14:3100/metrics
    Health: up
    Last scrape: 2024-03-19T22:04:53.95581167Z (33.363083ms)
```

**Comment by Sandared** [comment]
Hi Pete,

thanks for your quick answer.
This is super strange. I did not change anything in my setup, but after I ran the tests that you told me the metrics started to show up in Grafana Cloud. 
Both approaches also were discovered by the tests as said above, i.e., ServiceMonitor and the annotations were discovered.

Thank you so much :)

**Comment by petewall** [comment]
Yeah, that shouldn't make a difference. I'd only worry about YAML and formats if you've got numbers of things that I thinks feels like booleans (true, on, yes are all interpreted as boolean yes). If in doubt, quotes never hurt.

**Comment by petewall** [comment]
Glad you got things working!

**Comment by ubbeK** [comment]
I have been trying to get the auto discovery feature to work but I wont. I am using the latest chart version at `0.12.2`. 


My pod is enabled through the following annotations
```
# pod annotation
annotations:
    sidecar.istio.io/inject: "false"
    k8s.grafana.com/scrape: "true"
    k8s.grafana.com/instance: "aspnet-front-override" # annotation for overriding the instance label
    k8s.grafana.com/metrics.path: "/metrics" # annotation for setting or overriding the metrics path. if not set, it defaults to /metrics
    k8s.grafana.com/metrics.portnumber: "8080" # annotation for setting the metrics port by number.
    k8s.grafana.com/metrics.scheme: "http" # annotation for setting the metrics scheme, default: http.
```

I do get a positive result from `helm test <release name> -n <namespace>` command
```
prometheus.scrape.annotation_autodiscovery_http
  Inputs: 1
  - 10.244.0.52:8080
  Scrapes: 1
  - URL: http://10.244.0.52:8080/metrics
    Health: up
    Last scrape: 2024-03-22T14:02:25.7374658Z (1.581ms)
```    

k8s-monitoring yaml configuration is as follows

```
metrics:
  scrapeInterval: 60s
  enabled: true
  autoDiscover:
    enabled: true
    metricsTuning:
      includeMetrics: ["c10r_metrics_requests_count_total", "process_runtime_dotnet.*", "kestrel_.*", "http_server.*", "http_client.*"]
      excludeMetrics: []
```

Which results in the following Grafana agent configmap

```
prometheus.relabel "annotation_autodiscovery" {
  rule {
    source_labels = ["__name__"]
    regex = "up|c10r_metrics_requests_count_total|process_runtime_dotnet.*|kestrel_.*|http_server.*|http_client.*"
    action = "keep"
  }
  forward_to = [prometheus.relabel.metrics_service.receiver]
}
```

I am kind of getting out of ideas where to debug now. @petewall Do you have any pointers?
