### ISSUE TITLE
Format issue with otelcol.processor.filter (traces.span)

### ISSUE THREAD

**Issue by Lp-Francois** [grafana/k8s-monitoring-helm#431]
Hello!

I am currently trying to drop all health check probes from our traces as it generates a lot of noise (💸) and is not helpful.

For this I am configuring the values.yaml the following way:

```yaml
traces:
  enabled: true
  # Settings related to traces ingested via receivers
  receiver:
    # -- Apply a filter to traces received via the OTLP or OTLP HTTP receivers. ([docs](https://grafana.com/docs/agent/latest/flow/reference/components/otelcol.processor.filter/))
    filters:
      span:
        -  '"attributes[\"http.route\"] == \"/livez\"",'
        -  '"attributes[\"http.route\"] == \"/health\"",'
        -  '"attributes[\"http.route\"] == \"/readyz\"",'

# ...
```

which generates the following:

```hcl
// ...
otelcol.processor.filter "default" {
  error_mode = "ignore"
  traces = {
    span = [
        "attributes[\"http.route\"] == \"/livez\"",
        "attributes[\"http.route\"] == \"/readyz\"",
        "attributes[\"http.route\"] == \"/health\"",
    ]                                         <-- This is the line 145 highlighted by the error
  }

  output {
    metrics = [otelcol.processor.batch.batch_processor.input]
    logs = [otelcol.processor.batch.batch_processor.input]
    traces = [otelcol.processor.batch.batch_processor.input]
  }
}
// ...
```

The agent fails with:

```
Error: /etc/agent/config.river:145:6: missing ',' in field list
Error: could not perform the initial load successfully
Error: /etc/agent/config.river:145:6: missing ',' in field list
```

I reproduced in local with saving the generated config to a file `river` and ran:  `brew install grafana-agent && AGENT_MODE=flow grafana-agent fmt file.river`.

But I don't see any issue with the lines, in the generated files, other objects or arrays don't have comma and the agent doesn't complain 🤔 

Any idea what could be the issue?
