### ISSUE TITLE
How to do tail sampling to drop health probes?

### ISSUE THREAD

**Issue by Lp-Francois** [grafana/k8s-monitoring-helm#443]
Hello,

I tried in a [previous issue](https://github.com/grafana/k8s-monitoring-helm/issues/431#issuecomment-2020458505) to find a solution to my current problem: how to drop the traces coming from Kubernetes probes (readiness, liveness)? Sadly, using the span filter creates inconsistent traces, missing the root span as it drops the root.

Is there a way of doing tail sampling with this helm chart, in order to drop the full trace containing an health probe? (/health, /live or /ready)?

Or how would you recommend to proceed to drop these traces?

**Comment by t00mas** [comment]
Hello François, I agree with you about moving to tail sampling to achieve your goal, instead of filtering.

Are you trying to get to something that looks like this?

```yaml
processors:
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
         {
            name: drop-probes-policy,
            type: string_attribute,
            string_attribute: {
              key: http.route,
              values: [\/livez, \/readyz, \/health],
              enabled_regex_matching: true,
              invert_match: true
            }
         }
      ]
```
