### ISSUE TITLE
Example Request: Tolerations

### ISSUE THREAD

**Issue by skl** [grafana/k8s-monitoring-helm#486]
It'd be great to have an example showing how to apply tolerations to the various deployments and subcharts.

**Comment by skl** [comment]
Here's the current defaults for all charts, any changes need to be done in addition to the below, otherwise the defaults would be removed:

```yaml
test:
  tolerations: []

configAnalysis:
  tolerations: []

alloy:
  controller:
    tolerations:
      - effect: NoSchedule
        operator: Exists

alloy-events:
  controller:
    tolerations:
      - effect: NoSchedule
        operator: Exists

alloy-logs:
  controller:
    tolerations:
      - effect: NoSchedule
        operator: Exists

alloy-profiles:
  controller:
    tolerations:
      - effect: NoSchedule
        operator: Exists

kube-state-metrics:
  tolerations: []

prometheus-node-exporter:
  tolerations:
    - effect: NoSchedule
      operator: Exists

prometheus-windows-exporter:
  tolerations:
    - effect: NoSchedule
      operator: Exists

opencost:
  opencost:
    tolerations: []
```
