### ISSUE TITLE
Set dnsConfig to change ndot value

### ISSUE THREAD

**Issue by eric-freewill** [grafana/k8s-monitoring-helm#488]
Is there a way to set the dnsConfig settings to lower the ndots value? I'm experiencing random timeouts when hitting Grafana cloud external endpoints. I've been able to fix some of these by adding a dot to the end of the endpoint; however, opencost for instance is hitting AWS endpoints that I can't modify.

Example:
```
spec:
  dnsConfig:
    options:
      - name: ndots
        value: "2"
```
