### ISSUE TITLE
Opencost UI no values

### ISSUE THREAD

**Issue by marquesj2-ppb** [grafana/k8s-monitoring-helm#490]
Hi, 
Can't seem to get opencost to read any information when using `0.10.3` or `1.0.2` of this chart

Seems to be same case as #263 but can't get it to solve.
```
  opencost:
    opencost:
      ui:
        enabled: true
      exporter:
        defaultClusterId: 'Hrk8sDEV'
      prometheus:
        existingSecretName: prometheus-k8s-monitoring
        external:
          url: 'https://prometheus-us-central1.grafana.net/api/prom'
```
![image](https://github.com/grafana/k8s-monitoring-helm/assets/79195686/e7c84ba5-3fe8-4968-9548-c9edeb47c567)
