### ISSUE TITLE
Labels missing from logs

### ISSUE THREAD

**Issue by thecodeassassin** [grafana/k8s-monitoring-helm#501]
Labels are not being sent to loki:
![image](https://github.com/grafana/k8s-monitoring-helm/assets/939775/2a9680b2-84d2-4be3-8609-d990d2ca9b2c)

These labels are missing:
![image](https://github.com/grafana/k8s-monitoring-helm/assets/939775/bf31d1cb-61e2-47a9-85d4-f3d6ca2a6e45)

Config used:

```yaml

    cluster:
        name: test123
      externalServices:
        prometheus:
          writeEndpoint: /api/v1/push
          queryEndpoint: /api/v1/query

          basicAuth:
            usernameKey: mimir_username
            passwordKey: mimir_password
          secret:
            create: false
            name: "mimir-credentials"
            namespace: "kube-system"
        loki:
          queryEndpoint: /loki/api/v1/query
          writeEndpoint: /loki/api/v1/push
          basicAuth:
            usernameKey: loki_username
            passwordKey: loki_password
          secret:
            create: false
            name: "loki-credentials"
            namespace: "kube-system"
      metrics:
        enabled: true
        cost:
          enabled: true
        node-exporter:
          enabled: true
      logs:
        enabled: true
        pod_logs:
          enabled: true
        cluster_events:
          enabled: true
      traces:
        enabled: false
      receivers:
        grpc:
          enabled: true
        http:
          enabled: true
        zipkin:
          enabled: true
      opencost:
        enabled: false
      kube-state-metrics:
        enabled: true
      prometheus-node-exporter:
        enabled: true
      prometheus-operator-crds:
        enabled: true
      alloy: {}
      alloy-logs: {}
```
