### ISSUE TITLE
Having "true" extra ports for faro receiver

### ISSUE THREAD

**Issue by doanbutar** [grafana/k8s-monitoring-helm#507]
As of now, we can't just specify additional ports for Faro, but also need to include Otel ports; otherwise we get a validation error like: 
```
Error: UPGRADE FAILED: execution error at (k8s-monitoring/templates/hooks/validate-configuration.yaml:123:8): OTLP gRPC port not opened on Grafana Alloy.
```

In order to receive data over this protocol, port 4317 needs to be opened on Alloy. For example, set this in your values file:
```
alloy:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"
      - name: "faro"
        port: 12347
        targetPort: 12347
        protocol: "TCP"
```

This seems like including the settings that are default for k8s-monitoring chart in our helm values. E.g. if for whatever reason this changes in some way (for example, for some reason you chart requires another "required" port), we'll have to change our config. 

Makes version upgrades more difficult. Hence the name `extra` ports seems misleading (though looking at the chart logic I understand why they are called "extra" in the alloy chart). Basically, what would be valuable is having "true" extra ports (in this case "extra" from the k8s-monitoring chart perspective, not from alloy chart).
