### ISSUE TITLE
Why there are so may alloy-logs agents when `gatherMethod:  api`?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [grafana/k8s-monitoring-helm#542]
I've set:
```tf
    logs = {
      pod_logs = {
        gatherMethod = "api"
      }
    }

    alloy-logs = {
      alloy = {
        clustering = {
          enabled = true
        }
        mounts = {
          varlog = false
        }
      }
    }
```
but there still seems to be 1 pod per node and I am not sure why, since it is using API instead of varlog I expected to see 2 pods at most

**Comment by bentonam** [comment]
@gytis-ivaskevicius when using `gatherMethod: api` the controller type should be changed from `daemonset` which is the default for the alloy sub-charts to `deployment` 

```yaml
alloy-logs:
  alloy:
    clustering: {enabled: true}
    mounts:
      varlog: false
  controller:
    replicas: 2
    type: deployment
```
