### ISSUE TITLE
Traces and Profiles missing extraConfig block

### ISSUE THREAD

**Issue by bentonam** [grafana/k8s-monitoring-helm#565]
Add support for traces and profiles `extraConfig` block.

**Comment by geertn** [comment]
Good to see you are working on this! Is it possible to Cherry pick the fix and merge this already? Currently we are working around this "bug" by patching the configmap after deployment. It would be great if we can leverage your fix without having to patch our helm chart locally.

**Comment by petewall** [comment]
Currently we have:

```yaml
extraConfig: ... # Adds config to the "alloy" instance
logs:
  extraConfig: ... # Adds config to the "alloy-logs" instance
  cluster_events:
    extraConfig: ... # Adds config to the "alloy-events" instance
  journal:
    extraConfig: ... # Not used anywhere currently
```

We could add:
```
profiles:
  extraConfig: ... # Adds config to the "alloy-profiles" instance
```

Trace receivers exist on the alloy instance, so the top-level `extraConfig` should be sufficient.

**Comment by petewall** [comment]
So, a few options:

1. Smallest change:
Add exttraConfig for profiles, the only place that is missing the ability:
```yaml
profiles:
  extraConfig: ... # Adds config to the "alloy-profiles" instance
```

2. More logical sense, but breaking:
Deprecate the existing extraConfigs and instead put them inside the alloy instances. to make it clearer where they're being deployed:

```yaml
alloy:
  extraConfig: ...
alloy-events:
  extraConfig: ...
alloy-logs:
  extraConfig: ...
alloy-profiles:
  extraConfig: ...
```

**Comment by geertn** [comment]
My thoughts as a user:
Both options would work for me but option 2 seems more logical. Maybe overthinking but since the `alloy` block seems to already deal with configs 

```
alloy:
  alloy:
    extraConfig: ...
alloy-events:
  alloy:
    extraConfig: ...
alloy-logs:
  alloy:
    extraConfig: ...
alloy-profiles:
  alloy:
    extraConfig: ...
```

Afterburner: is there a reason `alloy` is named `alloy-metrics`?
