### ISSUE TITLE
Allow for pod logs to use custom discovery list

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#57]
Currently, there isn't a clean way to get pod logs from a subset of pods (i.e. only from a certain set of namespaces).

We should make a way to use a different discovery component.

Perhaps by giving a custom component:

```yaml
logs:
  pod_logs:
    target: "discovery.kubernetes.my_pods_for_logs.targets"

extraConfig: |-
  discovery.kubernetes "my_pods_for_logs" {
    role = "pod"
    namespaces {
      names = ["mynamespace"]
    }
  }
```

**Comment by petewall** [comment]
## Proposal 0: (no-op)
1. Turn logs off `logs: { "enabled": false }`
2. `extraConfig` everything.
PRO: it works today
CON: it's a hack and doesn't get any updates.

## Proposal 1: targetName
This is what's above
1. Leave the all pods target (used by node exporter and windows exporter)
2. Allow to use a different discovery.kubernetes target
3. Define that component in extra config
PRO: more flexible than proposal 0
CON: Still using extra config, which kinda feels like a junk drawer

## Proposal 2: Everything gets `discovery.kubernetes` targets
Each metric and logs system gets a distinct discovery.kubernetes component, and they can each add modifiers to them
PRO: Lots of flexibility
CON: Lots of open watches to the API service

## Proposal 3: Allow for relabelingRules for each service
Each metric and logs system is allowed to define custom relabeling rules. This would let them filter by namespace if needed. Similar to the `metrics.cost.labelMatchers` of today, but allow for full relabeling rules.

**Comment by petewall** [comment]
As of now, I'm leaning towards proposal 3.

**Comment by skl** [comment]
@petewall I'm guessing 3 is also compatible with the new split agent. What does this mean for the chart, new values for each service?

**Comment by petewall** [comment]
Personally, I'm tempted to have:
```yaml
metrics:
  <some metric source>:
    extraRelabelingRules: ""          # Custom flow rules for discovery.relabel
    extraMetricRelablingRules: "" # Custom flow rules for prometheus.relabel
logs:
  <some logs source>:
    extraRelabelingRules: ""      # Custom flow rules for discovery.relabel
    extraLogProcessingRules: "" # Custom flow rules for loki.process
```

That'd roll in #50 as well as bring flexibility for all metric and log sources.
