### ISSUE TITLE
Zipkin only receiver causes log issue

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#576]
If logs are enabled, and zipkin, but not otlp receivers are enabled, then we build the pipeline for logs, but some logs components are missing.

```yaml
cluster:
  name: my-cluster
externalServices:
  prometheus:
    host: <PROM_HOST>
    basicAuth:
      username: xxx
      password: xxx
  loki:
    host: <LOKI_HOST>
    basicAuth:
      username: xxx
      password: xxx
  tempo:
    host: <TEMPO_HOST>
    basicAuth:
      username: xxx
      password: xxx

metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true

logs:
  enabled: true
  pod_logs:
    enabled: false
  cluster_events:
    enabled: true

traces:
  enabled: true

receivers:
  grpc:
    enabled: false
  http:
    enabled: false
  zipkin:
    enabled: true

opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: my-cluster
  prometheus:
    external:
      url: <PROM_HOST>/api/prom

kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: false
alloy: {}
alloy-events: {}
alloy-logs: {}
```
