### ISSUE TITLE
How to enable Service Graph

### ISSUE THREAD

**Issue by dicki** [grafana/k8s-monitoring-helm#597]
I'm currently using this Helm chart to monitor our clusters but for can't seem to understand how to enable the Service Graph to display any data.
I have Alloy hooked up and pushing traces and metrics to Tempo and Prometheus in my Grafana Cloud instance.

Is it possible for someone here to help me out?

Below are my values for the Helm release.
```

values.yaml
  values:
    cluster:
      name: qa-cluster
    externalServices:
      loki:
        host: https://logs-prod-025.grafana.net
        basicAuth:
          username: "xx"
          password: xxx
      tempo:
        host: https://tempo-prod-18-prod-eu-north-0.grafana.net:443
        basicAuth:
          username: "xxx"
          password: xxx
      prometheus:
        host: https://prometheus-prod-39-prod-eu-north-0.grafana.net
        basicAuth:
          username: "xxx"
          password: xxx
    metrics:
      enabled: true
      cost:
        enabled: false
      extraMetricRelabelingRules: |-
        rule {
            source_labels = ["namespace"]
            regex = "^$|apps"
            action = "keep"
        }
      podMonitors:
        namespaces: [apps]
      probes:
        namespaces: [apps]
      serviceMonitors:
        namespaces: [apps]
    logs:
      enabled: true
      pod_logs:
        enabled: true
        discovery: "all"
        namespaces:
          - "apps"
      cluster_events:
        enabled: false
    traces:
      enabled: true
    opencost:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-operator-crds:
      enabled: true

```
