### ISSUE TITLE
Add global labels and annotations for all pods.

### ISSUE THREAD

**Issue by marcinpro1** [grafana/k8s-monitoring-helm#601]
There is an option to add extraAnnotation for validator pods and thats it.
For situation like adding additional info to pods (labels or annotation) required by cluster policy (eg. kyverno), deployment will fail.

**Comment by petewall** [comment]
Which pods are missing the ability to set annotations or labels?

**Comment by marcinpro1** [comment]
alloy, kube-state-metrics, node-exporter - these ones i've checked by trying to deploy them and they don't have the option.
The ramining I'm not sure. I've based my issue on those 3 and assumed that whichever don't have extraAnnotation option, also don't have the option to add extra labels or annotations.

**Comment by petewall** [comment]
For [alloy](https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy):
```yaml
alloy:
  controller:
    podAnnotations: {}
    podLabels: {}
```
(repeat for `alloy-logs`, `alloy-events`, `alloy-profiles`)

For [kube-state-metrics](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics):
```yaml
kube-state-metrics:
  customLabels: {}
  podAnnotations: {}
```

For [Node Exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter):
```yaml
prometheus-node-exporter:
  podAnnotations: {}
  podLabels: {}
```

The k8s-monitoring Helm chart uses subcharts to deploy these resources, so to pass a value down to the subchart, you just have to put those values inside a key of the name of the subchart. So, any values you want to send to the `kube-state-metrics` subchart go inside the `kube-state-metrics` section of the k8s-monitoring chart.
