### ISSUE TITLE
Active Series Ingestion Rate per minute doubling

### ISSUE THREAD

**Issue by edas-smith** [grafana/k8s-monitoring-helm#624]
Hello!

I am currently on version **0.9.2** of this Grafana helm chart and have now started the upgrade process to the latest version - v1.3.0 which for the most part is very easy to do. I am using Grafana Cloud.

However, after upgrading the version I did notice that the rate at which active time series are being ingested into Grafana almost doubled, for example:
![Screenshot 2024-07-08 at 10 52 22](https://github.com/grafana/k8s-monitoring-helm/assets/117644805/128b36ea-173e-4027-baac-a66b7bd81f96)

Now I did pin-point in which version this sudden spike began and it is in **0.9.3** though there really didn't seem to be that much difference between **0.9.2** and **0.9.3** as seen here : https://github.com/grafana/k8s-monitoring-helm/compare/v0.9.2...v0.9.3 

Did anyone run into a similar issue like this? Any pointers to why this could be the case would be greatly appreciated as I have spent a bit of time on this now and can't put my finger on what the problem could be.

Thank you!

**Comment by skl** [comment]
@edas-smith can you post your redacted values file for `0.9.3`? Also, just as a sanity check, please confirm you're runnning only a single release of `k8s-monitoring-helm` 😄

**Comment by edas-smith** [comment]
Hi @skl thanks so much for the quick response!

So this is the values.file I am using for **0.9.2** though I was/have been using the exact same one for **0.9.3** too :) 
```
cluster:
  name: "xx"
externalServices:
  prometheus:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "xx"
    externalLabels: 
      cluster: xx

    writeRelabelConfigRules: |-
      write_relabel_config {
        source_labels = ["__name__"]
        regex = "erlang_vm_msacc_timers_seconds_total|erlang_vm_msacc_sleep_seconds_total|erlang_vm_msacc_send_seconds_total|"
        action = "drop"
      }

           
  loki:
    hostKey: host
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: "xx"
metrics:
  scrapeInterval: 60s 
    
  cost:
    enabled: false 
  
  cadvisor: 
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics:
      - machine_cpu_cores 
      - container_cpu_usage_seconds_total
      - container_memory_working_set_bytes

  kubelet: 
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics:
      - kubelet_volume_stats_used_bytes
      - kubelet_volume_stats_available_bytes
      - kubelet_node_name
      - kubelet_volume_stats_capacity_bytes

  kube-state-metrics:
    metricsTuning:
      useDefaultAllowList: false
      includeMetrics:
      - kube_persistentvolumeclaim_status_phase
      - kube_persistentvolumeclaim_info
      - kube_pod_container_resource_requests
      - kube_pod_status_phase
      - kube_pod_status_reason
      - kube_job_status_succeeded
      - kube_job_status_active
      - kube_job_status_failed
      - kube_pod_container_resource_limits
      - kube_pod_container_resource_requests
      - kube_pod_container_status_waiting_reason
      - kube_pod_info
      - kube_deployment_metadata_generation
      - kube_statefulset_metadata_generation
      - kube_pod_annotations
      - kube_node.*
      - kube_cronjob_info
  
  opencost:
    enabled: false
  
  podMonitors:
    enabled: false
  
  probes:
    enabled: false
  
  kubernetesMonitoring:
    enabled: false


kube-state-metrics:
  metricLabelsAllowlist:
    - nodes=[workload-type,kubernetes.io/hostname]


opencost:
  enabled: false
  
grafana-agent:
  controller:
    nodeSelector: 
      workload-type: xx

    tolerations:
    - key: workload-type
      value: "xx"
      effect: NoSchedule

extraObjects: 
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: xx
    spec:
      refreshInterval: 100h
      secretStoreRef:
        name: xx
        kind: ClusterSecretStore
      target:
        name: xx
        creationPolicy: Owner
      dataFrom:
      - extract:
          conversionStrategy: Default	
          decodingStrategy: None
          key: xx
          metadataPolicy: None

  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: xx
    spec:
      refreshInterval: xx
      secretStoreRef:
        name: xx
        kind: ClusterSecretStore
      target:
        name: xx
        creationPolicy: Owner
      dataFrom:
      - extract:
          conversionStrategy: Default	
          decodingStrategy: None
          key: xx
          metadataPolicy: None
```

Haha yes in terms of the sanity check I can 100% confirm I am are running only that release :) ( using ArgoCD ).
