### ISSUE TITLE
Error deploying `grafana-k8s-monitoring` from helm chart

### ISSUE THREAD

**Issue by pedrolacerda** [grafana/k8s-monitoring-helm#635]
After running the suggested command to deploy `grafana-k8s-monitoring` helm chart, it's stuck while pulling the image from `ghcr.io`

### Command:

```bash
helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "grafana-alloy" --create-namespace --values config.yaml
```

### Error message

```bash
Release "grafana-k8s-monitoring" does not exist. Installing it now.
Error: release grafana-k8s-monitoring failed, and has been uninstalled due to atomic being set: failed pre-install: 1 error occurred:
        * timed out waiting for the condition
```

### Pod status
```bash
kubectl get pods                                     
NAME                              READY   STATUS             RESTARTS   AGE
validate-grafana-k8s-monitoring   0/1     ImagePullBackOff   0          13m
```

### `config.yaml` file

```yaml
cluster:
  name: grafana-demo
externalServices:
  prometheus:
    host: https://prometheus-prod-40-prod-sa-east-1.grafana.net
    basicAuth:
      username: <redacted>
      password: <redacted>
  loki:
    host: https://logs-prod-024.grafana.net
    basicAuth:
      username: <redacted>
      password: <redacted>
  tempo:
    host: https://tempo-prod-17-prod-sa-east-1.grafana.net:443
    basicAuth:
      username: <redacted>
      password: <redacted>
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
  grafanaCloudMetrics:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: grafana-demo
    prometheus:
      external:
        url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}
```

Is anyone else receiving this error? I've also tried to overwrite the image registry and tags, no success, though:

```yaml title='config.yaml'
global:
  image:
    registry: ghcr.io
    image: grafana/k8s-monitoring-test
    tag: 1.4.1
configAnalysis:
  image:
    registry: ghcr.io
    image: grafana/k8s-monitoring-test
    tag: 1.4.1
```
