### ISSUE TITLE
OpenTelemetry endpoint is not capturing any k8sattributes like namespace, pod, container

### ISSUE THREAD

**Issue by pavelpikatamcs** [grafana/k8s-monitoring-helm#672]
Our applications produce OTEL metrics and send them to local alloy endpoint exposed via this chart.

The metrics only contain attributes defined by the applications themselves, and any Kubernetes metadata is not included, e.g. namespace, pod, container are all missing, so it's very difficult to identify where the metrics are actually coming from.

Is there a way to configure this via this chart, or maybe have this enabled by default?

Chart version 1.4.4
Here is our helm values (traces and logs config removed as irrelevant):

```
cluster:
  name: eu1-aks-dev-1
alloy:
  alloy:
    stabilityLevel: "experimental"
    uiPathPrefix: /agent
    clustering:
      enabled: true
  controller:
    replicas: 1
    
  prometheus:
    host: "redacted"
    writeEndpoint: "/api/v1/push"
    tenantId: "redacted"
    authMode: basic
    basicAuth:
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: external-mimir-creds
      namespace: monitoring
opencost:
  enabled: false
metrics:
  enabled: true
    
receivers:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true

```

Cluster info:
1.29.5, AKS with Overlay CNI
