### ISSUE TITLE
LiveDebugging doesn't work even with experimental stabilityLevel

### ISSUE THREAD

**Issue by pavelpikatamcs** [grafana/k8s-monitoring-helm#673]
Chart version: 1.4.4

Piece of Chart values:

```
cluster:
  name: eu1-aks-dev-1
alloy:
  alloy:
    stabilityLevel: "experimental"
    uiPathPrefix: /agent
    clustering:
      enabled: true
    enableReporting: false
  config:
    liveDebugging:
      enabled: true
```

Even with this config, Alloy UI still displays error:

`Error: Failed to connect, status code: 500, reason: the live debugging service is disabled. Check the documentation to find out how to enable it`
