### ISSUE TITLE
Some kube-state-metrics are missing

### ISSUE THREAD

**Issue by khaykingleb** [grafana/k8s-monitoring-helm#687]
Hi, 

I'm using 1.4.6 Helm chart version and have noticed that some `kube-state-metrics` metrics are missing (e.g., `kube_node_annotations`, `kube_node_labels`, etc.), even though annotations and labels are present on the nodes. Here are some examples of what I'm seeing in the `metrics` endpoint:
```
# HELP kube_namespace_status_condition The condition of a namespace.
# TYPE kube_namespace_status_condition gauge
# HELP kube_node_annotations Kubernetes annotations converted to Prometheus labels.
# TYPE kube_node_annotations gauge
# HELP kube_node_created [STABLE] Unix creation timestamp
# TYPE kube_node_created gauge
kube_node_created{node="nu"} 1.722859996e+09
kube_node_created{node="psi"} 1.722856522e+09
kube_node_created{node="xi"} 1.722854448e+09
kube_node_created{node="ip-10-0-0-121"} 1.701279673e+09
kube_node_created{node="ip-10-0-0-185"} 1.70127964e+09
kube_node_created{node="ip-10-0-0-22"} 1.701279688e+09
kube_node_created{node="mu"} 1.722858318e+09
# HELP kube_node_labels [STABLE] Kubernetes labels converted to Prometheus labels.
# TYPE kube_node_labels gauge
# HELP kube_node_role The role of a cluster node.
# TYPE kube_node_role gauge
kube_node_role{node="ip-10-0-0-121",role="etcd"} 1
kube_node_role{node="ip-10-0-0-121",role="control-plane"} 1
kube_node_role{node="ip-10-0-0-121",role="master"} 1
kube_node_role{node="ip-10-0-0-185",role="etcd"} 1
kube_node_role{node="ip-10-0-0-185",role="control-plane"} 1
kube_node_role{node="ip-10-0-0-185",role="master"} 1
kube_node_role{node="ip-10-0-0-22",role="master"} 1
kube_node_role{node="ip-10-0-0-22",role="control-plane"} 1
kube_node_role{node="ip-10-0-0-22",role="etcd"} 1
```

I believe this might be related to this issue: https://github.com/kubernetes/kube-state-metrics/issues/1968

**Comment by petewall** [comment]
kube-state-metrics does not enable the "___labels" or "___annotations" metrics by default. Those metrics tend to have high cardinality. That being said, the node labels and annotations don't tend to change much at all.

You can enable this now by making these two changes:
```
metrics:
  kube-state-metrics:
    enabled: true
    metricsTuning:
      useDefaultAllowList: true
      includeMetrics:
        - kube_node_annotations
        - kube_node_labels

kube-state-metrics:
  metricAnnotationsAllowList
    - nodes=[*]
  metricLabelsAllowlist:
    - nodes=[*]
```

> I believe this might be related to this issue: https://github.com/kubernetes/kube-state-metrics/issues/1968

As they state in that issue, it's not a bug, just not enabled by default.
