### ISSUE TITLE
Add ARM64 toleration to Alloy, KSM, OpenCost

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#709]
GKE clusters with mixed ARM64 and AMD64 architectures will put a taint on the ARM64 nodes: `kubernetes.io/arch=arm64:NoSchedule`

This prevents mutliplatform-capable workloads like Alloy, kube-state-metrics, OpenCost from scheduling on those nodes. We should add the toleration by default.

https://cloud.google.com/kubernetes-engine/docs/how-to/prepare-arm-workloads-for-deployment#multi-arch-schedule-any-arch

**Comment by maxlemieux** [comment]
The `configValidator` pod also seems to need tolerations in this environment.

Here are example settings that work around this issue today:

```
alloy:
  controller:
    tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
alloy-events:
  controller:
    tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
kube-state-metrics:
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
opencost:
  opencost:
    tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
configValidator:
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "arm64"
      effect: "NoSchedule"
```
