### ISSUE TITLE
Extend securityContext options for NodeExporter

### ISSUE THREAD

**Issue by maxiar** [grafana/k8s-monitoring-helm#729]
Hi!, Excelent works! Please can add the securityContext configuration for prometheus node exporter yaml, in order to avoid errors with suse linux node clusters..

I need to add this, to the node exporter:

securityContext: 
    seLinuxOptions: 
      type: spc_t

Source: https://www.suse.com/es-es/support/kb/doc/?id=000020747

Thanks!

**Comment by petewall** [comment]
You can do that yourself by setting:
```
prometheus-node-exporter:
  securityContext: 
    seLinuxOptions: 
      type: spc_t
```

I don't want to add this by default, because, as the article you posted says:

> this would give the container super-privileged access which is NOT recommended
