### ISSUE TITLE
Validation error in traces alloy configuration

### ISSUE THREAD

**Issue by davidcurrie** [grafana/k8s-monitoring-helm#731]
Attempting to install chart version 1.5.0 using the following values:

```
cluster:
  name: "test"

externalServices:
  prometheus:
    host: xxx
    sendNativeHistograms: true
  loki:
    host: yyy
    tenantId: "default"
  tempo:
    host: zzz
    tenantId: "default"
    protocol: "otlphttp"

alloy:
  controller:
    replicas: 3
  alloy:
    resources:
      requests:
        cpu: 100m

prometheus-operator-crds:
  enabled: false

metrics:
  enabled: false

kube_state_metrics:
  enabled: false

node-exporter:
  enabled: false

kubelet:
  enabled: false

cadvisor:
  enabled: false

cost:
  enabled: false

podMonitors:
  enabled: false

probes:
  enabled: false

serviceMonitors:
  enabled: false

kubernetesMonitoring:
  enabled: false

logs:
  enabled: false

traces:
  enabled: true
```

Results in validation failing:
```
Validating Grafana Alloy config file
Error: /etc/alloy/config.alloy:114:38: component "remote.kubernetes.secret.metrics_service.data" does not exist or is out of scope

113 |     headers = {
114 |       "X-Scope-OrgID" = nonsensitive(remote.kubernetes.secret.metrics_service.data["tenantId"]),
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
115 |     }
```

Without digging very deeply, should [this line](https://github.com/grafana/k8s-monitoring-helm/blob/2284be968053536c7988cee5a459a557ad8fd4d5/charts/k8s-monitoring/templates/alloy_config/_traces_service.alloy.txt#L26) be using `traces_service`?
