### ISSUE TITLE
Question: Forking dataflow in logs configuration

### ISSUE THREAD

**Issue by cydergoth** [grafana/k8s-monitoring-helm#735]
Hi 

I had a small question about how best to fork the dataflow for logs in Alloy. Our use case is that some of our logs have a _huge_ (>2MiB) embedded JSON blob in them (don't ask :-( ) and we want to record that in S3 whilst also sending the remainder of the log line to Loki. So there is the OTEL AWSS3 exporter, all good, and there is the log_service exporter for Loki, also good, and we can target multiple receivers from a flow block, also good. 

My thoughts are to fork the data flow to send to two different pipelines, one of which extracts just the JSON, converts to OTEL, and forwards to the S3 exporter, and the other extracts the rest of the log line and forwards to Loki. Each pipeline would drop the part of the log it doesn't handle. All of this is feasible in River I believe. The sticking point for me is how best to configure that set of pipelines in this helm chart as it doesn't seem as if we can modify the targets of the pod logs or loki process block to fork the data stream. I _believe_ I could duplicate the entire stream for logs in the "extraConfig" section but that seems to be a bit cumbersome although the block *is* templated (thanks!). Also we would then have a completely parallel logs pipeline, unless there is an easy way to turn off the original one.

````
             pod
              |
            process
           /       \
         /           \ 
     process        process
       |               |
      OTEL      loki_logs_service
       |
  S3 Exporters
````

Do you have any recommendations as to how best to handle this scenario? 

Thanks

**Comment by petewall** [comment]
This should now be nearly possible in the v2 version of this chart!
You'd define both destinations, and use the destination filters and stages to drop the data that it doesn't use.

```
destinations:
- name: loki
  type: loki
- name: s3
  type: otlp
  logs: {enabled: true}
  metrics: {enabled: false}
  traces: {enabled: false}

podLogs:
  enabled: true
  extraLogProcessingStages: |
    stage.match ..... // Extra stages to identify the JSON body logs and tag them somehow
```

The trick then would be filtering each destination only for the logs that it should handle. I have some plans about that that we can explore...
