### ISSUE TITLE
alloy-events still trying to be created even with logs.cluster_events.enable=false

### ISSUE THREAD

**Issue by defanator** [grafana/k8s-monitoring-helm#745]
Hi. We are migrating some installations from grafana-k8s-monitoring 1.4.8 to 1.5.2, and noticed that a configuration like this:

```
    logs:                                                                       
      enabled: true                                                             
      cluster_events:                                                           
        enabled: false                                                          
      pod_logs:                                                                 
        gatherMethod: api                                                       
        namespaces:
          - foo
```

ends up with broken chart installation:

```
96s (x10 over 5m46s)   Warning   FailedMount            Pod/grafana-k8s-monitoring-alloy-events-546856dcb6-8k6p2    MountVolume.SetUp failed for volume "config" : configmap "grafana-k8s-monitoring-alloy-events" not found
45s                    Warning   InstallFailed          HelmRelease/grafana-k8s-monitoring                          Helm install failed for release monitoring/grafana-k8s-monitoring with chart k8s-monitoring@1.5.2: client rate limiter Wait returned an error: context deadline exceeded
```

This PR seems to be a breaking change - https://github.com/grafana/k8s-monitoring-helm/pull/714 (cc/ @petewall).

Not sure why it is happening if [these conditions](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/Chart.yaml#L25) are really AND'ed as stated [here](https://github.com/grafana/k8s-monitoring-helm/pull/714#issue-2503937017).

Setting `logs.cluster_events.enabled` back to `true` fixes the installation issue (but leaves us with unnecessary `alloy-events` deployment we'd like to avoid in particular environments).
