### ISSUE TITLE
if .Values.config.name is not set, then .Values.config.create should be set to true to use default configuration

### ISSUE THREAD

**Issue by bite-weldon** [grafana/k8s-monitoring-helm#750]
When I deploy Grafana monitoring into AKS via the command generate by Grafana Cloud, I got this error

`Error: execution error at (k8s-monitoring/charts/beyla/templates/daemon-set.yaml:24:28): if .Values.config.name is not set, then .Values.config.create should be set to true to use default configuration`

here is the command:

```
helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "default" --create-namespace --values - <<EOF
cluster:
  name: my-cluster
externalServices:
  loki:
    host: https://xxxxxxx.grafana.net
    basicAuth:
      username: "1111"
      password: xxxxxxxx=
  tempo:
    host: https://xxxxxxx.grafana.net:443
    basicAuth:
      username: "2222"
      password: xxxxxxxxx=
metrics:
  enabled: false
  alloy:
    metricsTuning:
      useIntegrationAllowList: false
  cost:
    enabled: false
  kepler:
    enabled: false
  node-exporter:
    enabled: false
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: false
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
  grafanaCloudMetrics:
    enabled: true
opencost:
  enabled: false
  podAnnotations:
    kubernetes.azure.com/set-kube-service-host-fqdn: "true"
kube-state-metrics:
  enabled: false
  podAnnotations:
    kubernetes.azure.com/set-kube-service-host-fqdn: "true"
prometheus-node-exporter:
  enabled: false
prometheus-operator-crds:
  enabled: false
kepler:
  enabled: false
alloy:
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
alloy-events:
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
alloy-logs:
  controller:
    podAnnotations:
      kubernetes.azure.com/set-kube-service-host-fqdn: "true"
beyla:
  enabled: true
EOF
```

when I enable the Auto-instrumentation button, I will get this error and if disable the button all good

But I want to deploy the Beyla, can you give a help to fix it
