### ISSUE TITLE
Node affinity prometheus-node-exporter leading to issues with AKS deployment

### ISSUE THREAD

**Issue by tpcgold** [grafana/k8s-monitoring-helm#751]
I currently try to deploy Grafana k8s-monitoring via ArgoCD and HELM
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '1.5.2'
    chart: k8s-monitoring
    helm:
      values: |-
        cluster:
          name: "k8s"
        externalServices:
          prometheus:
            host: "https://prometheus-prod-01-eu-west-0.grafana.net"
            basicAuth:
              username: "${PROMETHEUS_USERNAME}"
              password: "${PROMETHEUS_PASSWORD}"
          loki:
            host: "https://logs-prod-eu-west-0.grafana.net"
            basicAuth:
              username: "${LOKI_USERNAME}"
              password: "${LOKI_PASSWORD}"
          tempo:
            host: "https://tempo-eu-west-0.grafana.net:443"
            basicAuth:
              username: "${TEMPO_USERNAME}"
              password: "${TEMPO_PASSWORD}"
        metrics:
          enabled: true
          alloy:
            metricsTuning:
              useIntegrationAllowList: true
          cost:
            enabled: true
          kepler:
            enabled: true
          node-exporter:
            enabled: true
        logs:
          enabled: true
          pod_logs:
            enabled: true
          cluster_events:
            enabled: true
        traces:
          enabled: true
        receivers:
          grpc:
            enabled: true
          http:
            enabled: true
          zipkin:
            enabled: true
          grafanaCloudMetrics:
            enabled: false
        opencost:
          enabled: true
          opencost:
            exporter:
              defaultClusterId: k8sLLASuite
            prometheus:
              external:
                url: "https://prometheus-prod-01-eu-west-0.grafana.net/api/prom"
          podAnnotations:
            kubernetes.azure.com/set-kube-service-host-fqdn: "true"
        kube-state-metrics:
          enabled: true
          podAnnotations:
            kubernetes.azure.com/set-kube-service-host-fqdn: "true"
        prometheus-node-exporter:
          enabled: true
          affinity: {}
        prometheus-operator-crds:
          enabled: true
        kepler:
          enabled: true
        alloy:
          controller:
            podAnnotations:
              kubernetes.azure.com/set-kube-service-host-fqdn: "true"
        alloy-events:
          controller:
            podAnnotations:
              kubernetes.azure.com/set-kube-service-host-fqdn: "true"
        alloy-logs:
          controller:
            podAnnotations:
              kubernetes.azure.com/set-kube-service-host-fqdn: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - Replace=true
```

but it seems i cannot overwrite the default annotation on 
prometheus-node-exporter:
     affinity: {}

so the template seems to pick the first available node pool randomly
![Image](https://github.com/user-attachments/assets/ebaa15fb-8b89-465d-8668-be05977acd32)

but this one is way too small to allocate that many pods. 
this affects all deamon sets (sometimes also kepler which currently seems to work)
![Image](https://github.com/user-attachments/assets/118dc03b-bbc9-4f1b-a036-484c742f1e68)

the issue as expected due to the affinity:
![Image](https://github.com/user-attachments/assets/9813db6c-107b-4c0f-a67e-1039cb9808f8)

**Comment by skl** [comment]
Possibly related bug:

- https://github.com/helm/helm/issues/12637

You could try and see if any of these ideas work:

- setting an empty string `affinity: ""` instead of `affinity: {}`
- setting some other valid affinity values for your environment instead
- last resort, disable node exporter deployment in k8s-monitoring-helm chart and deploy the node exporter helm chart separately:
  - Keep `metrics.node-exporter.enabled: true` (to scrape the metrics)
  - Set `prometheus-node-exporter.enabled: false` (to disable the deployment)
  - Create a second node exporter helm chart deployment using [necessary values](https://github.com/grafana/k8s-monitoring-helm/blob/90eabdedabaa6f1e730c5659af5a2d0c75a903a8/charts/k8s-monitoring/values.yaml#L2180-L2213) from k8s-monitoring-helm chart

**Comment by tpcgold** [comment]
just made a quick check with affinity: "" instead of affinity: {}
as expected this is not allowed:
![Image](https://github.com/user-attachments/assets/5c498a5b-6953-4e13-a26b-db751c9daad3)

futher more i would also need the possibility to disable the affinity for alloy (which is currently not supported with the chart)

**Comment by skl** [comment]
Pinging @petewall for thoughts here

**Comment by tpcgold** [comment]
Hey, there just debugged the node and found the issue is caused by Azure (what else 🤷)
if the Monitoring Plugin is active MS assigns an insane amount of resources to this specific Node pool and hence the node-exporter cannot be scheduled on this specific node. 
![Image](https://github.com/user-attachments/assets/01ffa774-7aee-448e-9ed6-643572203bc4)

Still: why the affinity overwrite `affinity: {}` did not work is still unclear,
but I was at least able to deploy until the next issue related to affinity:
https://github.com/grafana/k8s-monitoring-helm/issues/752

**Comment by petewall** [comment]
Can you retest this? The upstream helm bug seems to have been fixed.

**Comment by petewall** [comment]
Following up on this, checking the current state with chart 4.1.0 and Helm 4.1.4:

The Helm side of this is resolved. The upstream Helm bug (helm/helm#12637) that prevented null from overriding nested subchart values was fixed in Helm 3.17.1. With a recent Helm version, null overrides into subcharts work as expected.

The chart structure has changed. Since the original report, configuration of bundled telemetry services moved out of top-level subchart keys. The path is now:

```yaml
telemetryServices:
  node-exporter:
    affinity: null   # or your desired affinity
```

Note that `affinity: {}` will not clear the default. That’s standard Helm merge behavior, not a bug. Use `null` (with Helm 3.17.1+) to clear it.

Going to close this. The parts this chart controls are working. Please reopen if you’re hitting a specific scheduling problem on a current chart version that isn’t covered above.
