### ISSUE TITLE
how to reuse grafana and prometheus

### ISSUE THREAD

**Issue by jainpratik163** [grafana/k8s-monitoring-helm#769]
we already have Prometheus/grafana/node-exporter/metric server already installed in our eks env.
so how can we use this k8s-monitoring helm chart?

Are there any grafana dashboards shared?

**Comment by skl** [comment]
You can disable each dependent deployment using the `enabled` value of each subchart entry.

For example, to disable node exporter and kube-state-metrics from being deployed you can use [these](https://github.com/grafana/k8s-monitoring-helm/blob/77cfa298de969ffe07c6bc1577a64c1719aec316/charts/k8s-monitoring-v1/values.yaml#L2192) [values](https://github.com/grafana/k8s-monitoring-helm/blob/77cfa298de969ffe07c6bc1577a64c1719aec316/charts/k8s-monitoring-v1/values.yaml#L2230).

Note that you may also need to set the `labelMatchers` to discover your existing deployments if they don't match the defaults:

```yaml
metrics:
  kube-state-metrics:
    enabled: true
    labelMatchers:
      app.kubernetes.io/name: kube-state-metrics

  node-exporter:
    enabled: true
    labelMatchers:
      app.kubernetes.io/name: prometheus-node-exporter.*

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false
```

For dashboards compatible with k8s-monitoring-helm chart, you can use [Grafana Cloud Kubernetes Monitoring](https://grafana.com/solutions/kubernetes/) or the open-source [kubernetes-mixin](https://github.com/kubernetes-monitoring/kubernetes-mixin).
