### ISSUE TITLE
Adding extra labels to logs and metrics - what is the best way?

### ISSUE THREAD

**Issue by hobbesuk** [grafana/k8s-monitoring-helm#778]
Could someone help if what I'm trying to achieve is the right way to be going about this (and if it is help on the best way to do this). I would like to add some extra labels to the mertics and logs that are collected by the resources in this helm chart and sent to loki and mimir.

I have added some custom labels (with very low cardinality) to the resources in my cluster which I would like to then use in queries in loki and mimir.

I've been messing around with extraMetricRelabelingRules and extraRelabelingRules which look like from the docs what I want but the labels never appear in logs or metrics to then be queried on.

I picked up on some discussions that maybe this chart isn't designed for picking up custom labels, if thats the case is someone able to point me at a good resource on how I should be doing this sort of thing?

TIA!

**Comment by petewall** [comment]
Hello! There are so many ways to set labels.
Are your labels using static values? I.e. you know the value at deploy time?
Or, are you labels using values pulled from the workloads themselves?

Static labels are probably best set in the `externalLabels` section:

```yaml
externalServices:
  prometheus:
    externalLabels:
      region: northwest
```

Or, if you're scraping metrics from a workload and want to get a value from that, let me know some more details and I can help out.

**Comment by hobbesuk** [comment]
these are dynamic labels (e.g. for example which ring the instance comes from), so not a huge number of values but are specific to the pod etc.

**Comment by petewall** [comment]
v2 does indeed support adding labels to all metrics, its just been renamed from `externalLabels` to `extraLabels`:

```yaml
destinations:
- type: prometheus
  ...
  extraLabels:
    env: production
```

If the value for this label is dynamic, and you want to source it from an environment variable or from a configMap, the `extraLabelsFrom` section will do that. Here's an example:


```yaml
destinations:
- type: prometheus
  ...
  extraLabelsFrom:
    env: sys.env("ENVIRONMENT")

alloy-metrics:
  alloy:
    extraEnv:
      - name: ENVIRONMENT
        value: production // or wherever you want, as with https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
```
