### ISSUE TITLE
Add the ability to deploy a remotecfg block

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#779]
This would enable the alloy instances deployed by the chart to be interoperable with the fleet management work.

**Comment by petewall** [comment]
There can only be one `remotecfg`, so add something like this inside each `alloy` instance block:

```yaml
  remoteConfig:
    url: ""
    auth:
      type: "basic"
      username: ""
      password: ""
    id: <cluster-name>-<namespace>-<pod-name>
    pollFreq: 60s
    attributes:
      platform: kubernetes
      workloadType: statefulset
```
