### ISSUE TITLE
Struggling to configure `values.yaml` to scrape Prometheus Metrics from other K8S Services

### ISSUE THREAD

**Issue by M4tt-** [grafana/k8s-monitoring-helm#784]
Hi @petewall !

Hope you can lend me a hand: using k8s-monitoring v1.4.4, I'm trying to scrape Prometheus metrics that another microservice is exposing on AKS. This is a Java-based microservice that exposes the Prometheus metrics at an endpoint /actuator/prometheus on port 8080 using Micrometer.

I've verified that my field selector is valid and that I can successfully scrape these metrics at this end point using a standard OpenTelemetry Collector with a prometheus receiver using the config below.

```yaml
  prometheus:
    config:
      scrape_configs:
        - job_name: 'my_service_api-metrics'
          scrape_interval: 60s
          static_configs:
            - targets: ['my_service_api.api.svc.cluster.local:8080']
          metrics_path: '/actuator/prometheus'
```

I've configured the `values.yaml` for the chart as per the code snippet below. Am I missing something?

Configuration information:
- Kubernetes version: 1.28.5
- Helm Chart version: k8s-monitoring v1.4.4
- Helm Chart namespace: observability
- Application namespace: api

```yaml
cluster:
  name: "asms-XX-musea2-aks-shared"
externalServices:
  prometheus:
    host: https://prometheus-us-central2.grafana.net
    basicAuth:
      username: "1234567"
      password: "my-access-token"
  loki:
    host: https://logs-prod-us-central2.grafana.net
    basicAuth:
      username: "1234567"
      password: "my-access-token"
  tempo:
    host: https://tempo-prod-09-us-central2.grafana.net:443
    basicAuth:
      username: "1234567"
      password: "my-access-token"
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: false
  metrics:
  extraMetricRelabelingRules: |-
   rule {
      action        = "replace"
      replacement   = env("ENV")
      target_label  = "ENV"
    }
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
  grafanaCloudMetrics:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: "asms-XX-musea2-aks-shared"
    prometheus:
      external:
        url: https://prometheus-us-central2.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: false
prometheus-operator-crds:
  enabled: true
alloy:
  alloy: 
    extraEnv:
      - name: ENV
        value: XX
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
alloy-events:
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
alloy-logs:
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
alloy-profiles:
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
kube-state-metrics:
  podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
opencost:
  podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
extraConfig: |-
  discovery.kubernetes "my_service_api" {
    role = "service"
    namespaces {
      own_namespace = false
      names         = ["api"]
    }
    selectors {
      role  = "service"
      field = "metadata.name=my_service_api"
    }
  }

  prometheus.scrape "my_service_api" {
    job_name   = "my_service_api_prom_scrape"
    targets    = discovery.kubernetes.my_service_api.targets
    forward_to = [prometheus.remote_write.metrics_service.receiver]
  }

```
