### ISSUE TITLE
k8s-monitoring v2 doesn't allow setting discovery relabeling for node-exporter

### ISSUE THREAD

**Issue by mtweten** [grafana/k8s-monitoring-helm#800]
While playing around with the helm-monitoring v2 chart, I noticed  one feature that is possible in v1 is not possible (I think) in the v2 chart. Specifically, the ability to perform discovery relabeling for node-exporter. 

v1 allows this through the following configuration:

```yaml
metrics:
  enabled: true
  node-exporter:
    enabled: true
    extraRelabelingRules: |
      rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        action = "replace"
        target_label  = "nodename"
      }
```

In v2, the node-exporter scrape configuration is now using the [node-exporter alloy module](https://github.com/grafana/alloy-modules/blob/main/modules/system/node-exporter/metrics.alloy) which doesn't expose the ability to set any additional discovery relabel configs (https://github.com/grafana/alloy-modules/blob/main/modules/system/node-exporter/metrics.alloy#L49C7-L138). Maybe this was intentionally not exposed, but I'm not sure.

Supporting this feature would require a change to the upstream alloy-module, it seems.
