### ISSUE TITLE
Allow basicAuth username/password to be sourced from secrets

### ISSUE THREAD

**Issue by adam-homeboost** [grafana/k8s-monitoring-helm#81]
We use terraform to control the configuration of this helm chart and it means that we have to check the raw username and password values into our terraform source code, which is a very bad practice.  It would be much safer and cleaner if we had the option of using values from regular kubernetes secrets which can be managed in a much more secure way.

**Comment by skl** [comment]
Would #47 help?

**Comment by LukaSvastVolue** [comment]
I dont think so #47 seems to only make secret creation optional, how would we pass the reference to the pre-existing secret than?

**Comment by skl** [comment]
Yes, I see. #47 I assumes that you would create the secret named as `grafana-agent-credentials` in the format defined [here](https://github.com/grafana/k8s-monitoring-helm/blob/f875a37bd4b97b7e508a6569c852542e9e523281/charts/k8s-monitoring/templates/credentials.yaml), but [other parts](https://github.com/grafana/k8s-monitoring-helm/blob/f875a37bd4b97b7e508a6569c852542e9e523281/charts/k8s-monitoring/templates/agent_config/_prometheus.river.txt#L7) of the chart template are conditional based on the username and password being non-empty in the values... so this looks like a valid feature request 👍

**Comment by adam-homeboost** [comment]
#47 does help.  Its fine for me if the names are mandated, though some flexibility would be nice.  The only quibble I would have is that in most charts I have seen "createX" means "create this resource as part of installing helm and generate the values for me randomly".  For charts using "existing" secrets, conf names tend to be more along the lines of "existingSecret<Name>", etc...

As @skl says though, other parts of the chart that are conditional based on username/password being non-empty do need to be addressed.

**Comment by MounaGC** [comment]
Yes , this will be a useful feature. Our use case is -terraform to deploy helm charts in kubernetes and we use CSI driver secrets in kubernetes. With the current approach the only way we can pass the secret is using the data source in terraform.

**Comment by LukaSvastVolue** [comment]
Any status updates or rough estimate on this @skl @petewall?

**Comment by caleb-devops** [comment]
In addition to this change, can this chart be updated to support [extraObjects](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/extra-manifests.yaml)? This would enable SealedSecrets or ExternalSecretes to be created with the Helm deployment.

**Comment by RobCannon** [comment]
As a workaround, I have created a new secret that is in the format of `grafana-agent-credentials`, which I named `k8s-grafana-cloud`.  Then I override the volume mounts in some of the daemonsets.  Here are the relevant changes to values.yaml:

```
        externalServices:
          prometheus:
            host: {{ .Values.prometheusHost }}
            basicAuth:
              username: "placeholder"
              password: "placeholder"
          loki:
            host: {{ .Values.lokiHost }}
            basicAuth:
              username: "placeholder"
              password: "placeholder"
        opencost:
          opencost:
            exporter:
              defaultClusterId: {{ .Values.accountName }}
            prometheus:
              secret_name: k8s-grafana-cloud
              external:
                url: "{{ .Values.prometheusHost }}/api/prom"
        grafana-agent:
          controller:
            volumes:
              extra:
              - name: grafana-agent-credentials
                secret:
                  secretName: k8s-grafana-cloud
        grafana-agent-logs:
          controller:
            volumes:
              extra:
              - name: grafana-agent-credentials
                secret:
                  secretName: k8s-grafana-cloud
```

An easier way to do this would be welcome.
