### ISSUE TITLE
v2: when configuring OTLP destination authMode needs to be used instead of auth.type

### ISSUE THREAD

**Issue by marcomusso** [grafana/k8s-monitoring-helm#844]
When defining an otlp/http destination like:

```
  - name: GrafanaCloudOTLP
    type: otlp
    protocol: http
    url: "{{ requiredEnv "GRAFANA_CLOUD_OTLP_HOST" }}/otlp"
    tenantId: "{{ requiredEnv "GRAFANA_CLOUD_INSTANCE_ID" }}"
    auth:
      type: basic
      username: "{{ requiredEnv "GRAFANA_CLOUD_INSTANCE_ID" }}"
      password: "{{ requiredEnv "GRAFANA_CLOUD_TOKEN" }}"
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
```

This creates an exporter WITHOUT client.auth thus generating 401 from the destination:

```
otelcol.exporter.otlphttp "grafanacloudotlp" {
  client {
    endpoint = "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
    headers = {
      "X-Scope-OrgID" = nonsensitive(remote.kubernetes.secret.grafanacloudotlp.data["tenantId"]),
    }
    tls {
      insecure = false
      insecure_skip_verify = false
      ca_pem = nonsensitive(remote.kubernetes.secret.grafanacloudotlp.data["ca"])
      cert_pem = nonsensitive(remote.kubernetes.secret.grafanacloudotlp.data["cert"])
      key_pem = remote.kubernetes.secret.grafanacloudotlp.data["key"]
    }
  }
}
```

Setting `authMode: basic` (single top level key) will result in the `auth` client attribute to be included:

```
otelcol.exporter.otlphttp "grafanacloudotlp" {
  client {
    endpoint = "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
    auth = otelcol.auth.basic.grafanacloudotlp.handler                       // HERE
    headers = {
      "X-Scope-OrgID" = nonsensitive(remote.kubernetes.secret.grafanacloudotlp.data["tenantId"]),
    }
    tls {
      insecure = false
      insecure_skip_verify = false
      ca_pem = nonsensitive(remote.kubernetes.secret.grafanacloudotlp.data["ca"])
      cert_pem = nonsensitive(remote.kubernetes.secret.grafanacloudotlp.data["cert"])
      key_pem = remote.kubernetes.secret.grafanacloudotlp.data["key"]
    }
  }
}
```

But `authMode` is not documented anywhere and instead `auth.type` should be used like for other destinations.

Reference: https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/templates/destinations/_destination_otlp.tpl#L68
