### ISSUE TITLE
v2: alloy_integration_discovery not using the correct labelSelector

### ISSUE THREAD

**Issue by marcomusso** [grafana/k8s-monitoring-helm#880]
I enabled alloy integrations for all deployed alloys (metrics, logs, receiver, singletong) via the metrics one with:

```
integrations:
  destinations: []
  alloy:
    instances:
      - name: alloy-metrics
        labelSelectors:
          app.kubernetes.io/name: alloy-metrics
      - name: alloy-logs
        labelSelectors:
          app.kubernetes.io/name: alloy-logs
      - name: alloy-receivers
        labelSelectors:
          app.kubernetes.io/name: alloy-receiver
      - name: alloy-singleton
        labelSelectors:
          app.kubernetes.io/name: alloy-singleton
```

but in the matrics alloy I see (snippet):

```
[...]
  alloy_integration_discovery "alloy_metrics" {
    port_name       = "http-metrics"
    label_selectors = ["app.kubernetes.io/name=alloy"]
  }

  alloy_integration_scrape  "alloy_metrics" {
    targets = alloy_integration_discovery.alloy_metrics.output
    clustering = true
    keep_metrics = "up|alloy_build_info"
    scrape_interval = "60s"
    max_cache_size = 100000
    forward_to = argument.metrics_destinations.value
  }

  alloy_integration_discovery "alloy_logs" {
    port_name       = "http-metrics"
    label_selectors = ["app.kubernetes.io/name=alloy"]
  }
[...]
```

It seems that the discovery is trying to always select name=alloy when the names are all different per feature.
Either that selector should be correct implicitly or, in this case, I expect it to be the one explicitly set in the values.
