### ISSUE TITLE
k8s-monitoring fails to launch pod logs and node exporter due to missing pod-security label

### ISSUE THREAD

**Issue by aretecarpe** [grafana/k8s-monitoring-helm#895]
grafana  k8s-monitoring chart fails due to it not containing the pod-security.kubernetes.io/enforce=privileged. Is there a way to add a label via a values.yaml?

**Comment by petewall** [comment]
in v1:
```
prometheus-node-exporter:
  podLabels:
    pod-security.kubernetes.io/enforce: privileged
alloy-logs:
  controller:
    podLabels:
```

**Comment by petewall** [comment]
Yep, in v2, it should be this:
```
clusterMetrics:
  node-exporter:
    podLabels:
      pod-security.kubernetes.io/enforce: privileged
alloy-logs:
  controller:
    podLabels:
      pod-security.kubernetes.io/enforce: privileged
```
