### ISSUE TITLE
Helm chart test improvements

### ISSUE THREAD

**Issue by petewall** [grafana/k8s-monitoring-helm#917]
1. `test-manifest.yaml` should include a cluster section:
```yaml
cluster:
  type: kind
  config: cluster.yaml
```

2. `test-manifest.yaml` should change `prerequisites` to `deployments`
3. Include `k8s-monitoring` and `k8s-monitoring-test` as entries in the deployments
4. Add a `test: true` to run `helm test` after deployment
5. Change the special handling for `grafana` to a `skipOnHeadless: true` and related ENV var.
