### ISSUE TITLE
Adding labels to telemetry based on namespace in k8s-monitoring-helm v2.

### ISSUE THREAD

**Issue by cxk314** [grafana/k8s-monitoring-helm#956]
Hi,
Is it possible to add custom transformation rule or processor to attach custom label to any telemetry (logs, metrics, events, traces) based on namespace where that it is coming from? Where should it be added? In `destinations.processors` or in `alloy-receiver.extraConfig`? How should I build it? Will this work? Or there is better way to do it?

```
alloy-receiver:
  # -- Deploy the Alloy instance for opening receivers to collect application data.
  # @section -- Collectors - Alloy Receiver
  enabled: true
  controller:
    podAnnotations: {kubernetes.azure.com/set-kube-service-host-fqdn: "true"}
  extraConfig: |-
    otelcol.processor.transform "default" {
      error_mode = "ignore"
    
      trace_statements {
        context = "span"
        statements = [
          `set(attributes["my-label"], "pass") where attributes["k8s.namespace.name"] == "my-label-value"`,
        ]
      }
    
      output {
        metrics = [otelcol.exporter.otlp.default.input]
        logs    = [otelcol.exporter.otlp.default.input]
        traces  = [otelcol.exporter.otlp.default.input]
      }
    }
```
Is there an easy way to test this? If I want to debug those conditions and see what attributes are actually there is there a way to do this?

**Comment by petewall** [comment]
It's worth noting that the `extraConfig` can only add components, it cannot affect the components that already exist.

To add a transform rule, you can either set one per destination, or in the applicationObservability feature:

```yaml
destinations:
  - name: my-destination
    type: otlp
    host: otlp-gateway.example.com
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}
    processors:
      transform:
        traces:
          span:
            - set(attributes["my-label"], "pass") where attributes["k8s.namespace.name"] == "my-label-value"

applicationObservability:
  enabled: true
  traces:
    transforms:
      span:
        - set(attributes["my-label"], "pass") where attributes["k8s.namespace.name"] == "my-label-value"
```
