### ISSUE TITLE
v2: TLS caFile in destinations not set in configmap

### ISSUE THREAD

**Issue by william413215** [grafana/k8s-monitoring-helm#972]
We just switched from v1 to v2 in our test environment and it seems that the caFile parameter is not set in the configmap.

```
k8s-monitoring:
  cluster:
    name: XXXXXXXX

  destinations:
    - name: test-metrics
      type: prometheus
      url: https://XXXXXXXX
      tls:
        caFile: /etc/cert/ca.crt
      ...
```
