### ISSUE TITLE
Dropping metrics when shipping to grafana cloud doesn't seem to work

### ISSUE THREAD

**Issue by gnur** [grafana/k8s-monitoring-helm#975]
We're using almost the basic example that grafana cloud generates for you when going through the tutorial, as we have a lot of metrics (150k+) and we're reaching the limit of the free trial we're trying to reduce to also get an estimate of what the costs might be if we transition.

We've tried dropping metrics in all kinds of ways but they always seem to continue showing up in grafana cloud. If possible we'd like to drop it using alloy (and not in the grafana cloud interface) as we can compare the various environments that are also shipping to on-site prometheus instances.

This is the config we're using:

```
metrics:
  enabled: true
  autoDiscover:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  kube-state-metrics:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  kubelet:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  kubeletResource:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  cadvisor:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  apiserver:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  podMonitors:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
  probes:
    metricsTuning:
      excludeMetrics:
        #filter these metrics based on usage in grafana cloud
        - 'apiserver_.*'
        - 'cilium_.*'
        - 'etcd_.*'
```

And we've confirmed that they also show up in the configmap generated by the helm chart:

```
<snip>
    prometheus.relabel "annotation_autodiscovery" {
      max_cache_size = 100000
      rule {
        source_labels = ["__name__"]
        regex = "apiserver_.*|cilium_.*|etcd_.*"
        action = "drop"
      }
      forward_to = [prometheus.relabel.metrics_service.receiver]
    }
</snip>
```

But the metrics still show up in grafana cloud without being dropped. Is there some other way to set a global exclude. The way we're doing it right now feels a bit error-prone and copy-pasta like.
