### ISSUE TITLE
v2.0.0-rc.7 otlp destination - produced zero addresses

### ISSUE THREAD

**Issue by ceastman-r7** [grafana/k8s-monitoring-helm#977]
error from alloy-logs pod logs:

ts=2024-12-07T16:18:59.020913631Z level=info msg="Exporting failed. Will retry the request after interval." component_path=/ component_id=otelcol.exporter.otlp.otlpgateway error="rpc error: code = Unavailable desc = last resolver error: produced zero addresses" interval=4.945336661s

error from alloy-metrics pod logs:

ts=2024-12-07T18:03:17.745659015Z level=error msg="Exporting failed. Dropping data." component_path=/ component_id=otelcol.exporter.otlp.otlpgateway error="interrupted due to shutdown: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: authentication handshake failed: credentials: cannot check peer: missing selected ALPN property\"" dropped_items=5

config:
```
destinations:
  - name: otlpGateway
    type: otlp
    url: https://otlp-gateway-prod-us-east-0.grafana.net
    auth:
      type: basic
      username: "redacted"
      password: "redacted"
    metrics: { enabled: true }
    logs:    { enabled: true }
    traces:  { enabled: true }
```

**Comment by petewall** [comment]
Can you try a few things for me?
When I've used the Grafana Cloud OTLP Gateway, I used this destination:
```yaml
destinations:
  - name: otlp-gateway
    type: otlp
    url: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
    protocol: http
    auth:
      type: basic
      username: ...
      password: ...
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}
```

So, can you add `/otlp` to the `url` field, and set `protocol: http` and let me know if this works?
