### ISSUE TITLE
v2.0.0-rc.7 opencost validation is incorrect

### ISSUE THREAD

**Issue by ceastman-r7** [grafana/k8s-monitoring-helm#978]
With the following config:

```
clusterMetrics:
  enabled: true
  opencost:
    enabled: true
    metricsSource: promGateway
    opencost:
      exporter:
        defaultClusterId: redacted
      prometheus:
        external:
          url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom
        existingSecretName: promgateway-grafana-k8s-monitoring
```

I get this validation error:

Error: UPGRADE FAILED: execution error at (k8s-monitoring/templates/validations.yaml:9:6): 
```
OpenCost requires the secret for promGateway to be set.
Please set:
clusterMetrics:
  opencost:
    opencost:
      prometheus:
        existingSecretName: otlpgateway-grafana-k8s-monitoring
```
