### ISSUE TITLE
v2.0 name of Alloy modules configmaps do not respect fullnameOverride

### ISSUE THREAD

**Issue by splichy** [grafana/k8s-monitoring-helm#994]
We are using ArgoCD, so our .Release.Name is quite long. For clarity, we are using fullnameOverride where possible.

With the following values:
```
clusterMetrics:
  enabled: true
  kepler:
    fullnameOverride: kepler
  opencost:
    fullnameOverride: opencost
podLogs:
  enabled: true
nodeLogs:
  enabled: true
clusterEvents:
  enabled: true

alloy-metrics:
  fullnameOverride: alloy-metrics
  enabled: true
alloy-logs:
  fullnameOverride: alloy-logs
  enabled: true
alloy-singleton:
  fullnameOverride: alloy-singleton
  enabled: true
```
we are getting nice, clean names - except for alloy modules configmaps whose names are like: `very-long-release-name-alloy-module-kubernetes`

There is hardcoded .Release.Name in https://github.com/grafana/k8s-monitoring-helm/blob/e94d0b5c03d46ecee1f08c25e66e4ac50f87dfa4/charts/k8s-monitoring/templates/alloy-modules-configmaps.yaml#L9C3-L9C91 and on the other places(references to created configmap name in Alloy features).
